Canadian-Geospatial-Platform/geoview

public/css/style.css

On my laptop (and mobile) the height of the maps in the examples exceed the viewport, which makes it harder to interact with them. This change constrains the example maps to `90vh` (to give some leeway).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/230)

docs(style): Constrain maps to a maximum of `90vh`

---

packages/geoview-core/src/core/components/click-marker/click-marker.tsx
packages/geoview-core/src/core/components/crosshair/crosshair.tsx
packages/geoview-core/src/core/types/cgp-leaflet-config.ts
packages/geoview-core/src/core/types/marker-cluster-element.d.ts
packages/geoview-core/src/core/types/marker-cluster-element.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/layer/vector/marker-cluster.ts

Some section of the code didn't use the types appropriately. Did not correct everything, but it a starting point.
Type usage rectification is on the marker cluster feature of GeoView.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/371)

refactor(marker-cluster): Type usage rectification on the marker cluster feature

---

docs/app/components-packages.md
packages/geoview-core/public/templates/layers.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

Added properties inheritance as specified in the WMS standard.
Added a catch on the methode that load the legend images. When there is an error, a null value is returned instead of a canvas.
Changed isDynamicLayerGroup to isMetadataLayerGroup to eliminate confusion with esri-dynamic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)

618-WMS metadata extent bug

---

packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/public/templates/legend.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts

Correction to the Esri Dynamic visibility bug. You can use the legend.html or the test.html to verify the behaviour of the new code.
Cancel old PR 605-esri-dynamic-layer-visibility and the related PR 642
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/651)

605-Esri-dynamic-layer-visibility-bug-resolution

---

packages/geoview-core/public/geojson/metadata.json
packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/public/templates/test.html
packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts
packages/geoview-core/src/api/events/payloads/get-legends-payload.ts
packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
packages/geoview-core/src/core/components/details/details-api.ts
packages/geoview-core/src/core/components/legend/legend-api.ts
packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/core/components/legend/legend.tsx
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/layer-set.ts
packages/geoview-core/src/ui/list/list-item-button.tsx
packages/geoview-core/src/ui/list/list-item-icon.tsx

Three changes:
#673 - Clipped canvas bug in legends
#674 - Duplicate geoview layer creation bug
#675 - Confusing property names
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/676)

676-Legend and duplicate geoview layer bug

---

packages/geoview-basemap-panel/src/basemap-panel.tsx
packages/geoview-core/public/templates/layers.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/schema.json
packages/geoview-core/src/api/events/payloads/map-view-projection-payload.ts
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts
packages/geoview-core/src/geo/layer/basemap/basemap.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/map/map.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

To test, use the test.html template. It has an example of a WMS configured with an extent and having a bounds derived from the service metadata. It also have an example using a WFS and a smaller bounds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/716)

715-Add bounds to the schema and the code

---

packages/geoview-core/public/templates/test.html
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts

This PR correct the metadata group layer bug and the getBounds improvment.
A good candidat to test the metadata group layer correction is layerId=1 and metadataAccessPath=https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/723)

721-Hierarchical geoview bug

---

packages/geoview-core/public/templates/layers.html
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts

While fixing the conflicts, I noticed that the time dimension has been added in the layerEntryConfig object. So far, most of the properties of the layerEntryConfig object have a mapping to the schema entries. There are some exceptions, but this is to chain the entries together. The schema does not contain a definition for the temporalDimension property. I think we should place this property on the instance of the WMS objects to avoid breaking the mapping rule between the schema and the configuration objects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/802)

Solution for issue 714-WMS-unsupported-query

---

packages/geoview-core/public/configs/package-footer2-config-footer-panel.json
packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
packages/geoview-core/src/ui/tabs/tabs.tsx
packages/geoview-footer-panel/schema.json
packages/geoview-footer-panel/src/index.tsx

Closes #842
Default behaviour for footer-panel is initially collapsed. Clicking a tab now opens it, and there is a setting in the config to change initial behaviour.
Fixes #842 
- [x ] New feature (non-breaking change which adds functionality)
Tested on the three footer panel maps, with setting in config file for the second map set to true and false.
- [x ] I have connected the issues(s) to this PR
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
-  ~~New and existing …

feat(footer-panel): Panel collapsed on map load

---

packages/geoview-core/src/core/components/overview-map/overview-map-toggle.tsx
packages/geoview-core/src/core/components/overview-map/overview-map.tsx

Add solid background and tooltip to minimap toggle button
Fixes # (847)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/883)

add background to mini map button and tooltip

---

packages/geoview-core/public/geojson/metadata.json
packages/geoview-core/public/templates/layers.html
packages/geoview-core/schema.json
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/other/geocore.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/renderer/esri-renderer.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

The values that can be assigned to the visible flag of unique value and class break are now 'always', 'yes' and 'no'.
GeoCore layer names can now be specified in the layer configuration.
Esri layers now keep layer's metadata in the geoview layer object.
Unique value now verify the type of the fields (string / number) and adapt the filter accordingly
Fixes # 538 and 668
Using the Layers template and verifying that the show/hide and always show behave as expexted.
Edit the config file many times.
- - - …

538-Add_a_flag_to_layers_configuration_items

---

packages/geoview-core/public/templates/default-config.html
packages/geoview-core/public/templates/package-layers-panel.html
packages/geoview-core/src/app.tsx
packages/geoview-layers-panel/src/panel-content.tsx

closes #856
Re enable the EVENT EVENT_MAP_RELOAD with the all handler name to allow the map to be reloaded. This is use to switch projection in layers-package demo file. At the same repair the load by url in default config demo page.
Fixes # (856)
Run package-layers-panel.html and switch projection
Run default-config.html and look at map 5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/888)

fix(demo): default config url and switch projection for layers package

---

packages/geoview-core/public/configs/my-config.json
packages/geoview-core/public/templates/codedoc.js
packages/geoview-core/public/templates/layers.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/schema.json
packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/map/map.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

Style filtering exploits the grouping capacity of the geoview WMS layers. We can now place the same layerId on the map many times and assign a style to each of them. The filtering is done by showing/hiding the layer associated to a style.
It is now possible to place comments in the config files using /* and */, but not with //.
Fixes only issue 870
Using the test.html template.
To test, click the Legend button and use the show/hide buttons associated to each entry in the table..
- - - …

870-Implement_WMS_style_filtering

---

packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/ui/tabs/tabs.tsx
packages/geoview-footer-panel/src/legend-item.tsx

Closes #778
Closes #890
Cluster toggle added to the legend menu. Legend items are now expanded by default, clicking on the open tab closes the panel. issues with footer panel tabs fixed.
Fixes #778
Fixes #890 
I added the cluster toggle to the footer panel for testing to test it on all layers in /package-footer-panel.html, and then tested it in the layer-panel menu after adding the esri dynamic layer to the map in package-layers-panel.html. Legend tab behaviour was tested throughout those tests.
- - - …

feat(cluster): Toggle for clustering added to legend

---

packages/geoview-core/schema.json

Closes #844
Changed zoom to number in schema as openlayers allows for non integer values.
Fixes #844 
Checked codebase for anywhere zoom was required to be an integer, tested maps with non integer zoom valuees.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/895)

fix(zoom): Zoom changed from int to number

---

packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/core/components/nav-bar/export-modal.tsx

Fix the legend menu focus and export button dialog when dialog is shown.
Fixes # ([906](https://github.com/canadian-geospatial-platform/geoview/issues/906))
Manually tested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/911)

fix legend menu and export btn autofocus

---

packages/geoview-core/public/geojson/metadata.json
packages/geoview-core/public/templates/codedoc.js
packages/geoview-core/public/templates/layers.html
packages/geoview-core/schema.json
packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts
packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
packages/geoview-core/src/core/components/details/details-api.ts
packages/geoview-core/src/core/components/details/feature-info.tsx
packages/geoview-core/src/core/components/legend/legend.tsx
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/map/map.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

Correction to a bug found in the unique value find routine in geoviewRenderer.
The values returned by the get feature info call have a new type. It contains the field names, the field types, the field values, the field aliases, the feature with its style set to the right value, the extent, the domain for esri featuresand an entry key.
Fixes # 877
The tests were done using the layers template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914)

887-getAllFeatureInfo_and_getFeatureInfo_result_formatting

---

packages/geoview-core/public/configs/cluster-config.json
packages/geoview-core/public/geojson/lines.json
packages/geoview-core/public/geojson/polygons.json
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts
packages/geoview-core/src/core/utils/config/reader/json-config-reader.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

This PR is to correct a bug introduced in PR Legend filtering does not cover clustering #869 and merged with https://github.com/Canadian-Geospatial-Platform/geoview/pull/930.
Fixes #869
Fixes #930
Open the cluster template and look in the console. The stack dump displayed at load time is not supposed to be there anymore. Look at the first map, you will see two cluster with a different color. One is for Polygons and the other for LineStrings. Zoom in and the clusters will be replaced by the clustered geometry.
- - - …

932-Cluster_template_correction

---

packages/geoview-swiper/src/swiper.tsx

Closes #901
Fixes swiper bar dividing map based on mouse pointer location rather than bar position.
Fixes # 901
Lots of dragging with both vertical and horizontal alignments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/936)

fix(swiper): Fixed the division not being in the center of swiper bar

---

packages/geoview-core/public/templates/layers-temporal.html
packages/geoview-core/schema.json
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-swiper/src/swiper.tsx

Moved the time dimension from the layerEntryConfig instance to the geoviewLayer instance. The time dimension is now in this.layerTimeDimension[path to the layerEntryConfig]
Fixes #804
Using the layers-temporal.html template and the DevTool debugger. Run the template and expand the Time Dimension section below the map. Set a breakpoint and look in cgpv.api.map('the_map_id').layer.geoviewLayers['the_geoview_layer_id'].layerTemporalDimension['the_layer_entry_path'] to confirm everything is set properly.
- - - …

804 move temporal dimension on geoview instances

---

packages/geoview-core/public/templates/layers-temporal.html
packages/geoview-core/public/templates/layers.html
packages/geoview-core/schema.json
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/map/map-schema-types.ts

The problem is not caused by the use of a http call. It is the hydro layer that define a style that points to a bad http query that returns an error saying htat the layer parameter mentioned in the http query is bad. I wrote a correction to avoid the error trace in the console and returned an undefined legend entry (null).
Fixes #735
Using the layers.html template and the DevTool debugger. Run the template and look at the legend to see the 8 undefined entry for the hydro.
- - - …

735-Enforce https for image

---

packages/geoview-core/src/core/components/legend/legend.tsx
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map.ts
packages/geoview-layers-panel/src/layer-stepper.tsx
packages/geoview-layers-panel/src/panel-content.tsx
packages/geoview-layers-panel/src/reorder-layers-list.tsx

Closes #629
Closes #736
Layers now follow the order specified in the config, with the first layer being on the top. Layers can now be reordered in the layers panel.
Checked layers on the layers page for correct orders, enabled layers panel on WMS layer map to move layers around. Also added and moved layers on layers-panel page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/950)

feat(layers): Layers follow config order and can be moved

---

packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
packages/geoview-core/src/core/components/legend/legend-item.tsx

add filter map button in data grid table, and filter the map by clicking
Fixes #886
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
In footer panel, data tab:
1. click the "Filter" button to set a column filter 
2. The "Filter map" button would be clickable, click it:
The layer icons on the map would be hidden
Only showing the filtered feature info icons
The "Filter" button would be disabled
The "Filter map" button would be changed to "Remove Filter map"
3. Click "Remove Filter map" button:
The filter on the map would be removed, all the layer icons would be showing on the map
The button would be changed back to "Filter map"
The "Filter" button would be clickable. 
- [ X ] I have connected the issues(s) to this …

886 data grid filters the map

---

packages/geoview-core/public/templates/layers.html
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/renderer/geoview-renderer-types.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

This PR resolve three issues:
- The `initialSettings` visibility flag is not working properly;
- The `Package - Layers Panel` generate a stack dump when adding a GeoJSON layer;
- The query filter does not accept `is null` and `is not null` operations.
Fixes #982, #983 and #984
Using the devTools to trace and verify that the code behave as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/985)

982-Visibility-settings-bug

---

packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/layerlib.js
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/schema.json
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/ui/slider/slider-base.tsx
packages/geoview-layers-panel/src/layer-stepper.tsx

When the validation of the configuration is done with the help of the schema and an error is detected, the code in its current state prints an avalanche of messages making the detection of the error particularly difficult. In order to facilitate the interpretation of the error report by our users, we need to reduce the error log to its simplest form.
The validation is now done in two phases. The first phase validates the configuration of the map up to the level of the typeListOfLayerEntryConfig entries. The second phase is recursive and processes the entries of the configuration list according to the depth level.
The group creation algorithm has been rewritten to correct the problem.
Openlayers side effect: It should be noted that the visibility flag of a group that is alone in another …

1017 reduce schema validation verbosity

---

packages/geoview-core/src/geo/layer/vector/vector.ts

Capability to specify the projection of the coordinates when using the vector class to draw on map
Fixes #1019
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1020)

Capability to specify the projection of the coordinates when using the vector class to draw on map

---

packages/geoview-core/public/configs/cluster-config.json
packages/geoview-core/public/templates/cluster.html
packages/geoview-core/schema.json
packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/core/components/map/map.tsx
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts

Closes #1026
Closes #1000 
Clustering updated to be two separate layers.
Clusters automatically split at set zoom level (default 8).
Clusters keep same colours as their individual Points, LineStrings, or Polygons.
Tested on cluster.html with layers panel added. Checked toggle fuctionality and colour cohesion on all layers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1041)

refactor(cluster): update cluster to utilize two layers

---

packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts

Closes #998
calculateBounds function has been added for all layers, it will provide bounds. trimmed to fit in the layer or map extents, in the maps given projection.
- [ x New feature (non-breaking change which adds functionality)
Checked with each of the raster layers on their html pages. Will require further testing once functionality is being used in zoom to layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1057)

fix(geo): calculateBounds function added to all layers

---

packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/core/utils/utilities.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts

Closes #1058
Moved calculteBounds to abstract-geoview-layer, each layer type (or abstract-vector-layer) has its own getBounds function, and getMinOrMaxExtents added to utilities.
Tested with all layer types, using as many different layers as were readily available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1069)

fix(calculateBounds): moved function to abstract

---

packages/geoview-core/public/geojson/metadata.json
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/map/map.ts

All vector layers do not apply initialSettings.
Fixes #1071-Vector_layers_do_not_apply_initialSettings
Using the test.html template and the chrome devtools debugger to see that everythings work as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1072)

1071-Vector_layers_do_not_apply_initialSettings

---

packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/geopackage.html
packages/geoview-core/public/templates/layers/image-static.html
packages/geoview-core/public/templates/layers/layerlib.js
packages/geoview-core/public/templates/layers/ogc-feature.html
packages/geoview-core/public/templates/layers/wfs.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/pygeoapi-processes.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/src/api/api.ts
packages/geoview-core/src/core/components/details/details-api.ts
packages/geoview-core/src/core/components/legend/legend-api.ts
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/date-mgt.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/legends-layer-set.ts
packages/geoview-details-panel/src/details-item.tsx
packages/geoview-footer-panel/src/details-item.tsx
packages/geoview-footer-panel/src/index.tsx

Modify the legendLayerSet and the featureInfoLayerSet so that there is only one instance per map.
The singleton design patern will be used for the implementation.
Fixes #1073-Use_singleton_patern_for_layerSets
Using the chrome devtools by tracing all type of layer templates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1074)

1073-Use_singleton_patern_for_layerSets

---

packages/geoview-layers-panel/src/layer-stepper.tsx

Closes #820
Removed projection check from layer-stepper
Tried https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png in 3978 projection in http://localhost:8081/package-layers-panel.html 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1096)

fix(xyz projection): removed projection requirement from layer stepper

---

packages/geoview-core/public/templates/raw-feature-info.html
packages/geoview-core/src/core/components/feature-info/feature-info.tsx
packages/geoview-core/src/ui/accordion/accordion.tsx

Add loading icon to Accordion component. This feature can be enabled by setting `showLoadingIcon` prop to true. By default, this prop is set to `false`.
Also, we can have a condition to check if the number of elements in accordion is more than X.
For example:
`showLoadingIcon: arrayOfItemsInAccordion.length > X`
Fixes #1161 
Open accordion and some of its items and sub-item. Then try to close the accordion. We should be able to see the loading indicating accordion is closing.
- - - …

feat(accordion): Add loading icon to accordion

---

packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/src/core/components/app-bar/app-bar.tsx
packages/geoview-core/src/core/components/app-bar/buttons/version.tsx
packages/geoview-core/src/core/utils/constant.ts
packages/geoview-core/src/ui/index.ts
packages/geoview-core/src/ui/popover/popover.tsx

We need to have a Popover component to be used in AppBar to show the version of the application and a link to GitHub to know more about project.
The version button will be always in AppBar section.
Fixes #1112 
Open any of the maps in demo site. The version button should be at the bottom of the AppBar and a popover feature should be displayed once we click on version icon. Make sure once the popover is opened, the state of the version icon is active.
https://amir-azma.github.io/geoview/index.html
- - - …

feat(version-appbar): Add version feature as popover in appbar

---

packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/geopackage.html
packages/geoview-core/public/templates/layers/image-static.html
packages/geoview-core/public/templates/layers/ogc-feature.html
packages/geoview-core/public/templates/layers/vector-tiles.html
packages/geoview-core/public/templates/layers/wfs.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/layers/xyz.html
packages/geoview-core/src/api/events/payloads/layer-set-payload.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/layer-set.ts

Pull Request 1016-Improve-loading-time added to the viewer the layerPhase property on each GeoView layer. Pull Request 1128-Run-init-for-all-maps removed it. Since that this property was a hit in presentations, we need to restore it.
This PR also add the layerName property to the layerSets.
Fixes #1209 
Using the templates in Type Of Layers and the chrome devtools to trace and debug the code and see that the phase is properly displayed on the layer pages.
URL for the deployment: https://ychoquet.github.io/GeoView/type-of-layers.html
- - - …

1209-Restore-the-layerPhase-property

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/package.json
packages/geoview-core/public/templates/basemaps.html
packages/geoview-core/src/core/components/map/map.tsx
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts

Changes to extents are reflected on maps - use of config extents in LLC projections generates warning. Also fixed issue with WMS styles showing incorrect legend image.
Fixes # 643
Fixes # 1218
Added extents to last two maps on basemaps.html (remaining in code), hardcoded changes to basemap default extents.
[__https://damonu2.github.io/geoview/basemaps.html__](https://damonu2.github.io/geoview/basemaps.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform …

fix(config): changing config extent has no effect

---

packages/geoview-details-panel/src/details-item.tsx
packages/geoview-footer-panel/src/details-item.tsx
packages/geoview-footer-panel/src/legend-item.tsx
packages/geoview-layers-panel/src/layer-stepper.tsx
packages/geoview-layers-panel/src/panel-content.tsx

Some GeoView events are listening to the same event name and use a different handler function to react to the event. When we create events, we must keep a reference to the handler function so that when we want to unregister the listener, we can provide the handler to make sure we deactivate only the targeted listener because if we don't do that, all handlers will be deactivated.
Fixes #1076 
https://amir-azma.github.io/geoview/
- - - …

refactor(unregister-event): Refactor useEffect for unregister event

---

packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
packages/geoview-core/src/core/components/legend/legend-item.tsx
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/layer-set.ts
packages/geoview-footer-panel/src/data-item.tsx
packages/geoview-layers-panel/src/panel-content.tsx

Closes #1104
Closes #1242
Closes #1067
Fixes multiple legend issues:
legend layer set now updates properly
legend add/remove functions utilize layer sets
visibility of layers and sublayers is not overridden by legend
Fixed the legend layer set to update when changes are made to layers, and updated the add/remove layer functions to utilize layer sets. Visibility of layers and sublayers now initially set by config and/or style settings.
Tested primarily with the footer-panel page, where various settings are used to control initial visibility. Also tested in layers-panel with add/remove layers.
https://damonu2.github.io/geoview/package-footer-panel.html
-  ~~I have added tests that prove my fix is effective or that my feature …

fix/refactor(legend): legend fixes

---

packages/geoview-core/src/ui/icons/index.ts

Closes #1245 
This code change simplifies how we import icons.
It uses `export {...} from '@mui/icons-material';`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1246)

simplify how we import icons

---

packages/geoview-core/src/core/utils/utilities.ts

Utility functions to add a notification, quickly, and show a message WITH (or without) a notification alongside it - so that a dev only has 1 method to call from its development level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1273)

Utility functions to add a notification quickly and improved showMessage() functions too

---

packages/geoview-core/src/core/components/scale/scale.tsx
packages/geoview-core/src/ui/modal/modal.tsx

CLoses #1268
Open any page and scalebar is there on load
__Add the URL for your deploy!__ https://jolevesq.github.io/geoview/vector.html
- - - …

fix(scale): Set scale on load, not waiting for the first map move

---

packages/geoview-core/src/core/components/data-table/map-data-table.tsx

Add `min` and `max` filters for data table.
Fixes # ([1251](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1251))
- [] Bug fix (non-breaking change which fixes an issue)
- - - …

fix(DataTable): add min and max filters for datatable Closes #1251

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/src/core/components/geolocator/geo-list.tsx
packages/geoview-core/src/ui/style/style.css

Closes #1260
With css, remove display of default overview map control. The better improvement would be to trap the screen size and prevent the creation of the duplicate control. But because it will not happen often, this can be a patch for now.
Fixes #1260
Got the page in link on a map were there is an overview map and resize the screen. No more other control
https://jolevesq.github.io/geoview/default-config.html?p=3857&z=4&c=-100,40&l=en&t=dark&b={basemapId:transport,shaded:false,l …

fix(overview): Remove display of overview duplication on resize

---

packages/geoview-core/src/geo/renderer/geoview-renderer.ts

Fixes error when filtering text entries with null values
Fixes # 1250
Tested with both new and old data tables.
https://damonu2.github.io/geoview/raw-data-table.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1324)

fix(filter): null values don't break 'like' filters

---

packages/geoview-core/src/core/components/data-table/map-data-table.tsx
packages/geoview-core/src/geo/renderer/geoview-renderer.ts

fixes #1311
Also removes case-sensitivity from 'like' map filters to match what is shown in table
Fixed issue with queries getting 'upper' added to them, causing errors for non-string values, also removes case-sensitivity in map filter queries to match table results.
Fixes # 1311
Tested with historical flood on raw-data-table.html
https://damonu2.github.io/geoview/raw-data-table.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1325)

fix(filter): fixed error with 'upper' in filter query

---

packages/geoview-core/src/api/events/event.ts

A bug has been found in the events class. The object used to keep track of events does not clean up normally when once events are executed. The aim of the fix is to use the background mechanism of the eventEmitter class to keep track of active events.
Fixes #1330 Event refactoring
Using the chrome devtools to trace an verifying that everithing work properly.
__Deploy URL:__ https://ychoquet.github.io/GeoView/
- - - …

1330-Event refactoring

---

packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/geopackage.html
packages/geoview-core/public/templates/layers/image-static.html
packages/geoview-core/public/templates/layers/ogc-feature.html
packages/geoview-core/public/templates/layers/vector-tiles.html
packages/geoview-core/public/templates/layers/wfs.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/layers/xyz.html
packages/geoview-core/public/templates/package-swiper.html
packages/geoview-core/src/geo/layer/geoview-layers/raster/abstract-geoview-raster.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/layer.ts

fixes #1337
loadend events moved to raster layers and abstract-geoview-vector, so the 'loaded' status is applied to sublayers of groups.
Checked by fetching the registeredGeoviewLayers from the api and checking for 'loaded' layerStatus for each of the layer types.
https://damonu2.github.io/geoview/type-of-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1355)

fix(layerStatus): 'loaded' handling refactored for groups

---

packages/geoview-core/public/configs/raw-data-table.json
packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/public/templates/raw-data-table.html
packages/geoview-core/src/core/components/data-table/data-panel.tsx
packages/geoview-core/src/core/components/data-table/map-data-table.tsx

Update language of data table components like filter mode, filter message, toggle density.
Fixes # ([1309](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1309))
- - - …

fix(DataTable): datatable language Closes #1309

---

packages/geoview-core/public/templates/codedoc.js

I would like to suggest this alternate method of showing code snippet in the html interface.
Enhanced code snippet generator which allows to associate a script id with a code snippet script (og function is using indexes) and write down different code snippet spreaded in the dom tree (og function always reuses 'script' variable which is the last script tag found in the dom).
- - - …

New createCodeSnippet2 function in codedoc.js

---

packages/geoview-core/src/geo/layer/layer.ts

New getGeoviewLayerByIdAsync function mimicking the getGeoviewLayerById, but awaitable. That way, you can run asynchronous code that awaits for the layer to be loaded, before returning the layer.
This has been tested during Clip Zip Ship GeoView development.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1371)

New getGeoviewLayerByIdAsync function mimicking the getGeoviewLayerById

---

packages/geoview-core/src/api/events/payloads/payload-base-class.ts

At the time of development of GeoChart, the events were still going to be handled by api and PayloadBaseClass principles. I'm not sure if this is super relevant at this time, but for GeoChart it is.
The `api.event.emit` works in pair with a `PayloadBaseClass` which is tightly coupled with a fixed `EventStringId` type - only valid for core events.
To be able to leverage that concept and still be able to use `api.event.emit`, I wanted to have plugin-specific events inheriting the `PayloadBaseClass` and providing an extended list of event-names (which is the sum of the { events in the core} + {events in the plugin}).
Turning the class generic and accepting any type 'inheriting' from EventStringId allows this functionality.
Tested as part of the GeoChart plugin development.
-  ~~I have made …

PayloadBaseClass now generic

---

packages/geoview-core/src/ui/index.ts
packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-enhanced.tsx

I would like to suggest an enhanced checkbox list component which uses key-values (instead of indexes) to maintain state and offers an option to inject another component on the right side of each item for further customization. It is used by Clip Zip Ship GeoView application.
It was tested as part of the Clip Zip Ship GeoView development.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1372)

An 'enhanced' checkbox list component

---

packages/geoview-core/src/api/events/constants/feature-highlight-constants.ts
packages/geoview-core/src/api/events/event-types.ts
packages/geoview-core/src/api/events/payloads/bbox-highlight-payload.ts
packages/geoview-core/src/core/components/click-marker/click-marker.tsx
packages/geoview-core/src/core/components/geolocator/geolocator.tsx
packages/geoview-core/src/ui/snackbar/snackbar.tsx

Fixes #1300
Fixes #1308
Fixes issue with snackbar button appearing without content. Also fixes geolocator zoom levels to be zoomed closer to result, and displaying a bounding box of the feature (if it exists) for 5 seconds.
Tested with many different search results throughout the country.
https://damonu2.github.io/geoview/basemaps.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1367)

fix(geolocator): geolocator zooms in closer to results

---

packages/geoview-core/public/templates/basemaps.html
packages/geoview-core/src/core/components/map/map.tsx
packages/geoview-core/src/geo/layer/basemap/basemap.ts
packages/geoview-core/src/ui/snackbar/snackbar.tsx

Fixes #1387
Fixes #703
Loads a blank basemap at map creation before loading actual basemap. Also updates extent handling to use transformExtent which makes extent useable (if a bit clunky) for LCC projections.
Tested with most demo pages, testing somewhat incomplete with basemap servers currently down. Will require further testing, especially on package-basemap-panel.html once basemaps are back.
https://damonu2.github.io/geoview/basemaps.html
- - - …

feat(basemap): load a blank basemap initially

---

packages/geoview-core/src/core/components/app-bar/app-bar-buttons.ts
packages/geoview-core/src/core/components/app-bar/app-bar.tsx
packages/geoview-core/src/ui/panel/panel-types.ts
packages/geoview-core/src/ui/panel/panel.tsx

For the purpose of using HTML canvas drawing (notably for the GeoChart), I needed to know when the panel has completed expanding, to force a redraw of the canvas. Of course, this PR focuses on implementing the callback logic without knowledge of the specific reason for the callback. It can serve other purposes too.
Tested as part of the GeoChart plugin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1368)

Added a new optional callback when the panel has completed transitioning and is fully opened

---

packages/geoview-core/public/geojson/points.json
packages/geoview-core/public/templates/raw-feature-info-1.html
packages/geoview-core/src/core/components/details-1/details-1-style.ts
packages/geoview-core/src/core/components/details-1/feature-info-table.tsx
packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx
packages/geoview-footer-panel/src/details-item.tsx

We need to display long texts and images in Details tab (right panel) in order to show the full text similar to screenshot below:
Fixes #1361 
Please select a point on map in order to load the layers in left panel, and its features on right panel. In case we have images, the need to take the full length of the right panel container, and long texts should display properly.
https://amir-azma.github.io/geoview/raw-feature-info-1.html
- - - …

feat(right-panel-style): Refactor details right panel, support long text and images

---

packages/geoview-core/public/templates/codedoc.js

Further improved the new `createCodeSnippetUsingIDs` function to be able to not only point to different scripts in the html template, but **stack** different scripts on top of each other in the UI (to be able to show standardized code which might be re-using common functions throughout the template).
During development of the template for Geoview-geochart.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1390)

Further improved createCodeSnippetUsingIDs for multiple scripts stacking

---

packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/utilities.ts

Correction to the map loaded bug when a server is down..
Fixes #1423
Using the Chrome Devtool, force a get metadata error to simulate a server not responding error (downtime simulation). This test can only be done on a localhost. 
__Deploy URL:__ https://ychoquet.github.io/GeoView/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1430)

1423-[BUG] Map loaded is not fired

---

packages/.eslintrc
packages/geoview-core/src/api/plugin/plugin.ts
packages/geoview-core/src/app.tsx
packages/geoview-core/src/core/components/map/map.tsx
packages/geoview-core/src/core/utils/utilities.ts
packages/geoview-core/src/geo/layer/basemap/basemap.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-layers-panel/src/layer-stepper.tsx

Added a rule about using 'async' strictly if a function is using 'await' keyword and enforcing the return to be a Promise.
Maybe needs particular attention around the initMap() function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1435)

Added a rule about having an await if a function has the 'async' keyword

---

packages/geoview-core/src/core/components/details/details.tsx
packages/geoview-core/src/core/components/details/layers-list-footer.tsx
packages/geoview-core/src/core/stores/geoview-store.ts

We need to use store management in our Details tab. Also, the left panel selected layer should be the same as our previous layer selected.
Fixes #1376 
https://amir-azma.github.io/geoview/raw-feature-info-1.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)

fix(layer-selection) Pre select the previously selected layer in left panel

---

packages/geoview-core/public/configs/raw-data-table.json
packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/public/templates/legend.html
packages/geoview-core/public/templates/raw-feature-info-1.html
packages/geoview-core/schema.json
packages/geoview-core/src/core/components/details/details-style.ts
packages/geoview-core/src/core/components/details/feature-info-new.tsx
packages/geoview-core/src/core/components/details/layers-list-footer.tsx
packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
packages/geoview-core/src/core/components/nav-bar/buttons/fucos.tsx
packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/ui/icons/index.ts

We would like to easily go from map to footer element and minimize the scrolling. We have added 3 focus button, and we will keep the one that works the best for the focus purpose.
Fixes #1135
https://amir-azma.github.io/geoview/raw-feature-info-1.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1450)

feat(focus-btn): Add focus button on the map and footer, refactor css

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/src/api/eventProcessors/feature-info-event-processor.ts
packages/geoview-core/src/core/components/details/layers-list-footer.tsx
packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts

Elimination of the phantom click and correction to the hover result sets overwriting the click result sets.
Fixes #1480
Using the Chrome Devtools to trace and debug the raw-feature-info-1.html template.
__URL for the deploy:__ https://ychoquet.github.io/GeoView/raw-feature-info-1.html
- [] I have created new issue(s) related to the outcome of this PR is needed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1485)

1480-Bugs-With-New-Store-Strategy

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/src/core/components/details/layers-list-footer.tsx

Solution was pretty simple. Only one line added.
Fixes #1487
1- Display the raw-feature-info-1.html template;
2- Zoom the map to a zone where you see overlapping features of different layers and empty areas;
3- select the Details tab;
4- You should see many layers on the left and information of the first feature on the first layer in the right panel;
5- Click on an empty zone in the map;
6- Everything disapear but the right panel remains there and it should not.
- - - …

1487-BUG_Details right panel should be empty

---

packages/geoview-core/src/ui/accordion/accordion.tsx
packages/geoview-core/src/ui/select/select.tsx

This adds 'sx' support to the Accordion component and reverts a recent modification on the way the Select works with the MenuItems.
The Accordion was tested in Clip Zip Ship plugin.
The Select was tested in GeoChart component and in Layers Panel plugin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1512)

Adding sx support to the Accordion and reverting the Select component to using the react 'children' props for the MenuItems

---

packages/geoview-core/src/core/components/common/close-button.tsx
packages/geoview-core/src/core/components/common/responsive-grid.tsx
packages/geoview-core/src/core/components/data-table/data-panel.tsx
packages/geoview-core/src/core/components/details/details-panel.tsx
packages/geoview-core/src/core/components/time-slider/time-slider-panel.tsx

Show left panel as default view when browser is resized in responsive grid.
Fixes # (1510)
1. https://kaminderpal.github.io/geoview/raw-data-table.html
2. https://kaminderpal.github.io/geoview/raw-feature-info-1.html
3. https://kaminderpal.github.io/geoview/package-time-slider.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatia …

fix(datatable): show default layer list on mobile and tablet  #1510

---

packages/geoview-core/src/core/components/attribution/attribution-style.ts
packages/geoview-core/src/core/components/attribution/attribution.tsx
packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx
packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx
packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts
packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
packages/geoview-core/src/core/components/mouse-position/mouse-position-style.ts

Fixes issues in footer-bar that the map and footer-bar extend outside of the div containing them, which cuts off the overview-map and footer-bar. This also causes some shaking when mousing over the map.
Added 3 dots icon in small size pages that will open in popover component to display the attributions.
Fixes #1406 
Please open footer-bar and try to resize the page in different sizes, the Fix North and Overview map should not get cut from the container div, we should not have shaking map in some areas if we hover the map, also we should be able to use popover content of attribution.
https://amir-azma.github.io/geoview/index.html
-  ~~New and …

feat(footer-bar): Refactor footer-bar, attribution and more

---

packages/geoview-time-slider/src/index.tsx
packages/geoview-time-slider/src/time-slider-panel.tsx

Display layer name instead of layer path for the list of layers displayed under time slider section
Fixes # (1524)
- https://mayurmarakana89.github.io/geoview/package-time-slider.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1537)

fix(time-slider): fix layer display name on time slider #1524

---

packages/geoview-core/src/core/components/attribution/attribution.tsx
packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
packages/geoview-core/src/core/components/footer-tabs/footer-tabs-style.ts
packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
packages/geoview-core/src/ui/tabs/tabs.tsx

Fix some issues related to footer tab, and footer bar. Make the footer bar responsive so we can navigate and select all tabs when screen is on mobile. To minimize the number of controls, we only keep one button for focus and full screen when tab is open. Remove collapse/expand.
Fixes #1574 
To minimize the number of controls, we only keep one button for focus and full screen when tab is open. Remove collapse/expand.
- - - …

feat(footer-bar-responsive): Make the footer bar responsive

---

packages/geoview-core/src/core/components/common/layer-list.tsx
packages/geoview-core/src/core/components/details/details-panel.tsx

Add disabled state for layer list item which have 0 features and fix the selection of layer list when layer list is changed on map layer is clicked.
Fixes # ([1544](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1544))
- - - …

feat(details): add disabled state for details layer list  #1544

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts

A single line correction to use the group name instead of the layer name. This PR also includes a correction to the getBounds implementation.
Fixes #1637
Using Chrome Devtools to trace and debug the geojson.html template.
__Deploy URL to test:__ https://ychoquet.github.io/GeoView/geojson.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1639)

1637-Wrong-group-name

---

packages/geoview-core/.babelrc
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/layer/other/cluster-placeholder.ts
packages/geoview-core/src/geo/layer/other/geocore.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/renderer/geoview-renderer.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts

This PR is part of #528
[Use config-validation for auto completing all kinds of GeoView layers](https://github.com/Canadian-Geospatial-Platform/geoview/issues/528).
Fixes # Part of issue 528
Using Chrome Devtools and templates from [Type of layers](https://ychoquet.github.io/GeoView/type-of-layers.html).
__Deploy URL:__ https://ychoquet.github.io/GeoView/type-of-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)

Move config validation to layerConfig object

---

packages/geoview-core/public/geojson/metadata.json
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/map/map-schema-types.ts

Correction applied to resolve the bug with group layers following the "Move-config-validation-to-layerConfig-objects" PR.
Fixes #1673
Using Chrome Devtools and [Basic Details](https://ychoquet.github.io/GeoView/raw-feature-info.html) templates.
__Deploy URL:__ https://ychoquet.github.io/GeoView/raw-feature-info.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1677)

BUG following Move-config-validation-to-layerConfig-objects

---

packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts

The images in icon stack component have bad resolutions, because we tried to change the size of original image, and in cases the image is so small, we will see the small pixels on image that makes it in bad resolution.
Fixes #1680 
Please visit Legend, Layers and Details tab that include the icon stack. We needed to apply the image width and height to the correct image container.
- - - …

refactor(icon-stack): Fix icon stack resolution

---

packages/geoview-core/src/ui/slider/slider-base.tsx

Fixing the Slider-Base to a middle-ground of what it was before Jan 1st.
For usage from GeoChart external component which had gotten broken.
**Hosted here: https://alex-nrcan.github.io/geoview/**
***Note that the GeoChart component is broken in this host, because it's using an old version of the cgpv (circular dependency), so can't test GeoChart, but can test other Slider-Base usage.**
In GeoChart component and in Layers opacity functionality.
- - - …

[FIX] Quick fix trying to find middle-ground between changes from Jan 1st and GeoChart needs.

---

packages/geoview-core/public/configs/loading-packages-config.json
packages/geoview-core/public/configs/package-bp1-lcc-config.json
packages/geoview-core/public/configs/package-bp2-wm-config.json
packages/geoview-core/public/configs/package-footer-panel-geochart-map1-config.json
packages/geoview-core/public/configs/package-footer-panel-geochart-map2-config.json
packages/geoview-core/public/configs/package-geochart-map1-config.json
packages/geoview-core/public/configs/package-geochart-map2-config.json
packages/geoview-core/public/configs/package-swiper-config.json
packages/geoview-core/public/configs/package-time-slider-config.json
packages/geoview-core/public/configs/package-time-slider2-config.json
packages/geoview-core/public/configs/raw-data-table.json
packages/geoview-core/public/configs/sample-config.json
packages/geoview-core/schema.json
packages/geoview-core/src/api/event-processors/index.ts
packages/geoview-core/src/api/plugin/plugin.ts
packages/geoview-core/src/core/components/app-bar/app-bar.tsx
packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
packages/geoview-core/src/core/components/map/map.tsx
packages/geoview-core/src/core/stores/geoview-store.ts
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/logger.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/abstract-geoview-raster.ts
packages/geoview-core/src/geo/layer/other/cluster-placeholder.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-geochart/src/geochart.tsx

Removed the loadPlugin(s) functions as we're now loading plugins 3 ways, not just corePackages anymore.
added support to load plugins in the app-bar similar to footer-tabs.
core packages simplified, now only for swiper at the moment.
Fixes #1699
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1712)

[FIX] plugins simplification and usage of app-bar for plugins

---

packages/geoview-core/src/geo/utils/feature-info-layer-set.ts

Fix for the feature-info-propagation to store. To be approved before merging as not entirely sure of impacts...
Essentially moving the line `FeatureInfoEventProcessor.propagateFeatureInfoToStore(mapId, layerPath, 'click', this.resultSets);` in the other callback method, when `this.resultSet` has more layer paths.
Hosted: https://alex-nrcan.github.io/geoview/package-footer-panel-geochart.html
- - - …

[FIX] Fix for the feature-info-propagation to store

---

packages/geoview-core/src/core/components/common/layer-list.tsx
packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/ui/tabs/tabs.tsx

Fix footer tabs loading when page loads, now only one panel will load and rest will be loaded when user click on each tab.
Fixes # ([1731](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1731))
https://kaminderpal.github.io/geoview/package-time-slider.html
https://kaminderpal.github.io/geoview/package-footer-panel-geochart.html
- - - …

fix(footerTabs): fixes tabs of footer panel loading  #closes1731

---

packages/geoview-core/public/templates/layers/layerlib.js
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts

Verified and changed the code of all getFeatureInfo to make them follow the rule that says they must return a null if there is a query error.
Fixes #892
Using Chrome devtools to trace and debbug the code.
__Deploy URL__: https://ychoquet.github.io/GeoView
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1787)

892-BUG_getFeatureInfo_getLegend_errors_fails_the_viewer

---

packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/layerlib.js
packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/events/constants/get-feature-info-constants.ts
packages/geoview-core/src/api/events/event-types.ts
packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/layer-set.ts
packages/geoview-core/src/geo/utils/legends-layer-set.ts

Added a triggerGetAllFeatureInfo to the feature info layer set and simplified the logic of the propagateFeatureInfoToStore static method of the feature-info-event-processor. The store also have a triggerGetAllFeatureInfo action.
Fixes #1802
Using Chrome Devtools and the esri-feature.html template. The Get All Feature Info below the first map has a dropdown to test the new code.
__Deploy URL__: https://ychoquet.github.io/GeoView/esri-feature.html
- - - …

1802 implement trigger get all feature info and simplify event processor

---

packages/geoview-core/public/templates/default-config.html
packages/geoview-core/src/api/events/payloads/get-legends-payload.ts
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts
packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts

Geocore keys by div attribute with data-geocore-keys.
Fixes #816 
Hosted here as of Feb 22nd 12h45: https://alex-nrcan.github.io/geoview/
Here in particular: https://alex-nrcan.github.io/geoview/default-config.html?p=3857&z=4&c=-100,40&l=en&t=dark&b={basemapId:transport,shaded:false,labeled:true}&i=dynamic&cc=overview-map&keys=12acd145-626a-49eb-b850-0a59c9bc7506,ccc75c12-5acc-4a6a-959f-ef6f621147b9#HLCONF5B
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platfor …

feature(geocorekeysdiv) Geocore keys by div attribute with data-geocore-keys.

---

packages/geoview-core/public/configs/package-swiper-config-swiper.json
packages/geoview-core/public/configs/package-swiper2-config-swiper.json
packages/geoview-core/public/configs/package-swiper3-config-swiper.json
packages/geoview-core/public/templates/package-swiper.html
packages/geoview-core/src/api/event-processors/abstract-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/swiper-event-processor.ts
packages/geoview-core/src/api/event-processors/index.ts
packages/geoview-core/src/api/plugin/map-plugin.tsx
packages/geoview-core/src/core/app-start.tsx
packages/geoview-core/src/core/components/guide/guide-panel.tsx
packages/geoview-core/src/core/stores/geoview-store.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/swiper-state.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-geochart/src/index.tsx
packages/geoview-layers-panel/src/layers-list.tsx
packages/geoview-swiper/src/index.tsx
packages/geoview-swiper/src/swiper-style.ts
packages/geoview-swiper/src/swiper.tsx

Stores created
Style class created and separated from component
Fix for the path for the guide panel
Swiper, working state
Swiper improved
Moved the addEventListener and removeEventListener from the rendering phase to a useEffect mount hook.
Better logs and comments
Swiper working
Had to use async afterall to retrieve the OpenLayers layers
Adjusting the swiper template configs to use layer path
Finalizing
Cleanup
Fixes #1820
Hosted here as of Feb. 26 15h: https://alex-nrcan.github.io/geoview/package-swiper.html
- - - …

feature(Swiper) - Using new Swiper store, small guide fix, better info logs, some other fixes and comments

---

packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/legends-layer-set.ts

Modifications to the feature-info-event-processor and the legends-layer-set files to resolve the propagation issue. The problem was that the queryable flag of a layer, if not set in the config file, was known only when the metadata were loaded. At that point in time, the registration of the queryable layers from the config file was done, but those relying on the metadata were never registered. A call to registerToLayerSets was added in the LegendsLayerSet instance to register those layers  when the metadata are loded.
Fixes #1866
As usual, using the Chrome Devtools
__Deploy URL__: https://ychoquet.github.io/GeoView/all-layers.html
-  ~~New and …

1866-BUG-Bad_feature_info_propagation_to_store

---

packages/geoview-core/src/core/components/app-bar/buttons/version.tsx
packages/geoview-core/src/core/components/common/layer-list.tsx
packages/geoview-core/src/core/components/notifications/notifications.tsx
packages/geoview-core/src/ui/popper/popper.tsx

This PR does two things;
* Make Popper dissapear when user click ESC key.
* Disable clicking layers when they are in loading mode.
Fixes #1870
https://cphelefu.github.io/geoview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869)

making popper dissapear on esc click

---

packages/geoview-core/public/templates/sandbox.html
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/app.tsx
packages/geoview-core/src/core/app-start.tsx
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Prevents click/hover queries on a static map
Fixes #1768 
Hosted here as of Feb 28 13h45 : https://alex-nrcan.github.io/geoview/sandbox.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1864)

fix(click-static-map) Prevents click/hover queries on a static map

---

.github/workflows/type-build.yml
docs/app/geoview-layer/map-config/draw.io/TypeMapConfig.drawio.svg
packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/schema.json
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/components/data-table/data-panel.tsx
packages/geoview-core/src/core/components/details/details-panel.tsx
packages/geoview-core/src/core/components/layers/hooks/helpers.ts
packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
packages/geoview-core/src/core/components/legend/legend.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/layer/other/geocore.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/utils/layer-set.ts
packages/geoview-core/src/geo/utils/legends-layer-set.ts
packages/geoview-geochart/src/geochart-panel.tsx
packages/geoview-time-slider/src/time-slider-panel.tsx

Closes #1852
Layer order now maintains geocore layers in the proper location when they switch to the actual layer type.
https://damonu2.github.io/geoview/all-layers.html
https://damonu2.github.io/geoview/geocore.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)

fix(geocore): refactor layerOrder to keep geocore in proper order

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/api/events/event.ts
packages/geoview-core/src/core/components/export/export-modal-button.tsx
packages/geoview-core/src/core/components/map/map.tsx
packages/geoview-core/src/core/stores/geoview-store.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
packages/geoview-core/src/geo/layer/other/geocore.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/ui/popper/popper.tsx

Fixes the projections swapping
New serialization principles inside the LayerConfig classes, for the store.
Projections working
Some comments
Removed an old eslint line disabled
Rush update
Getting rid of 2 eslint warnings elsewhere
Removed dead code after changes in another PR
Removed comment about renaming the config types/classes, it's already in progress in other PR
Fixes #1728 
Hosted as of Feb 29 8h15 here: https://alex-nrcan.github.io/geoview/projections.html#HPRJ3
- - - …

fix(projections.html) Fixes the projections swapping and serialization for store

---

packages/geoview-core/src/core/components/data-table/data-table.tsx

Closes #1874
Fixed number filters in data table not properly applying to map.
Tested with various number columns and all filter types
https://damonu2.github.io/geoview/raw-feature-info.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1875)

fix(table): table filters fixed

---

packages/geoview-core/src/geo/map/map-schema-types.ts

Small fix to support geocore configs that aren't transformed to classes?
Hosted here as of Feb 29 13h35: https://alex-nrcan.github.io/geoview/geocore.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1882)

fix(geocore) Fix for temporary geocore support of configs

---

packages/geoview-core/public/css/style.css
packages/geoview-core/src/ui/panel/panel.tsx

This PR fixes how app-bar is displayed in small screens.
Fixes #1819 
This is what it looks like in mobile now.
Also notice the minor changes to the demo header (CSS changes). Now demo pages look like this at the top.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1895)

fix appbar in mobile/small screens

---

packages/geoview-core/src/app.tsx

cgpv.api had the event and plugins spreaded on top of the api itself, causing redundancy. This PR fixes it and forces devs to use the correct object: cgpv.api.event or cgpv.api.plugin.
Hosted as of March 13 16h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1920)

fix(api) Fix the api leaking redundancy

---

packages/geoview-core/public/templates/layers/csv.html
packages/geoview-core/public/templates/layers/esri-image.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/geopackage.html
packages/geoview-core/public/templates/layers/image-static.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/pygeoapi-processes.html
packages/geoview-core/src/api/api.ts
packages/geoview-core/src/geo/index.ts
packages/geoview-core/src/geo/layer/layer.ts

Move layerSets instanciation from Api class to Layer class..
Fixes #1918
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1919)

Instanciate layerSets in Layer class

---

packages/geoview-core/src/api/event-processors/abstract-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
packages/geoview-core/src/core/components/common/layer-list.tsx
packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx
packages/geoview-core/src/core/components/details/details-panel.tsx
packages/geoview-core/src/core/components/details/feature-info-new.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/layer-set.ts

This quick PR is part of a series of PR and has a dependency on PR #1942 
This particular one focuses on removing 2 types:
- TypeArrayOfLayerData => TypeLayerData[]
- TypeArrayOfFeatureInfoEntries => TypeFeatureInfoEntry[] | undefined | null
The second type, especially, was causing gotchas for developers and some issues. Having both types like this is much more straightforward and will help when we need to refactor further code.
- - -
This change …

refactor(layers) - Part 3

---

packages/geoview-geochart/src/geochart-parsing.ts
packages/geoview-geochart/src/geochart.tsx

This quick PR is part of a series of PR and has a dependency on PR: #1943 
This particular one focuses on work on geoview-geochart package that needed adjusting after the types naming in PR: #1943 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1944)

refactor(layers) - Part 3b

---

packages/geoview-core/src/api/events/event.ts
packages/geoview-core/src/api/events/payloads/layer-set-payload.ts
packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts
packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/layer-set.ts
packages/geoview-core/src/geo/utils/legends-layer-set.ts

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1944
It is a swinging board for the other PRs.
This PR focuses on simply rewriting code to use specific events to bring lots of clarity in the processing flow.
- Moved generic events REQUEST_LAYER_INVENTORY, LAYER_REGISTRATION, LAYER_SET.UPDATED, CHANGE_LAYER_STATUS, QUERY_LEGEND, LEGEND_INFO to specific events for further refactoring... this is temporary. _Lots more to come in upcoming PRs on this as they get integrated better._
- Simplified some code in layer-set with regards to registration conditions. _More to come in upcoming PRs on this._
-  ~~I have made …

refactor(layers) - Part 4

---

packages/geoview-core/src/api/events/event.ts
packages/geoview-core/src/api/events/payloads/layer-set-payload.ts
packages/geoview-core/src/core/utils/config/validation-classes/heatmap-layer-entry-config.ts
packages/geoview-core/src/core/utils/config/validation-classes/tile-layer-entry-config.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/utils/layer-set.ts

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1945
This PR focuses on the `REQUEST_LAYER_INVENTORY` event. After reviewing the code, it turns out that since the layer sets are part of the layer-api orchestrator and the layer-api is created along with the map (before the layers are loaded), there was no need for that event at all.
- Removed the code surrounding the REQUEST_LAYER_INVENTORY event
- Removed unnecessary overrides in 2 classes
-  ~~New and existing unit tests pass …

refactor(layers) - Part 5

---

packages/geoview-core/src/api/events/event.ts
packages/geoview-core/src/api/events/payloads/layer-set-payload.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/layer-set.ts

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1946
This PR focuses on the `LAYER_REGISTRATION` event.
- Rewrote the code related to the registering of the layers between the abstract-geoview-layers class and the layer-api orchestrator
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/ …

refactor(layers) - Part 6

---

packages/geoview-core/public/templates/geometry.html
packages/geoview-core/src/api/events/event-helper.ts
packages/geoview-core/src/api/events/index.ts
packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
packages/geoview-core/src/geo/interaction/draw.ts
packages/geoview-core/src/geo/interaction/extent.ts
packages/geoview-core/src/geo/interaction/modify.ts
packages/geoview-core/src/geo/interaction/select.ts
packages/geoview-core/src/geo/interaction/translate.ts
packages/geoview-core/src/geo/layer/geometry/geometry.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-core/src/ui/modal/modal-api.ts

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1948
This particular one focuses on work on the creation of an EventHelper class to streamline even further the ease to create class-level events and rewriting some earlier code in this PR series to align with it.
- - - …

refactor(layers) - Part 8

---

packages/geoview-core/public/templates/layers/csv.html
packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/geopackage.html
packages/geoview-core/public/templates/layers/ogc-feature.html
packages/geoview-core/public/templates/layers/wfs.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/pygeoapi-processes.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/src/geo/utils/feature-info-layer-set.ts

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1950
This PR focuses on reactivating the code that was commented out in the templates with regards to `ALL_QUERIES_DONE`. The feature-info-layer-set emits a class-event when it's done querying something.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geosp …

refactor(layers) - Part 10

---

packages/geoview-core/public/templates/layers/csv.html
packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/ogc-feature.html
packages/geoview-core/public/templates/layers/wfs.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/pygeoapi-processes.html
packages/geoview-core/public/templates/test.html
packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
packages/geoview-core/src/geo/layer/layer.ts

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1952
- Fixed some templates so they use the correct cgpv.init() callback depending on what the template code is trying to achieve.
- Tying the knot by re-adding a layer added event to be listened to by outside, not listened by our own core;
- Modified a bit the Event response after adding a layer, minor;
- - - …

refactor(layers) - Part 12

---

packages/geoview-core/src/core/components/common/layer-list.tsx
packages/geoview-core/src/core/components/common/layout.tsx
packages/geoview-core/src/core/components/export/export-modal.tsx
packages/geoview-core/src/core/components/guide/guide-panel.tsx
packages/geoview-core/src/core/components/icon-stack/icon-stack.tsx
packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
packages/geoview-core/src/core/containers/shell.tsx
packages/geoview-core/src/ui/list/checkbox-list/checkbox-list.tsx

In Layers tab, we can't navigate through the layer selection using keyboard tab. We should be able to use keyboard and select all layers and sub-layers, including the layer icons.
Fixes #1898 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1959)

fix(layer-accessibility): Fix layers keyboard navigation

---

packages/geoview-core/public/templates/layers-temporal.html
packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/esri-feature.html
packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/public/templates/raw-feature-info.html
packages/geoview-core/public/templates/ui-components.html
packages/geoview-core/src/api/event-processors/event-processor-children/data-table-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/layer.ts

There are at least two methods in the viewer for obtaining the Geoview layer using the layer path. In addition, one of them uses a property to encapsulate the layer path and uses this encapsulated property in other methods such as getOpacity, setOpacity, getVisible, setVisible and so on. This approach is ambiguous and obscures the actual use of the layer path. We want to eliminate this dangerous behavior from our code for a single method that doesn't hide the use of the layer path.
Fixes #1930
Using Chrome Devtools and the geoview templates.
__Deploy URL__: https://ychoquet.github.io/GeoView/index.html
-  ~~New and existing unit tests pass locally …

1930-REFACTOR_geoviewLayer_using_layerPath

---

packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts

Closes #1767
refactor hover to move it to map-state and propagate to the store only the values, no result set.
Fixes #1767
hosted April, 3 - 5pm: https://jolevesq.github.io/geoview/raw-feature-info.html
- - - …

refactor(hover): use store and map state

---

packages/geoview-core/public/templates/config-sandbox.html
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
packages/geoview-core/src/api/config/types/config-constants.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/api/config/uuid-config-reader.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts

Modification of the new config API to accept the new structure of the schema.
Fixes # 2103
Using Chrome Devtools.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)

Synchronous version of the new schema

---

packages/geoview-core/public/css/style.css
packages/geoview-core/public/templates/sandbox.html
packages/geoview-core/src/core/containers/shell.tsx

Implement map size width and height input fields on sandbox for rendering different size of maps.
Fixes #2102 
https://kaminderpal.github.io/geoview/sandbox.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2116)

feat(map): implement mapsize in sandbox page  #closes2102

---

packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/config-constants.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json

This PR groups two issues:
- The creation and activation of two schemas (input/internal) that validate hte configuration provided by the user and the the structure of the internal representation of the map and layer instances.
- The correction of the default maxExtent according to the projection code used.
Fixes #2121, 2122
Using Chrome Devtools to trace and debug the code.
- - - …

Input and internal schema validation plus  default maxExtent issue

---

packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts

Closes #1891
Fixes issue with missing style config causing errors in WMS layers
Added DSM Hillshade layer to first WMS map.
https://damonu2.github.io/geoview/wms.html#HLYR1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2111)

bug(WMS): error with empty style in HRDEM layers

---

packages/geoview-core/public/templates/sandbox.html
packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/swiper-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts
packages/geoview-core/src/app.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/app-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/swiper-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts
packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/hover-feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-time-slider/src/index.tsx

Fixes #2148
Hosted, May 21: 9AM: https://jolevesq.github.io/geoview/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154)

refactor(store): All state follow setterActions

---

docs/app/geoview-layer/map-config/README.md
docs/app/geoview-layer/map-config/draw.io/TypeMapFeaturesInstance.drawio.svg
packages/geoview-core/public/configs/validator/04-geocore.json
packages/geoview-core/public/templates/config-sandbox.html
packages/geoview-core/src/api/config/config-api.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
packages/geoview-core/src/api/config/types/config-constants.ts
packages/geoview-core/src/api/config/types/config-types.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/api/config/types/type-guards.ts
packages/geoview-core/src/api/config/utils.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts
packages/geoview-core/src/app.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/date-mgt.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Remove deprecated sections of the schema and implement inheritance in the schema to reduce repetitive structures.
Fixes #2170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2171)

2170-Schema cleanup and inheritance

---

packages/geoview-core/public/templates/config-sandbox.html
packages/geoview-core/src/api/config/config-api.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json

PR related to the implementation of  the getLayerConfig method of the ConfigApi.
The implementation only covers the default values for the GeoView layers and the returned vallues for the GeoCore layers. A new section must be added to the config-sandbox to test the code and display the result.
Fixes #2205
Using Chrome Devtool to trace and debug the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geo …

ConfigApi.getLayerConfig

---

.vscode/settings.json
packages/geoview-core/public/templates/demos/demo-function-event.html
packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx
packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
packages/geoview-core/src/core/components/legend/legend-layer.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts
packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts
packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
packages/geoview-core/src/core/utils/config/validation-classes/group-layer-entry-config.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/hover-feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/legends-layer-set.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts

Fourth spring-board PR focusing mainly on the LayerSets with a distinction between registering a layer-config and registering a layer.
- Changed a couple TypeLayerEntryConfig to ConfigBaseClass to better represent the actual object being used.
- Fixing the auto-switching to Details panel when we were changing a layer name via the event template
- Removed the layer config parameter in the create default style in the geoview-renderer class
Hosted, June 3rd: 16h45: https://alex-nrcan.github.io/geoview/
- - - …

refactor(layer-sets) - Fourth spring-board PR focusing mainly on the LayerSets

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/geo/layer/layer.ts

This PR is dependent on PR #2245 
This PR replaces 5 `calculateBounds()` calls, distributed in different region of code, with a simple get bounds from the store instead.
Hosted June 14th, 10h00: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2260)

refactor(layers-bounds) - Quick PR to see if calculate bounds can be simplified now

---

packages/geoview-core/src/api/config/uuid-config-reader.ts
packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer.ts

Adds outfields, aliases, and data types to layers that don't have them supplied by metadata, using query returns
Fixes #1470 
Add: ea4c0bdb-a63f-49a4-b14a-09c1560aad0b
Run: cgpv.api.maps.mapWM.layer.redefineFeatureFields('rcs.ea4c0bdb-a63f-49a4-b14a-09c1560aad0b.en/pub:WHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT', '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29', 'aliasFields')
Numbers should replace names in details
- - - …

feat(WMS): add feature info to layers

---

packages/geoview-core/public/templates/outliers.html
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2112
Updates icon image cache according to layer styles.
https://damonu2.github.io/geoview/outliers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2267)

fix(icons): Dynamically set icon cache

---

packages/geoview-core/public/templates/sandbox.html
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts

Fixes when a layer group visibility is false and the sub layers wouldn't get 'loaded'.
Fixes #2169
Pending host
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2268)

fix(layer-group-visibility) - Fixes when a layer group visibility is false and the sub layers wouldn't get 'loaded'

---

packages/geoview-core/public/configs/elections-canada-2019.json
packages/geoview-core/public/index.html
packages/geoview-core/public/templates/outliers/outlier-ESRI-feature-polygons.html
packages/geoview-core/public/templates/outliers/outlier-GeoAI.html
packages/geoview-core/public/templates/outliers/outlier-elections-2019.html
packages/geoview-core/public/templates/outliers/outlier-geometry.html
packages/geoview-core/public/templates/outliers/outlier-metadata.html
packages/geoview-core/public/templates/outliers/outlier-style.html
packages/geoview-core/public/templates/outliers/outliers.html
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-esri-layer-entry-config.ts
packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
packages/geoview-core/src/core/components/legend/legend-layer.tsx
packages/geoview-core/src/geo/layer/basemap/basemap.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts
packages/geoview-core/webpack.common.js

Closes #2212 
Closes #2251
Also split outlier demo page
Fixed bug where a missing time extent would cause the layer to fail. Also split outlier demo page into a few, and added a small performance boost for layer loading. Fixes ESRI layers with no geometryField not loading.
https://damonu2.github.io/geoview/outliers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2292)

fix(time dimension): Missing time extent won't crash layer

---

packages/geoview-core/public/templates/layers/wms.html
packages/geoview-core/src/api/plugin/abstract-plugin.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts

Geoview WMS layer implementation doesn't read properly the information returned by a getFeatureInfo processed by esri WMS services. A small adjustment to the code would resolve this issue.
Fixes #2302
Using Chrome Devtool to trace and debug the code.
__Deploy URL:__ https://ychoquet.github.io/GeoView/wms.html (use getFeatureInfo on Current Conditions and Canada Energy Regulator)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2308)

2302-BUG WMS getFeatureInfo Correction

---

packages/geoview-core/public/templates/sandbox.html
packages/geoview-core/src/core/components/export/export-modal.tsx
packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts

1) Fix default footer tab id when no legend is present in config file.
2) Selection of `View` as default layers toolbar when no legend exist.
Fixes #2299 
Fixes #2301 
https://kaminderpal.github.io/geoview/sandbox.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)

fix(layers): fix default footertabid  closes2299

---

packages/geoview-core/src/api/config/config-api.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/utils.ts

Making input and internal config validation uniform.
Fixes #2288
Using chrome Devtool to trace and debug the code.
__Deploy URL:__ https://ychoquet.github.io/GeoView/config-sandbox.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2289)

2288-Input and internal config validation

---

packages/geoview-core/public/templates/outliers/outlier-geometry.html
packages/geoview-core/src/app.tsx
packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/layer/other/geocore.ts

Closes #2284
Removes hard coding of languages in config validation.
Map changed to French: https://damonu2.github.io/geoview/outlier-geometry.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2319)

fix(language): Removed hardcoding of language

---

packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Safer zoomToExtent function, preventing an infinite loop in OpenLayers.
Hosted, June 27th, 11h30: https://alex-nrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/14-wms-layer.json
1- Zoom to Ice Cover layer
2- Notice how it doesn't break the application and causing an infinite loop anymore (open console to see the infinite loop in upstream)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2322)

fix(zoom-extent) - Safer zoomToExtent function, preventing an infinite loop in OpenLayers

---

packages/geoview-core/public/configs/navigator/05-zoom-layer.json
packages/geoview-core/schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/utils/constant.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2274
Improves the consistency of zooming to a layer extent on initial map load.
Tested with: https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/05-zoom-layer.json
Also checked with all layers in: https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
And some on: https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
- - - …

fix(initialView): zoom to layer more consistent

---

packages/geoview-core/src/core/components/data-table/data-table-modal.tsx
packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx

Closes #2300
Closes #2271
Get all features is only triggered once the button is clicked in the layers panel
Tested mainly with outlier-GeoAI.html, and several others.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2326)

fix(performance): no prefetch for layers table

---

.vscode/settings.json
common/config/rush/pnpm-lock.yaml
packages/geoview-aoi-panel/README.md
packages/geoview-aoi-panel/default-config-area-of-interest.json
packages/geoview-aoi-panel/package.json
packages/geoview-aoi-panel/schema.json
packages/geoview-aoi-panel/src/aoi-panel.tsx
packages/geoview-aoi-panel/src/area-of-interest-style.ts
packages/geoview-aoi-panel/src/index.tsx
packages/geoview-aoi-panel/tsconfig.json
packages/geoview-core/public/configs/loading-packages-config.json
packages/geoview-core/public/configs/navigator/26-package-area-of-interest.json
packages/geoview-core/public/templates/demos-navigator.html
packages/geoview-core/public/templates/events.html
packages/geoview-core/public/templates/loading-packages.html
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/core/components/app-bar/app-bar.tsx
packages/geoview-core/src/ui/icons/index.ts
packages/geoview-core/webpack.common.js
rush.json

Created the Area of interest package. The first version display the AOI icon in the app bar but the panel used is Data-Table Panel.
Fixes # (2321)
With a local host I was loading the AOI page and making sure the icon was in the side panel and the page title was Area of interest. I still have a little problem, when I over above the AOI icon it says "aoiPanel.title". 
URL deploy : https://guichoquette.github.io/geoview/area-of-interest.html
- - - …

2321-draft version aoi

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/core/components/data-table/data-table.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts

Closes #2215
ESRI Dynamic layers will now fetch there geometries when the zoom is clicked in the data table
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)

fix(datatable): ESRI Dynamic zoom in data table fixed

---

packages/geoview-core/src/core/components/common/responsive-grid-layout-style.ts
packages/geoview-core/src/core/components/layers/layers-toolbar.tsx

Fix the centering of the icons on mobile view for layers and responsive grid.
Fixes #2330 
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/12-package-geochart.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2350)

fix(common): centered the common icons on mobile view

---

.github/workflows/type-build.yml
packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/gv-layers/tile/gv-xyz-tiles.ts
packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector-tile.ts
packages/geoview-core/src/geo/utils/utilities.ts

Closes #2324
Added a utility extent validation function. Also updated all layers so that extent and bounds in initial settings config remains in lat/long.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/14-wms-layer.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2346)

fix(extent): Extent validation

---

packages/geoview-basemap-panel/default-config-basemap-panel.json
packages/geoview-basemap-panel/schema.json
packages/geoview-basemap-panel/src/basemap-panel-style.ts
packages/geoview-basemap-panel/src/basemap-panel.tsx
packages/geoview-basemap-panel/src/index.tsx
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/schema.json
packages/geoview-core/src/api/config/types/config-constants.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/geo/layer/basemap/basemap.ts

Closes #1849
Added a satellite image basemap to basemap options and included it in the default basemap panel.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/08-package-basemap.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2368)

feat(basemap): satellite basemap added

---

.github/workflows/type-build.yml
packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts
packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
packages/geoview-core/src/core/stores/state-api.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-core/src/ui/button/button.tsx
packages/geoview-core/src/ui/tabs/tabs.tsx
packages/geoview-time-slider/src/time-slider.tsx

Closes #2369
Removes (hides) tabs for time slider and geochart from footer-bar if there are no layers that support them. Also adds name and email to type action to stabilize it, and span tags to buttons to avoid errors when they are disabled.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/12-package-geochart.json
- - - …

feat(plugins): Hides plugin tabs if no layers support them

---

packages/geoview-core/public/configs/navigator/12-a-package-swiper.json
packages/geoview-core/public/templates/layers/esri-dynamic.html
packages/geoview-core/public/templates/layers/geocore.html
packages/geoview-core/schema.json
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2370
If an empty array is passed to the layerIds in initialSettings, will default to using all layers.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/12-a-package-swiper.json
https://damonu2.github.io/geoview/esri-dynamic.html
https://damonu2.github.io/geoview/geocore.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2386)

feat(initialView): empty layerIds array defaults to all layers

---

packages/geoview-aoi-panel/src/aoi-panel.tsx

I added to extent to Area of Interest as asked. Now when you click on a Area of Interest in the side panel, you should see a square around that AOI.
Fixes # (2412)
I ran a rush serve and made sure both my AOI present in the side panel in the demo package worked properly.
[__URL for your deploy!__](https://guichoquette.github.io/geoview/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2418)

2412 add extent to aoi

---

packages/geoview-core/public/configs/navigator/06-basic-footer.json
packages/geoview-core/schema.json
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/config-constants.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/core/containers/shell.tsx
packages/geoview-core/src/geo/map/map-schema-types.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2379
Closes #2423 
Added a global settings section of the config, with only one setting currently, canRemoveSublayers per request from OSDP. If set to false, sublayers will not be removable without removing the full layer. Also added a way to maintain map container div height when reloading, to avoid the div collapsing and resizing.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json - canRemoveSublayers is false for this map.
Can resize maps on https://damonu2.github.io/geoview/sandbox.html and call cgpv.api.maps.sandboxMap.reloadWithCurrentState() to check resizing issue.
-  ~~New and …

feat(settings): added canRemoveSublayers global setting

---

packages/geoview-core/src/core/containers/shell.tsx
packages/geoview-core/src/geo/map/map-viewer.ts

Fixes issue with resizing of map in rare cases. Reverts fix to keep map div size when reloading map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2436)

fix(size):remove hard code map height

---

packages/geoview-core/public/templates/config-sandbox.html
packages/geoview-core/src/api/config/config-api.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts

This issue covers two aspects of the layer tree implementation;
1- Improved tree generation for the WMS type on the Geomet site;
2- Temporary tree implementation for GeoView layers not yet coded.
Fixes #2471
Using Chrome Devtools and https://ychoquet.github.io/GeoView/config-sandbox.html template
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2473)

2471-Comple_layer_tree_coverage

---

packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Also fixes sublayer entry configs not being deleted when parent was removed
Also fixes sublayer entry configs not being deleted when parent was removed. Slight discrepancy with zoom to layer ids remain, as the extent is converted to lat/lon and then back.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/05-zoom-layer.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2504)

fix(home): home button works for extent and ids

---

packages/geoview-core/src/core/components/app-bar/buttons/version.tsx
packages/geoview-core/src/core/components/common/focus-trap-container.tsx
packages/geoview-core/src/core/components/data-table/data-table-modal.tsx
packages/geoview-core/src/core/components/details/feature-detail-modal.tsx
packages/geoview-core/src/core/components/export/export-modal.tsx
packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
packages/geoview-core/src/core/components/notifications/notifications-style.ts
packages/geoview-core/src/core/components/notifications/notifications.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts
packages/geoview-core/src/ui/tabs/tabs-style.ts

Implement focus trap and close icon for notification and version popover so that user can ability to close it.
Fix the exit button of tab panel when access through keyboard.
Fixes #2522 
Fixes #2523
- - - …

fix(notification): implement close icon for notificaiton and version 

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/public/configs/navigator/27-geocore-custom.json
packages/geoview-core/public/templates/demos-navigator.html
packages/geoview-core/public/templates/demos/demo-osdp-water.html
packages/geoview-core/schema.json
packages/geoview-core/src/api/config/uuid-config-reader.ts
packages/geoview-core/src/api/plugin/plugin.ts
packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
packages/geoview-core/src/core/utils/config/config-validation.ts
packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
packages/geoview-core/src/core/utils/utilities.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts
packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
packages/geoview-geochart/src/index.tsx

- Add the ability to extract layers config from Geocore
- Fix the issue with the details panel not opening on feature click because of panel index added to id. At the same time fix the script loading issue for packages when index is not in the id
- Fix for the third time the regex for date filter. Kept the old version in comment and kept the todo to standardize that section of code
Fixes #2259, #2531
Hosted, October 3rd, 7:30AM
https://jolevesq.github.io/geoview/add-layers.html
- Add …

2259 osdp geocore

---

packages/geoview-core/public/datasets/geojson/metadata.meta
packages/geoview-core/public/templates/layers/geojson.html
packages/geoview-core/public/templates/layers/layerlib.js
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/geojson-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/geojson-group-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wfs-group-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wms-group-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/wms-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/geojson-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts

QA done on hte add layer and the config API revealed some issues. This PR proposes corrections to be applied to the code.
Using the add-layer.html template.
__Deploy URL__: https://ychoquet.github.io/GeoView
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2530)

2529-More corrections for add layer and the config API

---

packages/geoview-core/public/templates/demos/demo-function-event.html
packages/geoview-core/src/app.tsx
packages/geoview-core/src/core/types/global-types.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts
packages/geoview-core/src/geo/map/map-viewer.ts

- Introduction of 4 distinct callback registrators for cgpv to better distinguish when it's possible to start listening to events.
- cgpv.onMapInit()
- cgpv.onMapReady()
- cgpv.onLayersProcessed()
- cgpv.onLayersLoaded()
- Minor ESLint fixes elsewhere
Fixes #2380 #2516 - Init synchronization issues
Hosted here as Oct. 11th @ 14h30: https://alex-nrcan.github.io/geoview/demo-function-event.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2546)

feat(cgpv) - Introduction of 4 distinct callbacks for cgpv.

---

packages/geoview-core/public/locales/en/guide.md
packages/geoview-core/public/locales/en/translation.json
packages/geoview-core/public/locales/fr/guide.md
packages/geoview-core/public/locales/fr/translation.json
packages/geoview-core/src/core/components/data-table/data-table-style.ts
packages/geoview-core/src/core/components/data-table/data-table.tsx
packages/geoview-core/src/core/components/data-table/export-button.tsx
packages/geoview-core/src/core/components/data-table/filter-map.tsx
packages/geoview-core/src/core/components/data-table/hooks/useToolbarActionMessage.tsx
packages/geoview-core/src/core/components/data-table/json-export-button.tsx
packages/geoview-core/src/core/components/details/feature-info-new.tsx
packages/geoview-core/src/core/containers/containers-style.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts
packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts
packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
packages/geoview-core/src/ui/icons/index.ts

This PR is fixing issues and add UX improvement (comments from the workshop about the data table)
- Rename export to download
- Remove Icon, Zoom, and Details columns from downloaded file
- Download only selected rows (CSV and JSON) - Add geoviewID as internal to do filtering
- Put layer name as file name for JSON and csv
- Filter open by default
- Filter map open by default
- Add clear all filters button
- Make filter map more visible
- Re arrange display, show number of features on right panel all the time
- More visible scroll bar
Fixes #2506, #2414
Please describe the tests that you ran to verify your changes. …

fix(table): UX and filter export

---

packages/geoview-core/src/core/components/common/use-lightbox.tsx
packages/geoview-core/src/core/components/data-table/data-table.tsx
packages/geoview-core/src/core/components/details/feature-info-table.tsx
packages/geoview-core/src/core/components/legend/legend-layer.tsx
packages/geoview-core/src/core/components/lightbox/lightbox.tsx
packages/geoview-core/src/ui/style/vendor.css

- Fix lightbox not showing on full screen
- Make buttons bigger on lightbox component
- Focus trap when lightbox is enable (focus mode on)
- Focus back to origin image for legend, data table and details
Fixes #2525, #1113
Hosted, October 15 - 1pm
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/14-wms-layer.json
- Tab to map, enable focus  trap
- Tab to legend tab and go inside
- Tab to a WMS legend image and press space or enter to enter lightbox
- Tab to see focus trap, close …

fix(lightbox): WCAG and fullscreen fail

---

packages/geoview-core/public/templates/outliers/outlier-metadata.html
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/abstract-geoview-raster.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/abstract-gv-raster.ts

- Fixed an issue where the layer extent highlighted on the map was actually the layer extent of the whole service, not the extent of the layer service itself.
- Added example in outlier metadata demo page demonstrating how some services have metadata extent not covering the entire records. What seems to be a metadata problem, more than an application issue.
Fixes #2515
Hosted as Oct 18th @ 13h: https://alex-nrcan.github.io/geoview/demo-osdp-water.html and https://alex-nrcan.github.io/geoview/outlier-metadata.html
- - - …

fix(layer-extent) - Fixes an issue with layer extent vs service extent for esri dynamic and esri image layers

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/src/geo/layer/layer.ts

Fixing the layer visiblity parenting
Fixes #2532
Hosted Nov 21 @ 14h15: https://alex-nrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2613)

fix(layers-visibility) Fixing the layer visiblity parenting

---

packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/layer.ts

Fixes an issue with the LayerApi layerLoaded event not being triggered correctly when in hybrid mode.
Hosted Dec 5th @ 11h: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2634)

fix(layerLoaded) - Hotfix for the LayerApi.layerLoaded event

---

packages/geoview-core/schema.json
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/config/types/config-validation-schema.json
packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2632
Config validation was assuming values for zoomAndCenter in config, this is no longer assumed. Also removed mapId value from createMapConfigFromMapState to better line up with what is expected in reload.
https://damonu2.github.io/geoview/sandbox.html
With:
{
"mapId": "mapWM",
"map": {
"basemapOptions": {
"basemapId": "transport",
"shaded": true,
"labeled": true
},
"interaction": "dynamic",
"listOfGeoviewLayerConfig": [],
"highlightColor": "black",
"overlayObjects": { "pointMarkers": {} },
"viewSettings": {
"initialView": { "extent": [ -63.17068832713632, 47.54397873973516, -47.11323060823711, 48.06148308033754 ] },
"enableRotation": true,
"rotation": 0,
"minZoom": 0,
"maxZoom": 50,
"maxExtent": [ -135, 25, -50, 89 ],
"projection": 3978
}
},
"theme": "[GEO.ca Language Selection …

fix(config): fixed bug with config validation

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/layer.ts

Fixes an issue with the layer highlighting function.
Fixes #2636
Hosted Dec 6 @ 10h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2638)

fix(layer-highlight) Hotfix for the layer highlighting

---

packages/geoview-core/src/core/components/details/details-style.ts
packages/geoview-core/src/core/components/details/feature-info-table.tsx
packages/geoview-core/src/core/utils/date-mgt.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/layer.ts

Closes #2593
Closes #2210
Closes #563
Fixes some issues with getting the feature info for some geocore layers. Adds support for html response from WMS getFeatureInfo.
HTML WMS: 6433173f-bca8-44e6-be8e-3e8a19d3c299
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)

fix(feature info): repairs feature info for geocore layers

---

packages/geoview-core/src/core/components/common/focus-trap-container.tsx
packages/geoview-core/src/core/components/common/full-screen-dialog.tsx
packages/geoview-core/src/core/components/common/layer-icon.tsx
packages/geoview-core/src/core/components/common/layer-list.tsx
packages/geoview-core/src/core/components/common/layout.tsx
packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx
packages/geoview-core/src/core/components/common/responsive-grid.tsx
packages/geoview-core/src/core/components/common/use-footer-panel-height.tsx
packages/geoview-core/src/core/components/common/use-lightbox.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/core/utils/useWhatChanged.ts

Fixes #2630
https://jolevesq.github.io/geoview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2637)

refactor(ui): Clean and improve performance

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/core/components/data-table/data-table.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/core/utils/constant.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts

Closes #2592
Fixes issues with ESRI Dynamic zoom to feature in the data table.
274ede77-27b9-46b8-96c8-4d7d4a706f08 - fixed
22abff18-6f9d-4926-b7de-3a80c178bf95 - fixed
21b821cf-0f1c-40ee-8925-eab12d357668 - no geometry returned - doesn't work in RAMP
039fbd92-43c2-4805-b210-d65703712e37 - no geometry returned - doesn't work in RAMP
622a7f72-4a00-4f9e-b04f-af6551c77db3 - fixed
1c61d457-4d03-4f3a-9005-9aabb5a201bb - no layers returned from geocore
5c670585-97ed-4e6a-a607-30fab940ff88 - no geometry returned - doesn't work in RAMP
2163f792-d105-4e80-8150-08b49fab20c0 - fixed
cfab1711-3566-4481-aebf-292ef56b216a - fixed
6ab784be-1197-4820-8bc2-fd20da32632c - wms layer, no data table
87b08750-4180-4d31-9414-a9470eba9b42 - fixed
-  ~~I have made …

fix(dynamic layers): fixed zoom issues in data table

---

packages/geoview-core/public/configs/navigator/28-geocore.json
packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/app-start.tsx
packages/geoview-core/src/core/components/crosshair/crosshair.tsx
packages/geoview-core/src/core/components/details/details-panel.tsx
packages/geoview-core/src/core/components/details/details-skeleton.tsx
packages/geoview-core/src/core/components/details/feature-info-new.tsx
packages/geoview-core/src/core/components/details/feature-info-table.tsx
packages/geoview-core/src/core/components/details/feature-info.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
packages/geoview-core/src/core/utils/constant.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2639 
- Remove a double query on each click
- Remove unessacary render of all features in  a query. Only render the visible one
Fixes #2639
Compare with https://canadian-geospatial-platform.github.io/geoview/public/outlier-elections-2019.html and https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/28-geocore.json
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/28-geocore.json …

refactor(details): Improve performance

---

packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-core/src/geo/utils/projection.ts
packages/geoview-core/src/ui/button-drop-down/button-drop-down-style.ts

- Improves support for layer projections once more.
- Improves extent densification, to make sure the generated extent bbox adequately follows the curvature of the earth.
Fixes (partially? can't test well today, GeoCore service not working well) #2591
Hosted Dec 13rd @ 13h30 : https://alex-nrcan.github.io/geoview/add-layers.html
NEED TO LOOK AT ISSUE, some uuid not working anymore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2659)

feature(layer-proj) - Better layer projection and extent densification support

---

packages/geoview-core/src/geo/utils/projection.ts

Added support for the CRS:84 projection and better distinction between 4326 and CRS:84.
Fixes #2591
Hosted Dec 18th @ 12h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2667)

fix(layer-projection) Added support for the CRS:84 projection

---

packages/geoview-core/public/configs/navigator/16-esri-dynamic.json
packages/geoview-core/public/configs/navigator/17-esri-feature.json
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/renderer/esri-renderer.ts

Closes #2597
Fixes issues with ESRI Dynamic layer styles. Default is now respected for class break styles, multiple entries for the same style are properly combined, and default values are better handled in class breaks.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
3af377be-801d-4ebf-9137-869b3080bfa5
88c1689b-9327-406e-860b-3d0e2dd518fa
3fffdd62-41e7-443c-b607-8d5825e12600
f38ca22a-2a3f-4e8a-86b5-e74f599e5cb6
000183ed-8864-42f0-ae43-c4313a860720 (Metal mines (ID: 4))
-  ~~New and existing unit tests pass locally with my …

fix(style): ESRI Dynamic handles multiple styles with same label

---

packages/geoview-core/public/configs/navigator/28-geocore.json
packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/core/components/legend/legend-layer-container.tsx
packages/geoview-core/src/core/components/legend/legend-layer-ctrl.tsx
packages/geoview-core/src/core/components/legend/legend-layer-items.tsx
packages/geoview-core/src/core/components/legend/legend-layer.tsx
packages/geoview-core/src/core/components/legend/legend-styles.ts
packages/geoview-core/src/core/components/legend/legend.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts

Closes #2660
- Fix missing icon for WMS
- Fix wrong order on load for legend tab
- Simplification for component
- Memo to reduce renderer
TODO in anther PR
- Throttle the store to minimize re render
- Refactor the tab footer to remove render when tab is not selected.
Hosted Dec 19th 4pm:
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/19-geojson.json
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/28-geocore.json
-  ~~I have made …

refactor(legend): Simplify the code and tweak performance

---

packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts
packages/geoview-core/src/geo/utils/projection.ts
packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts

Closes #2598
Fixes issue with raster layers not loading in ESRI Dynamic geocore layers.
06be2cfe-d334-4f92-94ae-62a7615e9d28 -fixed
5095a5e0-e574-4769-84d3-acaac529399b - fixed
37b59b8b-1c1c-4869-802f-c09571cc984b - fixed
3d52693e-39d1-4e7f-b4fa-b72ccb605006 - fixed
42478434-e0ac-4f40-a4ac-aec40f161a9c - fixed
c094782e-0d6f-4cc0-b5a3-58908493a433 - fixed
ac2096a6-7b4a-464e-9e08-eca7873dd88c - fixed
47a60179-83aa-4750-ad59-5797da909748 - all layers load, layers 0 and 17 are in RCS but don't exist, and two layers have no legend (15 and 16) - does not load at all in RAMP
6c7e9bb6-17e1-4e41-b49c-23261c8eefbc - fixed
bd71df53-543d-4359-9d17-8f1bb3b5ab90 - fixed
-  ~~I have added …

fix(ESRI Dynamic): raster layers in ESRI Dynamic geocore layers now load

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/public/configs/navigator/16-esri-dynamic.json
packages/geoview-core/public/templates/config-sandbox.html
packages/geoview-core/public/templates/demos/demo-osdp-integration.html
packages/geoview-core/public/templates/demos/demos.html
packages/geoview-core/src/app.tsx
packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts

Closes #2675
Closes #2676
Also fixes rendering issue with multiple style types
Adds a page to mimic OSDP geoview implementation in order to replicate their issues.
Also fixes a bug where icons from a layer with multiple style types would fail to render.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json - for rendering bug, issue was with 2020 combined sewer icons in data table and details
- - - …

feat(demo): new page for OSDP integration

---

packages/geoview-core/public/templates/default-config.html
packages/geoview-core/public/templates/sandbox.html

Fixes errors on sandbox.html and default-config.html with how apostrophes are handled by in the config.
https://damonu2.github.io/geoview/sandbox.html
https://damonu2.github.io/geoview/default-config.html?p=3857&z=4&c=-100,40&l=en&t=dark&b=basemapId:transport,shaded:false,labeled:true&i=dynamic&cc=overview-map&keys=12acd145-626a-49eb-b850-0a59c9bc7506,ccc75c12-5acc-4a6a-959f-ef6f621147b9#HLCONF7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/268 …

fix(config): single quote issue

---

packages/geoview-core/public/templates/demos/demo-osdp-integration.html
packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts

Closes #2653
Replaces some values in CSV headers that break the filter strings. Also updates demo-osdp-integration.html documentation.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/23-csv.json
Problems were in NPRI layer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2693)

fix(csv): fixes issues with characters in csv headers breaking filter

---

common/config/rush/pnpm-lock.yaml
packages/geoview-core/public/templates/demos/demo-function-event.html
packages/geoview-core/public/templates/demos/demo-osdp-integration.html
packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/ogc-wms-layer-entry-config.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-image-static.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/projection.ts
packages/geoview-core/src/geo/utils/renderer/esri-renderer.ts

- Fixing bug with 'Private property not on object' which was causing many issues including one when removing a layer such as (9d96e8c9-22fe-4ad2-b5e8-94a6991b744b)
- Fixing an issue where, when removing layers, the layer configs would be removed from layer registration, but not the actual layer objects
- Added support for EPSG:42101 projection
- Better support of metadata urls for WMS services where GetCapabilities is in the URL already or not
Fixes #2643 #2645
Possibly fixes #2594 and #2647 and #2602 as well, as those issues seem to be working on host now
Fixes #2605
Hosted: Jan 16 @ 13h00 : https://alex-nrcan.github.io/geoview/
-  ~~New and …

fix(layers) Fixes a 'private property not on object', fixing a layer issue, and added another proj fixing another issue

---

packages/geoview-core/src/core/components/common/layer-icon.tsx
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/utils/projection.ts
packages/geoview-core/src/geo/utils/utilities.ts

Also fixes issues with legend not loading
Closes #2689
Fixes issues with invalid extent from the metadata causing issues. Also checks for legend icons and bounds once layer is loaded.
5a65ad7c-561a-466a-8375-8d876624df9d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2700)

fix(geocore): fixed errors with sublayers showing as loading endlessly

---

packages/geoview-core/public/configs/navigator/10-package-time-slider.json
packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/ogc-wms-layer-entry-config.ts
packages/geoview-core/src/core/utils/constant.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts

Closes #2625
Closes #2648
Closes #2671
Adds proxy URL to WMS layers to avoid CORS issues. Also has a fix for layer style not being set in layer.
For WMS proxy:
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/14-wms-layer.json
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
eaf92ab8-c744-4f8f-a280-6987d4f6005e
6b1408b4-ea09-4a6a-b5dd-3db3493e1218
5a316fdc-3237-4ace-831e-67b4ca26a248
9eb51c7b-5336-4b50-a9f8-a6791bad15a9
01e01816-9f08-49eb-a5ac-7480195d90d4
41d008f7-f083-4801-b7c0-c2bf5a83a757
77f5bbd2-4f24-466f-b309-5b73659d32a3
13564ca4-e330-40a5-9521-bfb1be767147
02c992bb-9692-4bff-9517-7a92b09676c7
For layer style: …

fix(WMS): adds proxy to WMS urls

---

packages/geoview-core/public/css/style.css
packages/geoview-core/public/templates/demos/demo-esri-renderer.html
packages/geoview-core/public/templates/demos/demo-osdp-integration.html
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Closes #2724
Added a function to find and replace layer names throughout a map config.
10:20(eastern) on Feb. 4
Use new button or in console:
const stateConfig = cgpv.api.maps.Map1.createMapConfigFromMapState();
const pairs = [["Radioactivité de l'air", 'radioactivity'], ['Périmètre de localisation des stations', 'perimeter'], ['Carte commémorative du Canada', 'commem']]
cgpv.api.maps.Map1.replaceMapConfigLayerNames(pairs, stateConfig)
cgpv.api.maps.Map1.reload(stateConfig)
- - - …

feat(names): function added to replace layer names

---

packages/geoview-core/src/core/components/data-table/data-table.tsx
packages/geoview-core/src/core/components/details/feature-detail-modal.tsx
packages/geoview-core/src/core/components/details/feature-info.tsx
packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
packages/geoview-core/src/geo/map/feature-highlight.ts
packages/geoview-core/src/geo/map/map-schema-types.ts

Closes #2719
featureIcon changed to string from HTML canvas element. Now changed to a data URL before assignment. Feature highlight for points now uses a set value for the size of the highlight circle.
https://damonu2.github.io/geoview/outlier-ESRI-maxRecordCount.html Feb. 6 at 2:20 Eastern
Best way to see the speed increase in the data table is to load both tables and then switch between them - no query, you just see how long to render. Tried the same for loading the map - keeping layer info in cache and reloading.
- - - …

feat(performance): changed featureIcon to data URL at creation

---

packages/geoview-core/public/templates/demos/demo-osdp-integration.html
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts

Closes #2480
Updates ESRI Dynamic layers to use the service spatial reference instead of the map one, also adds a field to show the current map language in the OSDP integration page.
Hosted Feb. 11 12:30
https://damonu2.github.io/geoview/outlier-performance.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2744)

feat(ESRI Dynamic): use service projection for imageLayerOptions source

---

packages/geoview-core/public/templates/demos/demo-osdp-integration.html
packages/geoview-core/src/geo/layer/other/geocore.ts

Closes #2484
Issue is actually unrelated. This fixes the issue mentioned in the last comment with handling of simplified geocore configs. I think that this handles the configs in the way OSDP is requesting, but who knows.
Hosted Feb. 12, 10:25PM
UUID: b177a8c-5d7d-49eb-8290-31e6a45d786c
config: [{"layerName":"Critical Habitat for Aquatic Species at Risk - Canada"}]
Also tested with existing custom configs and with reducing them to just a layerName
- - - …

feat(OSDP): updates handling of simplified geocore config

---

packages/geoview-core/src/core/containers/containers-style.ts
packages/geoview-core/src/core/containers/shell.tsx
packages/geoview-core/src/core/containers/use-map-resize.ts

Adjust map/footer heights to use percentage values instead of pixel values in fullscreen so that the footer and map containers are correctly sized regardless of browser zoom level
Fixes #2633 
Go to demo page. Zoom browser out to 80% and fullscreen the viewer. There should be no empty space beneath the footer.
https://jaredkinger.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial- …

fix (shell/footer/ui) Wrong footer height in fullscreen

---

packages/geoview-core/src/core/containers/use-map-resize.ts

Quick fix to resolve the viewer height issue in localhost
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2749)

Fix viewer height in localhost

---

packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/ogc-wms-layer-entry-config.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts

Closes #2733
Also fixes one of the layers mentioned in #2746
Added encodeURI to the layerDefs in identify URL to allow them to work with older versions of ArcGIS Server. Also adds some services at maps-cartes.ec.gc.ca/arcgis/services/ to the proxy exemption.
Feb. 13 at 5:15
Add: https://nronk1awvasp039.nrn.nrcan.gc.ca:6443/arcgis/rest/services/GeoAnalytics/earthquakes/MapServer/ layers 1 and/or 2
Click point on map. No return (service issue) but query is successful.
- - - …

fix(encoding): encode layerDefs in ESRI Dynamic identify

---

packages/geoview-core/public/configs/many-groups.json
packages/geoview-core/public/templates/outliers/outlier-many-groups.html
packages/geoview-core/public/templates/outliers/outliers.html
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/esri-dynamic-layer-entry-config.ts
packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/esri-feature-layer-entry-config.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
packages/geoview-core/src/geo/utils/projection.ts

Closes #2642
Closes #2791
Fixes issue with cloning parentLayerConfig and geoviewLayerConfig causing massive slowdown with many group layers. Also adds lookup for unsupported projections.
44ef4d33-20b7-45fc-974c-d73a0a8fbae8
For the projections, deleted some definitions and loaded the layers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2797)

bug(clone): removes deep clone of config

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts

Closes #2798
Removes set styles from vector features so they can be dynamically updated
Hosted March 19, 12:55
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2800)

fix(style): removes set style from features

---

packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts

Replaces XMLHttpRequest with fetch, and checks url for .meta or json. Theoretically fixes the issue experienced by GSC Minerals Analytics Section
https://damonu2.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2802)

fix?(metadata): replace getXMLHttpRequest with fetch

---

packages/geoview-core/public/configs/navigator/05-zoom-layer.json
packages/geoview-core/public/configs/navigator/12-package-geochart-geochart.json
packages/geoview-core/public/templates/demos/demo-function-event.html
packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/geojson-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/wfs-config.ts
packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/components/app-bar/app-bar-api.ts
packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
packages/geoview-core/src/core/components/nav-bar/nav-bar-api.ts
packages/geoview-core/src/core/utils/config/config.ts
packages/geoview-core/src/core/utils/notifications.ts
packages/geoview-core/src/core/utils/utilities.ts
packages/geoview-core/src/geo/layer/geometry/geometry.ts
packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/layer/other/geocore.ts
packages/geoview-core/src/ui/accordion/accordion.tsx
packages/geoview-core/src/ui/modal/modal-api.ts
packages/geoview-core/src/ui/slider/slider.tsx

Also updates generateId function and removes double geoview layer ID in layer paths
Closes #2814
Closes #2828
Uses layer entry configs to remove layers instead of geoview layers so layers that have not been fully created are still removed. Also replaces naming the base group layer with the geoview layer ID with "base-group", and updates the generateId utility function to provide options.
https://damonu2.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geos …

fix(layer): remove all layers changed to remove unloaded layers

---

packages/geoview-core/src/core/components/details/details-panel.tsx
packages/geoview-geochart/src/geochart-panel.tsx

Fixes #2851 
Also, bonus, when clicking a layer with a chart associated on the map, the layer is selected immediately on the Chart panel (same behavior as Details panel).
Hosted April 29th @ 13h : https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2865)

(fix) Fixes the guide inner-panel which wasn't staying open for Details and Geochart

---

packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts

Fixes #2864
Before:
After:
Hosted April 29th 17h: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2866)

fix(legend-image-static) Fix for the legend icon for layers of type image-static

---

packages/geoview-core/public/configs/navigator/01-basemap-LCC-TLS.json
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/geo/map/map-viewer.ts
packages/geoview-core/src/geo/utils/utilities.ts

Closes #2881
Adds check for lng/lat extent to home view and initial view, and assumes it is map projection otherwise and does not alter it
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/01-basemap-LCC-TLS.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2888)

feat(initialView): allow for map projection extent initial/home view

---

packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts

Closes #2881
Quick fix for wrong extent being checked in homeView extent
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/01-basemap-LCC-TLS.json
- [] I have commented my code, particularly in hard-to-understand areas
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2894)

feat(initialView): allow for map projection extent in itial/home view

---

packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/vector-tile-config.ts
packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts

Closes #2912
Looking up projections throws an error, instead or returning undefined as it did when the addProjection function was added. Updated calling to calling it when the error is thrown.
Add: d29def12-36f2-4518-8758-896d9fb1f40d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2914)

fix(projection): fixes unsupported projection error

---

packages/geoview-core/src/api/config/types/map-schema-types.ts
packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
packages/geoview-core/src/core/components/common/layer-icon.tsx
packages/geoview-core/src/geo/layer/layer.ts
packages/geoview-core/src/geo/map/map-viewer.ts

Fixes when the legend isn't fully queried and the layer should still be showing the spinner on the icon
Hosted June 2nd @ 16h00: https://alex-nrcan.github.io/geoview/ **INVALID HOST RIGHT NOW**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2922)

fix(legend-spinner) Fixes when the legend isn't fully queried and the layer should still be showing the spinner on the icon
