- public/index.html
- src/common/basemap.ts
- src/common/map.ts
- src/components/map/map.tsx
- src/components/mapctrl/overview-map.tsx
closes #49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/63)
> feat(basemap) add the ability to load more than one basemap for each projection

- src/assests/style/north-arrow.tsx
- src/assests/style/theme.tsx
- src/components/map/map.tsx
- src/components/mapctrl/north-arrow.tsx
Closes #41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76)
> feat(north-arrow) Create a north arrow

- src/components/map/map.tsx
Closes #82
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/83)
> bug(fix-calling-apis) Fix calling api functions from child components

- package-lock.json
- package.json
- src/assests/style/north-arrow.tsx
- src/common/constant.ts
- src/common/projection.ts
- src/components/map/map.tsx
- src/components/mapctrl/north-arrow.tsx
Closes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/87)
> fix(north-arror) Apply rotation for LCC projection

- public/index.html
- public/templates/basemaps.html
Closes #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)
> feat(sample-pages) Create basemap page

- public/index.html
- public/templates/languages.html
- public/templates/projections.html
Closes #86
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/99)
> feat(#86) Sample Page projections and languages

- src/common/ui/button.ts
- src/components/appbar/app-bar.tsx
- src/components/appbar/button.tsx
- src/components/mapctrl/north-arrow.tsx
- src/components/panel/panel.tsx
> fix(appbar): fix wcag issues with app bar for focus on keyboard use

- package-lock.json
- public/index.html
- public/templates/add-panels.html
- src/assests/style/theme.tsx
- src/common/containers/html-to-react.tsx
- src/components/appbar/button.tsx
- src/components/navbar/button.tsx
- src/components/panel/panel.tsx
> feat(add-panel-sample) Create a sample page to showcase adding panels

- src/assests/style/theme.tsx
- src/components/mapctrl/north-arrow.tsx
> fix(north-arrrow): transition and keep in screen

- src/api/api.ts
- src/common/layers/layer.ts
- src/common/map-viewer.ts
- src/common/vectors/vector.ts
- src/components/map/map.tsx
> refactor(adding-layers) Find a better way to load layers

- .eslintrc
- common/docs/app/accessibility.md
- src/app.tsx
- src/assests/style/style.css
- src/assests/style/theme.tsx
- src/common/utilities.ts
- src/components/mapctrl/overview-map.tsx
- src/components/panel/panel.tsx
> fix(wcag): Control focus on keyboard and removed Overview map from cycle

- public/index.html
- public/templates/layers.html
- src/common/basemap.ts
- src/common/layers/esri-dynamic.ts
- src/common/layers/esri-feature.ts
- src/common/layers/geojson.ts
- src/common/layers/layer.ts
- src/common/layers/wms.ts
- src/common/map-viewer.ts
- src/components/map/map.tsx
> 89 sample pages layers

- public/css/style.css
- public/index.html
- public/templates/add-panels.html
- public/templates/basemap-switcher.html
- public/templates/basemaps.html
- public/templates/events.html
- public/templates/languages.html
- public/templates/layers.html
- public/templates/projections.html
- public/templates/responsive_page.html
- public/templates/responsive_page_map.html
- public/templates/usecases.html
> refactor sample-page moving style to css file

- src/common/basemap.ts
> fix(basemap-switcher) Fix switching basemaps

- public/index.html
- public/templates/vector.html
> feat-91-sample-page-vector closes #91

- package-lock.json
- package.json
- public/index.html
- public/templates/api-loads.html
- src/common/map-viewer.ts
- src/core/app-start.tsx
Closes #110
We can test the deploy because the api used is only http and GitHub only allows call from https.
The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and …
> feat(load): Add geometries from API call  set by URL parameter

- public/index.html
- public/templates/api-loads.html
> fix(api): Update service endpoint link for api load

- public/locales/en-CA/translation.json
- public/locales/fr-CA/translation.json
- src/api/event.ts
- src/assests/style/crosshair.tsx
- src/assests/style/style.css
- src/assests/style/theme.tsx
- src/assests/style/vendor.css
- src/common/utilities.ts
- src/components/map/map.tsx
- src/components/mapctrl/crosshair.tsx
- src/components/mapctrl/overview-map.tsx
Closes #117
To test, navigate to the map by tab. Once on the map a crosshair appears. Click enter to simulate double click (zoom)
The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues …
> feat(wcag): Add crosshair for keyboard interaction

- public/templates/add-panels.html
- public/templates/api-loads.html
- public/templates/basemap-switcher.html
- public/templates/basemaps.html
- public/templates/codedoc.js
- public/templates/events.html
- public/templates/languages.html
- public/templates/layers.html
- public/templates/projections.html
- public/templates/usecases.html
- public/templates/vector.html
- webpack.common.js
> feat(samples): Generate Code Snippet

- src/components/map/map.tsx
- src/components/mapctrl/overview-map.tsx
> fix(overview): Always use transportation basemap

- src/components/map/map.tsx
- src/components/mapctrl/overview-map.tsx
> fix(overview): bound disapears when toggle on multi map

- public/templates/usecases.html
- public/templates/vector.html
- src/common/vectors/vector.ts
- q
> feat(samples) clear-graphic

- public/css/style.css
- public/index.html
- public/templates/default-config.html
- public/templates/responsive_page.html
- src/api/config.ts
- src/common/basemap.ts
- src/common/layers/layer.ts
- src/common/map-viewer.ts
- src/common/utilities.ts
- src/components/layout/shell.tsx
- src/components/map/map.tsx
- src/core/app-start.tsx
> core(config): Add a config class to validate and apply default

- public/index.html
- public/plugins/details-panel/details-panel.js
- public/templates/details-panel.html
- src/api/event.ts
- src/assests/style/vendor.css
- src/common/layers/esri-dynamic.ts
- src/common/layers/esri-feature.ts
- src/common/layers/wms.ts
- src/common/ui/button-panel.ts
- src/common/ui/button.ts
- src/common/ui/panel.ts
- src/common/utilities.ts
- src/components/appbar/app-bar.tsx
- src/components/layout/focus-trap.tsx
- src/components/map/map.tsx
- src/components/mapctrl/crosshair.tsx
- src/components/navbar/nav-bar.tsx
- src/components/panel/panel.tsx
> feat(details-panel) Create a details panel to show feature,layers info

- src/common/layers/layer.ts
> feat(layer-by-id) Create a function to return a layer by it's id

- src/api/config.ts
- src/common/map-viewer.ts
- src/components/layout/shell.tsx
> feat(load-plugin-map-config) Load internal plugins from map config

- public/index.html
- public/templates/loading-plugins.html
- src/api/plugin.ts
> feat(loading-plugins-sample) A sample page to showcase loading plugins

- public/locales/en-CA/translation.json
- public/locales/fr-CA/translation.json
- public/templates/default-config.html
- public/templates/events.html
- src/common/layers/layer.ts
- src/components/mapctrl/snackbar.tsx
> fix(snack): Add translation to snackbar

- public/locales/en-CA/translation.json
- public/locales/fr-CA/translation.json
- public/templates/details-panel.html
- src/components/layout/focus-trap.tsx
- src/components/layout/shell.tsx
- src/components/mapctrl/crosshair.tsx
> fix(wcag): Fix the focus trap to add a real dialog box

- common/docs/app/plugins.md
- package-lock.json
- public/plugins/basemap/basemap-switcher.js
- public/templates/loading-plugins.html
- src/api/event.ts
- src/common/map-viewer.ts
- src/common/ui/button-panel.ts
- src/components/map/map.tsx
- src/components/mapctrl/click-marker.tsx
- src/components/panel/panel.tsx
- src/plugins/details-panel/layers-list.tsx
- src/plugins/details-panel/panel-content.tsx
> feat(marker-icon) Create a marker icon to show when a click event on map

- src/common/layers/layer.ts
> fix(layer): remove from tabindex

- src/assests/style/theme.tsx
- src/common/layers/layer.ts
- src/components/layout/focus-trap.tsx
- src/components/layout/shell.tsx
- src/types/material-ui.d.ts
> feat(splah): Add a loading screen

- src/components/appbar/app-bar.tsx
- src/components/navbar/button.tsx
- src/components/navbar/nav-bar.tsx
> fix(wcag) Navbar button and panel

- public/locales/en-CA/translation.json
- public/locales/fr-CA/translation.json
- src/components/appbar/app-bar.tsx
- src/components/layout/focus-trap.tsx
Closes #189, #190, #191, #192
--- …
> fix(WCAG): Fix WCAG issue with label, appbar and focus dialog

- public/templates/details-panel.html
- src/common/ui/button-panel.ts
- src/components/mapctrl/crosshair.tsx
- src/components/panel/panel.tsx
- src/plugins/details-panel/feature-info.tsx
- src/plugins/details-panel/features-list.tsx
- src/plugins/details-panel/index.tsx
- src/plugins/details-panel/layers-list.tsx
- src/plugins/details-panel/panel-content.tsx
> fix(details): Fix WCAG issues with detials panel

- package-lock.json
- src/api/config.ts
- src/common/layers/layer.ts
- src/components/mapctrl/click-marker.tsx
> fix(extent): Fix bad initial extent and zoom to initial

- src/components/map/map.tsx
- src/components/mapctrl/crosshair.tsx
- src/components/mapctrl/mouse-position.tsx
> fix(WCAG): Add mouse  coordinates for keyboard user

- package-lock.json
- public/index.html
- public/templates/api-functions-test.html
- public/templates/codedoc.js
- src/api/api.ts
- src/api/utilities.ts
- src/common/layers/wms.ts
- src/plugins/details-panel/panel-content.tsx
> feat(api): Add get service metadata (ESRI and WMS)

- public/templates/default-config.html
- public/templates/languages.html
- public/templates/usecases.html
- src/common/map-viewer.ts
- src/components/layout/shell.tsx
- src/core/app-start.tsx
> fix(core): Maps doesn't load when we mix languages

- public/templates/load-test.html
- public/templates/marker-clusters.html
- public/templates/usecases.html
- public/templates/vector.html
- src/common/layers/vector.ts
* [?] Commit message follow the guidelines
* [NA] _Help files and documentation have been updated_
The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and …
> 234 - Fix vector class bugs

- packages/geoview-core/src/core/app-start.tsx
Closes #245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/246)
> fix(map-loading): Fixed loading map when additional classes is provided

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/plugin.ts
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/appbar/app-bar-buttons.ts
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar-buttons.ts
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/utils/config.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/panel/panel-api.ts
Closes #240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/267)
> refactor(map-instance): Refactored how we create the map instance

- common/config/rush/pnpm-lock.yaml
- packages/geoview-loader/public/templates/load-test.html
- packages/geoview-loader/public/templates/usecases.html
- packages/geoview-loader/public/templates/vector.html
Closes Canadian-Geospatial-Platform#265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/268)
> fix(broken-demo): Fixed broken demos related to geo refactoring

- .gitignore
- common/config/rush/command-line.json
- packages/geoview-loader/webpack.common.js
- rush.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/272)
> Some changes require for CI-CD, also updating gitignore file so that it won't add IntelliJ metadata files

- packages/geoview-core/src/geo/layer/ogc/wms.ts
Closes #280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/281)
> fix(wms-load): Fixed loading a single WMS Layer

- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/event.ts
- packages/geoview-core/src/api/plugin.ts
- packages/geoview-core/src/core/components/appbar/app-bar-buttons.ts
- packages/geoview-core/src/core/components/appbar/app-bar.tsx
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/crosshair/crosshair.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar-buttons.ts
- packages/geoview-core/src/core/components/navbar/nav-bar.tsx
- packages/geoview-core/src/core/components/overview-map/overview-map.tsx
- packages/geoview-core/src/core/containers/focus-trap.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/layer/vector/marker-cluster.ts
- packages/geoview-core/src/geo/layer/vector/vector.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/drawer/drawer.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/snackbar/snackbar.tsx
- packages/geoview-details-panel/src/panel-content.tsx
- packages/geoview-loader/public/templates/loading-packages.html
- packages/geoview-loader/public/templates/marker-clusters.html
- packages/geoview-overview-map/src/index.tsx
- packages/geoview-overview-map/src/overview-map.tsx
Closes #222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/292)
> fix(plugin-loading): Fixed issues with plugin loading in multiple maps

- packages/geoview-core/src/api/event.ts
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/icons/index.ts
Closes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/298)
> refactor(global-state): Added remaining functions to access state

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/src/core/components/appbar/app-bar.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/navbar/buttons/fullscreen.tsx
- packages/geoview-core/src/core/components/navbar/buttons/home.tsx
- packages/geoview-core/src/core/components/navbar/buttons/zoom-in.tsx
- packages/geoview-core/src/core/components/navbar/buttons/zoom-out.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar.tsx
- packages/geoview-core/src/core/types/material-ui.d.ts
- packages/geoview-core/src/geo/utils/utilities.ts
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/style/theme.tsx
- packages/geoview-loader/.babelrc
Closes #297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/310)
> fix(material-ui-issues): Fixed material upgrade issues

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
Close #317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/318)
> fix(detailspanel):show wms popup symbol

- packages/geoview-core/src/app.tsx
Closes #324
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/328)
> #324 fix french layer name

- packages/geoview-core/schema-default-config.json
- packages/geoview-core/schema.json
- packages/geoview-geolocator/schema.json
- packages/geoview-layers-panel/schema.json
Closes #327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/329)
> core(schema): Update bilangual schema and add default config file

- packages/geoview-core/src/core/components/appbar/app-bar.tsx
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-details-panel/src/index.tsx
- packages/geoview-details-panel/src/panel-content.tsx
- packages/geoview-loader/public/templates/layers.html
- packages/geoview-loader/public/templates/loading-packages.html
- packages/geoview-loader/public/templates/marker-clusters.html
- packages/geoview-loader/public/templates/responsive_page.html
- packages/geoview-loader/public/templates/responsive_page_map.html
Closes #332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/334)
> #332 appbar modifications

- packages/geoview-core/src/ui/panel/panel.tsx
Closes #322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/338)
> feat(layer-opacity): fix panel flexDirection

- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/core/components/appbar/app-bar.tsx
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/navbar/buttons/fullscreen.tsx
- packages/geoview-core/src/core/components/navbar/buttons/home.tsx
- packages/geoview-core/src/core/components/navbar/buttons/zoom-in.tsx
- packages/geoview-core/src/core/components/navbar/buttons/zoom-out.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/button/button.tsx
- packages/geoview-core/src/ui/circular-progress/circular-progress.tsx
Closes #339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/340)
> #339 map issues

- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/utils/config.ts
Closes #342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/344)
> #342 add custom options

- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-layers-panel/src/layers-list.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/351)
> #349 layer remove

- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/geo/layer/esri/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/esri/esri-feature.ts
- packages/geoview-core/src/geo/layer/file/geojson.ts
- packages/geoview-core/src/geo/layer/map-tile/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/ogc/wfs.ts
- packages/geoview-core/src/geo/layer/ogc/wms.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-layers-panel/src/layers-list.tsx
Adds Layer Panel "Zoom to Layer" and "Toggle BBOX" controls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/373)
> #352 layers zoom

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/types/marker-definitions.ts
- packages/geoview-core/src/geo/layer/esri/esri-feature.ts
- packages/geoview-loader/public/templates/layers.html
Closes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/374)
> #314 esrifeature symbol

- packages/geoview-core/src/geo/layer/esri/esri-dynamic.ts
- packages/geoview-layers-panel/src/layers-list.tsx
For ESRI Dynamic layers, add option to hide sub-layers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/375)
> #365 layers sub hide

- packages/geoview-layers-panel/src/layer-stepper.tsx
Allow Custom renaming of Select Multiple Layers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/388)
> Allow Custom renaming of Select Multiple Layers

- packages/geoview-core/src/geo/layer/ogc/ogc_feature.ts
- packages/geoview-layers-panel/src/layer-stepper.tsx
Add support for OGC API Feature in layers panel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/392)
> Add support for OGC API Feature in layers panel

- packages/geoview-basemap-switcher/src/index.tsx
- packages/geoview-core/src/api/plugin.ts
- packages/geoview-core/src/core/types/abstract/abstract-plugin.ts
- packages/geoview-core/src/core/types/abstract/abstract-web-layers.ts
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-details-panel/src/index.tsx
- packages/geoview-details-panel/src/panel-content.tsx
Final work on code restructuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/395)
> 380 review types

- packages/geoview-core/common/docs/app/api.md
- packages/geoview-core/public/configs/my-config.json
- packages/geoview-core/public/templates/codedoc.js
- packages/geoview-core/public/templates/default-config.html
- packages/geoview-core/public/templates/events.html
- packages/geoview-core/public/templates/languages.html
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/public/templates/load-test.html
- packages/geoview-core/public/templates/loading-packages.html
- packages/geoview-core/public/templates/marker-clusters.html
- packages/geoview-core/public/templates/projections.html
- packages/geoview-core/public/templates/responsive_page_map.html
- packages/geoview-core/public/templates/usecases.html
- packages/geoview-core/public/templates/vector.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/api/event.ts
- packages/geoview-core/src/api/plugin.ts
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/utils/config.ts
- packages/geoview-core/src/geo/layer/web-layers/esri/esri-dynamic.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/button/button.tsx
- packages/geoview-core/webpack.common.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/400)
> #8 map config

- packages/geoview-overview-map/src/minimap-bounds.tsx
- packages/geoview-overview-map/src/minimap-toggle.tsx
- packages/geoview-overview-map/src/overview-map.tsx
Closes #407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/409)
> fix(minimap-crash): Bug with the minimap navigation and window size modification

- packages/geoview-core/src/api/plugin.ts
- packages/geoview-core/webpack.common.js
Closes #411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/412)
> fix(core-packages): Fix loading core packages on external apps

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/appbar/app-bar-buttons.ts
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar-buttons.ts
Closes #354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/415)
> fix(panel-issues): Fixed appbar stays after all panels removed

- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/utils/config.ts
- packages/geoview-core/src/core/utils/date-mgt.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/layer/other/geocore.ts
Closes #291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/418)
> feat(uuid-layer): Added ability to load a layer from uuid (geoCore)

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/ui/select/select.tsx
- packages/geoview-layers-panel/src/layer-stepper.tsx
Closes #423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/424)
> feat(list-grouping): Added list sub header to select ui

- packages/geoview-core/common/docs/Programming/Using TypeJson/README.md
- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/ui-components.html
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/events/constants/slider.ts
- packages/geoview-core/src/api/events/event.ts
- packages/geoview-core/src/api/events/payloads/slider-payload.ts
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/ui/slider/slider.tsx
Closes #304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)
> feat(ui): Add slider component

- packages/geoview-core/src/geo/layer/web-layers/esri/esri-feature.ts
The esri-feature layer does not display the legend icons. It uses a blue circle instead. The correction reads the name of the field that identifies the icon to be displayed according to the value stored in it and builds a table associating the values to the icons to be displayed. If the legend is misconfigured, the blue circle display will be used as a fall back solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/431)
> Fix esri-feature to allow symbols to be displayed using the legend icons.

- common/scripts/push-types.js
- packages/geoview-core/public/css/style.css
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/events/constants/attribution.ts
- packages/geoview-core/src/api/events/event.ts
- packages/geoview-core/src/api/events/payloads/attribution-payload.ts
- packages/geoview-core/src/api/events/payloads/slider-payload.ts
- packages/geoview-core/src/core/components/appbar/app-bar.tsx
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/footerbar/footer-bar.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
Closes #426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/432)
> 426 test resize

- packages/geoview-core/public/templates/custom-package-config.html
- packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx
- packages/geoview-core/src/geo/layer/basemap/basemap.ts
- packages/geoview-overview-map/src/overview-map.tsx
Closes #442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/444)
> fix(pane-duplicate): Fixed north-pane and basemap duplicate

- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/geo/map/map.ts
Closes 452
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/453)
> fix(language-switch): Fixed language switch function

- packages/geoview-basemap-panel/src/index.tsx
- packages/geoview-core/public/templates/add-panels.html
- packages/geoview-core/src/core/components/appbar/app-bar-buttons.ts
- packages/geoview-core/src/core/components/appbar/app-bar.tsx
- packages/geoview-core/src/core/components/navbar/nav-bar-buttons.ts
- packages/geoview-core/src/core/components/navbar/nav-bar.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/types/material-ui.d.ts
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/list/list-item.tsx
- packages/geoview-core/src/ui/style/theme.tsx
- packages/geoview-details-panel/src/index.tsx
- packages/geoview-layers-panel/src/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)
> feat(UI): Initial UI updates for the app bar

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/472)
> refactor(typedoc): Added typedoc URL to README

- packages/geoview-core/schemav2.json
Closes #492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/493)
> core(schema): Cleanup new schema based on OL

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/public/configs/footer-tabs-config.json
- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/footer-tabs.html
- packages/geoview-core/src/api/events/constants/footer-tabs.ts
- packages/geoview-core/src/api/events/event.ts
- packages/geoview-core/src/api/events/payloads/footer-tab-payload.ts
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs-api.ts
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/navbar/buttons/fullscreen.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/table/table.tsx
- packages/geoview-core/src/ui/tabs/index.ts
- packages/geoview-core/src/ui/tabs/tab-panel.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
Closes #495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/496)
> feat(footer-tabs): Added footer tabs component

- packages/geoview-basemap-panel/src/basemap-panel.tsx
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/types/material-ui.d.ts
- packages/geoview-core/src/ui/card/card.tsx
- packages/geoview-core/src/ui/card/index.ts
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/select/select.tsx
- packages/geoview-core/src/ui/style/theme.tsx
Closes #461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/486)
> feat(UI): Updates to the basemap panel's UI

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/508)
> Minor edits to fix typo's

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/main.yml
- rush.json
Closes #518
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/519)
> core(build): Add CICD to create gh-pages automatically

- .github/workflows/main.yml
Closes #507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/547)
> fix(workflow): Fix deploy gh-pages workflow

- packages/geoview-core/README.md
Closes #548
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/549)
> test(workflow): Test the deploy workflow

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/public/templates/test.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/abstract-geoview-raster.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/geo/projection/projection.ts
- packages/geoview-core/src/geo/renderer/esri-renderer.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
- packages/geoview-core/src/geo/utils/constant.ts
First version of ESRI dynamic + some refactoring in the classe hierarchy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/554)
> 553-ESRI-Dynamic-refactoring

- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
Closes #542
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/558)
> fix(components): Fix mouse position bad cardinality and cleanup

- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/public/templates/test.html
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/abstract-geoview-raster.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/560)
> 559-WMS-refactoring

- packages/geoview-core/public/templates/test.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/renderer/esri-renderer.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
Correction made to the renderer to use properly the default settings and the index
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/583)
> 582-GeoView-renderer-bug

- common/scripts/push-types.js
- docs/app/accessing-types.md
Closes #578
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/585)
> fix(build): Build types to be access from external package

- packages/geoview-core/public/geojson/metadata.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/basemaps.html
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/geo/layer/basemap/basemap.ts
Closes #541
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/579)
> fix(attribution): remove duplicate

- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
- rush.json
This correction will solve certain problems Chris has.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/598)
> 597-Bug with sub layers defined in metadata

- packages/geoview-core/public/index.html
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/legend.html
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/components/legend/legend-api.ts
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/core/types/global-types.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/avatar/avatar.tsx
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/list/collapse.tsx
- packages/geoview-core/src/ui/list/index.ts
- packages/geoview-core/src/ui/list/list-item-button.tsx
- packages/geoview-core/src/ui/list/list-item-icon.tsx
- packages/geoview-core/src/ui/list/list-item-text.tsx
Its still forcing legend into a footer tab, but I will look at changing that next
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/599)
> 534 core legend

- .github/workflows/deploy.yml
- packages/geoview-core/webpack.common.js
- packages/geoview-core/webpack.prod.js
Close #623
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/627)
> feat(build): Add version (geoview-core) and date to js file banner

- packages/geoview-basemap-panel/src/basemap-panel.tsx
- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/public/configs/package-footer2-config.json
- packages/geoview-core/public/templates/legend.html
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/ui/list/list-item.tsx
- packages/geoview-core/src/ui/stepper/stepper.tsx
- packages/geoview-core/src/ui/style/theme.tsx
Closes #610
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)
> feat(ui): Enable light/dark themes

- docs/README.md
- docs/app/components-packages.md
- docs/app/loading-maps.md
- docs/app/packages.md
Closes #545
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/632)
> doc(app): Add package vs component doc

- packages/geoview-core/public/css/style.css
- packages/geoview-core/public/index.html
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/ui/avatar/avatar.tsx
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/list/list-item.tsx
- packages/geoview-core/src/ui/style/theme.tsx
closes #556 
Needs a new epic to remove makeStyles from the rest of the components
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641)
> fix(ui): font updates and upgrade legend to MUIv5

- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map.ts
Closes #654
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/655)
> fix(event): Trigger the map loaded when all layers are loaded

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/menu/index.ts
- packages/geoview-core/src/ui/menu/menu-item.tsx
- packages/geoview-core/src/ui/menu/menu.tsx
- packages/geoview-layers-panel/src/layer-stepper.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
Closes #669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/670)
> feat(ui): remove legend option

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/ui/icon-button/icon-button.tsx
- packages/geoview-core/src/ui/style/theme.tsx
Closes #630
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/678)
> feat(ui): better legend icon previews

- packages/geoview-core/src/core/components/legend/legend.tsx
Closes #679
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/682)
> fix(ui):new layers added on top, keep config order

- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-layers-panel/src/layer-stepper.tsx
Closes #671
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/693)
> fix(ui): Stepper add multiple layers at a time

- README.md
- common/config/rush/pnpm-lock.yaml
- docs/app/components-packages.md
- packages/geoview-core/public/configs/package-swiper-config-swiper.json
- packages/geoview-core/public/configs/package-swiper-config.json
- packages/geoview-core/public/configs/package-swiper2-config-swiper.json
- packages/geoview-core/public/configs/package-swiper2-config.json
- packages/geoview-core/public/configs/package-swiper3-config-swiper.json
- packages/geoview-core/public/configs/package-swiper3-config.json
- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/package-swiper.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/webpack.common.js
- packages/geoview-footer-panel/src/index.tsx
- packages/geoview-swiper/README.md
- packages/geoview-swiper/default-config-swiper.json
- packages/geoview-swiper/package.json
- packages/geoview-swiper/schema.json
- packages/geoview-swiper/src/index.tsx
- packages/geoview-swiper/src/swiper.tsx
- packages/geoview-swiper/tsconfig.json
- rush.json
Closes #666
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)
> feat(swiper): Add first version of swiper core package

- .github/workflows/main.yml
- packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
- packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/ui/style/theme.tsx
- packages/geoview-core/src/ui/tooltip/tooltip.tsx
Closes #619, #616
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/700)
> feat(data-grid): Add a custom key field and set table style

- .github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/707)
> fix(action): Fix GitHub action

- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/public/templates/test.html
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/map/map.ts
- rush.json
To test, use the test.html and layers.html templates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/705)
> 702-Bug Geocore WMS uses a xml instead of a GetCapabilities

- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/ui/style/theme.tsx
Closes #662
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691)
> fix(ui): legend toggle parent update

- packages/geoview-core/public/index.html
Closes #711
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/712)
> fix(demo): redo gh-pages

- packages/geoview-core/src/geo/utils/utilities.ts
- packages/geoview-layers-panel/src/layer-stepper.tsx
Closes #696
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)
> fix(stepper): better WMS url parsing

- packages/geoview-core/src/api/events/payloads/geoview-layer-payload.ts
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-layers-panel/src/layer-stepper.tsx
Use https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/900A_and_top_100_en/MapServer/1 to test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/726)
> 717-Add esri dynamic group layer timing

- packages/geoview-core/public/templates/footer-tabs.html
- packages/geoview-core/public/templates/legend.html
- packages/geoview-core/src/core/components/legend/legend-api.ts
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-footer-panel/src/index.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
Closes: #728
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/729)
> refactor(api): create legend with layerId

- packages/geoview-core/public/templates/footer-tabs.html
- packages/geoview-core/public/templates/legend.html
- packages/geoview-core/public/templates/vector.html
- packages/geoview-core/src/core/components/legend/legend-api.ts
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/geo/layer/vector/vector.ts
- packages/geoview-footer-panel/src/index.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/731)
> 730-vector type delete bug

- packages/geoview-core/public/templates/test.html
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/733)
> 725 multi polygon type not supported

- .github/workflows/type-build.yml
Added my credentials to hopefully solve permission issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/739)
> fix(action): Credentials added

- .github/workflows/type-build.yml
Closes #740
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/742)
> fix(action): github_token permissions changed

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/legend/legend-api.ts
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/slider/slider-base.tsx
- packages/geoview-layers-panel/src/layer-stepper.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
Closes #732
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737)
> feat(layer-panel): add new layer panel actions

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/public/templates/test.html
- packages/geoview-core/src/core/components/legend/legend-api.ts
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/slider/slider-base.tsx
- packages/geoview-layers-panel/src/layer-stepper.tsx
- packages/geoview-layers-panel/src/layers-list.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/746)
> 745-Calculate vector layer bounds

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-core/src/ui/list/list-item.tsx
- packages/geoview-core/src/ui/list/list.tsx
- packages/geoview-layers-panel/package.json
- packages/geoview-layers-panel/src/panel-content.tsx
- packages/geoview-layers-panel/src/reorder-layers-list.tsx
Closes #677
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752)
> feat(layer-panel): reorder layers ui

- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/public/templates/test.html
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-footer-panel/src/details-item.tsx
- packages/geoview-footer-panel/src/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/758)
> 757 stack dump with get feature info outside the extent

- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/api-functions-test.html
- packages/geoview-core/public/templates/default-config.html
- packages/geoview-core/public/templates/layers-temporal.html
- packages/geoview-core/src/core/utils/date-mgt.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/748)
> feat(time): Create time dimension and associate to layer object

- packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
- packages/geoview-core/src/ui/tabs/tab-panel.tsx
- packages/geoview-footer-panel/src/index.tsx
- packages/geoview-footer-panel/src/legend-item.tsx
Closes #761 Closes #743
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)
> fix(footer-panel): remove hardcoded legend ids

- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/766)
> 672-XYZ_layers-visibility_and-remove_problems

- packages/geoview-core/src/api/events/event.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/769)
> 768-Once event bug

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/ui/tabs/tab-panel.tsx
- packages/geoview-footer-panel/src/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/767)
> 756 details expand

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
Closes #770
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/771)
> fix(layer): Fix WMS with no temporal dimension failed to load

- packages/geoview-core/public/templates/package-layers-panel.html
- packages/geoview-core/src/geo/utils/utilities.ts
- packages/geoview-layers-panel/src/layer-stepper.tsx
Closes #753
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/780)
> feat(layer-panel): Add single layer OGC url

- packages/geoview-core/src/core/components/details/layers-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/ui/list/collapse.tsx
- packages/geoview-core/src/ui/list/list-item-button.tsx
- packages/geoview-core/src/ui/list/list-item-icon.tsx
- packages/geoview-core/src/ui/list/list-item-text.tsx
- packages/geoview-core/src/ui/list/list-item.tsx
- packages/geoview-core/src/ui/list/list.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
Closes #749
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/779)
> refactor(ui): common themes in legend/details

- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx
Closes #738
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/781)
> feat(ui): clean up footer bar ui

- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
Closes #784
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/789)
> fix(cluster): Improve cluster visibility

- packages/geoview-core/src/api/events/constants/footer-tabs.ts
- packages/geoview-core/src/api/events/event-types.ts
- packages/geoview-core/src/api/events/payloads/footer-tab-payload.ts
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs-api.ts
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-footer-panel/src/index.tsx
Closes #786
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/791)
> feat(footer-panel): switch to detail tab on result

- packages/geoview-core/src/core/components/details/feature-info.tsx
- packages/geoview-core/src/core/components/details/layers-list.tsx
Closes #788
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/799)
> feat(details): automatic expand single elements

- packages/geoview-layers-panel/src/panel-content.tsx
Closes #754
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/800)
> fix(layers-panel): disable scroll on reorder layer

- packages/geoview-core/public/configs/package-footer3-config.json
- packages/geoview-core/public/templates/package-footer-panel.html
- packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
Closes #785 
Changes made to get feature details for clustered features.
Legend is working with clustering, data works if clustering is enabled for the first map, however the third map doesn't get data with clustering on or off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/814)
> feat(cluster): Cluster footer example

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/core/types/cgpv-types.ts
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/webpack.common.js
- packages/geoview-layers-panel/src/layer-stepper.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)
> 183 geopackage support

- .github/workflows/type-build.yml
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/app-bar/buttons/export.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/core/components/nav-bar/buttons/export.tsx
- packages/geoview-core/src/core/components/nav-bar/export-modal.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/ui/icons/index.ts
Closes #796
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/832)
> 796 export to navbar

- packages/geoview-core/public/geojson/metadata.json
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
This PR is related to issue 551 and 836. It covers only the geoview vector layers and does nor implement fields filtering.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/837)
> 836-Legend_filtering_for_geoview_vector_layers

- packages/geoview-core/src/core/components/details/feature-info.tsx
- packages/geoview-core/src/core/components/details/layers-list.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-footer-panel/schema.json
- packages/geoview-footer-panel/src/data-item.tsx
- packages/geoview-footer-panel/src/index.tsx
Fixes #811
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852)
> 811 overviewer in ft

- packages/geoview-core/public/geojson/lines.json
- packages/geoview-core/public/geojson/metadata.json
- packages/geoview-core/public/geojson/polygons.json
- packages/geoview-core/public/templates/codedoc.js
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer-types.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
Implementation of a legend filter and  the possibility to provide an extra clause for the layer to get a filter like
(legendFilter and layerFilter) Also provides the ability to specify a filter that do not activate the legendFilter and layerFilter clause.
Fixes
Legend filtering for geoview vector layers #836
Add field value filtering to geoview vector layers #838
Using the Layers template..
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/864)
> 535 add filtering vector source

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/ui/switch/switch.tsx
Update footer bar component to make wcag compatible.
Fixes # (848)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)
> update footer bar components

- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/ui/style/theme.tsx
Update the selected state of appbar button and hover.
Fixes # (860)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/873)
> fix app bar selected color and hover state

- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
Add transition effect to app bar panel
Fixes # (846)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/880)
> add transition effect to app bar

- packages/geoview-core/src/core/components/details/details-api.ts
- packages/geoview-core/src/core/components/details/details.tsx
- packages/geoview-core/src/core/components/details/feature-info.tsx
- packages/geoview-core/src/core/components/details/layers-list.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-details-panel/src/details-item.tsx
- packages/geoview-details-panel/src/index.tsx
- packages/geoview-footer-panel/src/details-item.tsx
Fixes #841
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
Go to Footer panel or details panel page, click on map, with the layers/feature found, would open the details panel/tab ans showing the details info, and the marker show be showing on the map 
- [ X ] I have connected the issues(s) to this PR
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] My changes generate no new warnings
-  ~~I …
> 841 show details on map clicking

- packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
- packages/geoview-core/src/core/components/details/details.tsx
- packages/geoview-core/src/core/components/details/feature-info.tsx
- packages/geoview-core/src/core/components/details/layers-list.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-details-panel/src/details-item.tsx
- packages/geoview-footer-panel/src/data-item.tsx
- packages/geoview-footer-panel/src/details-item.tsx
Fixes #851
Footer panel, data tab, the GeoJsonSample, new dropdown list if layers, change the layers, the data table of the selected layer showing up below
For the feature info only have featurekey, set the featureKey column showing (default hidden) 
Fix the issue of data grid column max
Also remove the timeout from the details component, set the marker timeout separately in details panel and footer panel details tab
-  ~~New and existing unit tests pass locally with my …
> group layer data grid; remove the timeout from details component

- packages/geoview-core/public/templates/package-footer-panel.html
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/overview-map/overview-map.tsx
- packages/geoview-core/src/core/containers/focus-trap.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
Fix wcag issues for map, footer-tab, legends
Fixes # (881)
Tested locally, 
Also https://github.com/Canadian-Geospatial-Platform/geoview/issues/906 is not part of this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907)
> 881 wcag issue map

- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-footer-panel/src/data-item.tsx
Fixes #849
got to footer panel, in legend tab, exptend the footer panel, click the visible icon beside item icon/lebal, would toggle the icon and theshowing/hide the lengend item on map
some extra time for the rebase confliction solving and the layer indetification
- - - …
> 849 turn on off layer feature

- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/crosshair/crosshair.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/containers/focus-trap.tsx
Fix map click on static control map.
Fixes # (889)
Locally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/916)
> fix map click on static interacted map

- packages/geoview-core/public/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/918)
> fix(deploy): Error with build size

- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
- packages/geoview-core/src/ui/icons/index.ts
- packages/geoview-layers-panel/src/layer-stepper.tsx
Added file uploading to layer step with file browser and drag and drop.
Fixes #863 
Tested english/French, drag and drop .gpkg and .geojson, load .gpkg and .geojson. Dragged non-supported files, upload with .json that was not geojson.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923)
> 863 file load

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
Fixed legend menu issues
Fixes # (900)
Locally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/924)
> 900 legend menu

- packages/geoview-core/public/templates/cluster.html
- packages/geoview-core/public/templates/layers.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
- packages/geoview-footer-panel/src/legend-item.tsx
Correction of a bug found in the code:
- in layer.ts, forgot to delete the listOfGeoviewLayerConfig when deleting a partialLayerPath using the removeLayersUsingPath method;
Clusters now follow legend filtering. Cluster icon can be displayed in the legend and should be used to toggle clustering on and off. Clusters are returned in the get feature info and it is possible to zoom to the content extent.
Fixes #908 [BUG] Cluster not good number
Fixes #764 Linestring clusters not splitting last two features
using the layers, cluster and package-footer-panel templates.
Issue #908 and #764 were resolved by tracing the code and verifying what was caussing the problem described.
select a cluster …
> Legend filtering does not cover clustering #869

- packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
- packages/geoview-core/src/core/components/details/feature-info.tsx
Fixes #925
- [ x ] New feature (non-breaking change which adds functionality)
go to footer panel, data tab, click the filter button above the data table, change the column, for the number type the operator list would be changed
- [ x ] I have connected the issues(s) to this PR
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
-  ~~New and …
> 925 details and datagrid field type

- packages/geoview-core/public/configs/theme-switching.json
- packages/geoview-core/public/css/style.css
- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/theme-switching.html
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts
Implement theme switching feature capability for various components.
Tested Locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/934)
> implement new theme switching feature

- packages/geoview-core/public/templates/package-layers-panel.html
Closes #949
Links to geojson fixed, link for geopackage added.
Checked links and tried with add layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/961)
> fix(link): Fixed geojson links and added geopackage link

- packages/geoview-core/public/geojson/hydro-metadata.json
- packages/geoview-core/public/geojson/processes-metadata.json
- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/pygeoapi-processes.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
Added the possibility to load a GeoJSON layer using the POST method.
Correction to the Localized String validation
Adjustment to the initialization of the featureInfo.nameField.
Fixes #972, 973 and 974
Using the debugger by tracing the code to confirm it is working as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/975)
> 972-Allow-GeoJSON-layer-creation-from-a-service-call

- packages/geoview-core/public/configs/package-swiper3-config.json
- packages/geoview-core/public/templates/package-swiper.html
- packages/geoview-swiper/src/swiper.tsx
Tested manually on package swiper page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/978)
> 902 swiper wcag

- packages/geoview-core/src/api/api.ts
This exposes the showMessage function for outside-core developers.
Fixes #979
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/980)
> Add showMessage function for it to be usable by outside-core developpers

- packages/geoview-core/public/templates/languages.html
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts
- packages/geoview-core/src/core/utils/create-map-from-config.tsx
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/map/map.ts
Closes #905
Fixed loading config into existing map, and added function to load map into any div.
Tested various map functions for both methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981)
> fix(map): Fixed double config load and added function to create map

- packages/geoview-basemap-panel/src/index.tsx
- packages/geoview-core/src/ui/panel/default-panels.tsx
- packages/geoview-core/src/ui/panel/panel-api.ts
- packages/geoview-core/src/ui/panel/panel-types.ts
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-details-panel/src/index.tsx
- packages/geoview-layers-panel/src/index.tsx
Allow custom style of panel component through custom sx props.
Fixes # ([489](https://github.com/Canadian-Geospatial-Platform/geoview/issues/489))
Manually
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/990)
> #489 Panel style customization

- docs/app/event/event-payloads.md
- packages/geoview-core/public/geojson/hydro-metadata.json
- packages/geoview-core/public/templates/load-test.html
- packages/geoview-core/public/templates/use-cases.html
- packages/geoview-core/public/templates/vector.html
- packages/geoview-core/src/api/events/payloads/vector-config-payload.ts
- packages/geoview-core/src/api/events/payloads/vector-payload.ts
- packages/geoview-core/src/geo/layer/vector/vector-types.ts
- packages/geoview-core/src/geo/layer/vector/vector.ts
Closes #970
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/996)
> refactor(vector): Refactor demo and remove unused vector types

- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/core/utils/utilities.ts
Added new showSuccess, showWarning, showError quick methods.
Also added the utilities module export as part of the api.
This PR isn't breaking code as it is, but I've added a TODO: Refactoring to implement breaking changes that would be beneficial long term.
Fixes #1032
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1033)
> New showMessage methods for variants and exposing utilities module (similar to the geoutilities)

- packages/geoview-core/public/templates/layers/wfs.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
Fixes #997 
Test on wfs.html page with 3 different WFS services
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1037)
> fix(geo): Fix WFS layer bugs

- packages/geoview-core/src/core/utils/date-mgt.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
PR 954 contains a bug that is detected at build time. This PR is to solve it.
Fixes #1042 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1043)
> 1042-Bug_detected_following_PR_954

- packages/geoview-core/public/templates/ui-components.html
Closes #955
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1045)
> fix(deomo): Reactivate the range slider on UI Component page

- packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
This PR will suppress the 2 typescript/react warning  shown on console.
Fixes # ([1021](https://github.com/Canadian-Geospatial-Platform/geoview/issues/1021))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1052)
> 1021 onresize error

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/public/configs/package-footer3-config.json
- packages/geoview-core/public/templates/package-footer-panel.html
- packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
Tested on footer package page with all type of fields (string, number and date). Tested the filter on map as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1056)
> fix (datagrid): Repair filter and add datepicker filter

- packages/geoview-core/src/core/components/overview-map/overview-map.tsx
- packages/geoview-core/src/geo/layer/basemap/basemap.ts
Closes #1030
Changed overview map to use transport map with no shading or labels instead of matching base of main map.
Checked most test pages with and without disable cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059)
> fix(load): fixes basemap loading issues

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/public/geojson/metadata.json
- packages/geoview-core/public/templates/layers/geojson.html
- packages/geoview-core/public/templates/test.html
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
Some developpement broke the initialSettings visibility flag behavior. This PR is to restore the ability to set the initial visibility to false when the map is loaded.
Fixes #1063
Using the test.html template and tracing the code using the chrome devtools to find where the visibility flag was reset to true.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1065)
> 1063-BUG_MapConfig_initialSettings_visible_:_false_not_working

- packages/geoview-core/public/templates/layers/esri-dynamic.html
- packages/geoview-core/public/templates/layers/esri-feature.html
- packages/geoview-core/public/templates/layers/layerlib.js
- packages/geoview-core/public/templates/ui-components.html
Closes #1078
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1079)
> fix(demo): Fix date filter sample

- common/config/rush/pnpm-lock.yaml
- packages/geoview-basemap-panel/package.json
- packages/geoview-basemap-panel/src/basemap-panel.tsx
- packages/geoview-core/package-lock.json
- packages/geoview-core/package.json
- packages/geoview-core/public/configs/package-swiper3-config.json
- packages/geoview-core/public/templates/package-swiper.html
- packages/geoview-details-panel/package.json
- packages/geoview-details-panel/src/details-item.tsx
- packages/geoview-footer-panel/package.json
- packages/geoview-footer-panel/src/details-item.tsx
- packages/geoview-footer-panel/src/legend-item.tsx
- packages/geoview-layers-panel/package.json
- packages/geoview-layers-panel/src/layer-stepper.tsx
- packages/geoview-layers-panel/src/layers-list.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
- packages/geoview-swiper/package.json
- packages/geoview-swiper/src/index.tsx
- packages/geoview-swiper/src/swiper.tsx
Closes #1078
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1086)
> fix(demo): Fix date filter sample (#1079)

- packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
- packages/geoview-core/src/core/components/data-grid/export-button.tsx
- packages/geoview-core/src/core/components/data-grid/json-export-menu-item.tsx
- packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
- packages/geoview-core/src/core/components/data-grid/menu-data-grid.tsx
- packages/geoview-footer-panel/src/data-item.tsx
- packages/geoview-footer-panel/src/group-layers.tsx
This PR refactor `data-grid` component, which include lot of sub components, which make component rendering unstable.
Fixes # ([1055](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1055))
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1102)
> Refactor data grid sub components

- packages/geoview-core/public/templates/languages.html
- packages/geoview-core/src/geo/map/map.ts
Closes #1082
Fixes # 1082
On the html language page, there is a button to reset the language for a map.
https://jolevesq.github.io/geoview/languages.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)
> fix(core): Change language bug

- packages/geoview-core/package.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/nav-bar/buttons/home.tsx
- packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/geo/map/map.ts
- packages/geoview-core/src/ui/icons/index.ts
Closes #1092
Nav-bar button to zoom to location added
Only tested with my location
[__URL for deploy__](https://damonu2.github.io/geoview/geojson.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)
> feat(ui): zoom to my location button added

- packages/geoview-layers-panel/src/layer-stepper.tsx
Closes #803
When layers are sent as query parameters in URL when adding new layer in layers-panel, only requested layers are listed in layer select.
Tested with:
https://geo.weather.gc.ca/geomet?service=WMS&version=1.3.0&request=GetCapabilities&layers=CURRENT_CONDITIONS,METNOTES
https://maps.geogratis.gc.ca/wms/hydro_network_en?service=WMS&version=1.3.0&request=GetCapabilities&layers=nhn:nhn:hydrography:hydro20m_l,nhn:nhn:hydrography:hydro10m_p
https://ows.mundialis.de/services/service?service=WMS&version=1.3.0&request=GetCapabilities&layers=Dark,SRTM30-Hillshade
[__ URL for deploy__](https://damonu2.github.io/geoview/package-layers-panel.html)
- …
> fix(WMS): WMS added in layer panel only includes query layers, if present

- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
Closes #1138 
The footer-bar.tsx file is using old way of MUI to style the component (makeStyle). 
In this PR we update to sxClasses.
Manual test on footer-panel html page
https://cphelefu.github.io/geoview/package-footer-panel.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1141)
> refactor(ui): MUI Style for Footer Bar

- packages/geoview-core/package.json
- packages/geoview-core/public/configs/geolocator-config.json
- packages/geoview-core/schema-default-config.json
- packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
Closes #1126
Footer panel now expand below the map. 2 other issues has been created to continue the work for this panel 
Fixes # 1126
Manual test on footer-panel html page
https://jolevesq.github.io/geoview/package-footer-panel.html
- - - …
> feat(footer): Update style to expand below the map

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/api/events/constants/feature-highlight.ts
- packages/geoview-core/src/api/events/event-types.ts
- packages/geoview-core/src/api/events/payloads/clear-highlights-payload.ts
- packages/geoview-core/src/api/events/payloads/feature-highlight-payload.ts
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/details/feature-info.tsx
- packages/geoview-core/src/core/components/details/layers-list.tsx
Point selected on map highlighted in details, can select and deselect point from details, ability to select multiple points added.
Fixes #1094
Fixes #1095 
Tested on footer-panel and details-panel, with point, multipoint, linestring, and polygons.
[__URL for deploy__](https://damonu2.github.io/geoview/package-footer-panel.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1152)
> feature(ui): Select feature from details/highlight selected detail

- docs/app/geoview-layer/map-config/README.md
- packages/geoview-core/public/templates/package-layers-panel.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/geo/map/map-schema-types.ts
Fixes #1111
Added export property to TypeAppBarProps which enables the export button on the app-bar.
Added the property on package-layers-panel.html, and tested with true, false and missing.
[__URL for deploy__](https://damonu2.github.io/geoview/package-layers-panel.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1159)
> bug(ui): layer panel export button optional

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/raw-feature-info.html
- packages/geoview-core/src/core/components/feature-info/feature-info.tsx
- packages/geoview-core/src/ui/card-media/card-media.tsx
- packages/geoview-core/src/ui/index.ts
Closes #1108
Add capacity to handle links in details component
Fixes #1108
Add the link, json, pdf, script and website to items in the details generated component
https://jolevesq.github.io/geoview/raw-feature-info.html
- - - …
> feat(details): Add support for link in details fields info

- .github/workflows/main.yml
Closes #1180
Fixes #1180
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1186)
> fix(build): Github action trigger on draft

- common/config/rush/pnpm-lock.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1189)
> fix(build): Update pnpm-lock

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/data-table/export-button.tsx
Add translations for data table
Fixes # ([1191](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1191))
1) Visit raw data table page
2) Language translations has been added.
3) Stripe style has been added to the table.
- - - …
> Language Translations for data table

- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/linear-progress/linear-progress.tsx
A linear-progression bar UI component for the core.
A requirement during Clip Zip Ship development.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1213)
> New linear-progress UI component

- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/crosshair/crosshair.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/ui/drawer/drawer.tsx
- packages/geoview-core/src/ui/modal/modal.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/slider/slider.tsx
- packages/geoview-core/src/ui/snackbar/snackbar.tsx
Once we unregister an event, we must provide a handler function to the event.off() function to make sure we are unregistering the right event. This change needs to be done in useEffect once we are unmounting the component.
Fixes #1225 
https://amir-azma.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1228)
> refactor(unregister-events): Refactor unregister events in useEffect

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/data-table/data-table-api.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/data-table/export-button.tsx
- packages/geoview-core/src/core/components/data-table/json-export-button.tsx
- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
Add Export button at right top corner in toolbar.
Fixes # ([1217](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1217))
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)
> 1217 Add Export button with csv and geojson download option

- packages/geoview-core/public/templates/raw-data-table.html
- packages/geoview-core/src/core/components/data-grid/data-grid-api.ts
- packages/geoview-core/src/core/components/data-table/data-table-api.ts
- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
This PR fixes the image and zoom button of each feature row for data table.
Fixes # ([1232](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1232))
1) Open `https://kaminderpal.github.io/geoview/raw-data-table.html`
2) Click on `Create Data Table From Map` button
3) Data table will be displayed in accordion
4) Open accordion.
-  ~~New and existing unit tests pass locally with my …
> fix feature info image and zoom button

- packages/geoview-core/src/ui/accordion/accordion.tsx
There was an issue when we have multiple accordion on the page either as parent or child, once we open one of them, all accordions will be opened. That's because we were sharing one single state to keep track of all accordions.
Fixes #1201 
https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/8b0c581e-3916-4e51-9833-e4f4759ec374
https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/c431c16d-7a4f-4699-a9c9-855fe7191cf4
https://amir-azma.github.io/geoview/
- - - …
> fix(accordion): Fix accordion when we have multiple parent/child accordions

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/raw-data-table.html
- packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx
- packages/geoview-core/src/core/components/data-table/data-table-api.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/data-table/filter-map.tsx
- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
Do Map filter when we do filter search in data table.
Fixes # ([1231](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1231))
1) Open the below given url.
2) Create a table.
3) Switch on for filter on map.
4) Do some search by column.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/12 …
> 1231 filter map

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
Fixes error in click-marker.tsx that was causing the build to fail
Updated and built, checked that highlight functionality was working as intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1253)
> fix(build): fix an issue with intervals in clickmarker.tsx

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
Closes #1054 
This updates MUI to the latest version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1252)
> 1054- Updating mui to latest version

- packages/geoview-core/src/ui/panel/panel-types.ts
- packages/geoview-core/src/ui/text-field/text-field.tsx
New tooltip feature for TextField component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1271)
> Added ToolTip to the TextField ui component

- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
Update data table body cell which have long text. Now long text will have `ellipsis` and tooltip to show full text.
Fixes # ([1267](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1267))
Manually
-  ~~New and …
> 1267 - long text for data table body cell

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/configs/package-swiper3-config-swiper.json
- packages/geoview-core/public/templates/package-swiper.html
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-swiper/package.json
- packages/geoview-swiper/src/swiper.tsx
Swiper updated - now utilizes layerset and accounts for slow loading layers
Fixes # (1177)
Tested on package-swiper.html with all maps.
https://damonu2.github.io/geoview/package-swiper.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297)
> 1177 swiper utilize layerset

- packages/geoview-core/src/geo/layer/layer.ts
Added check for source before adding listeners
Checked data table and swiper pages
https://damonu2.github.io/geoview/raw-data-table.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1320)
> fix(layer): fix no source error

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/core/containers/shell.tsx
Fixes issue where export modal disables interaction with other elements after being closed.
Fixes # 1233
Tested with various elements on add-panels.html
https://damonu2.github.io/geoview/add-panels.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1313)
> fix(export modal): fixed focus issue caused by modal

- packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/stores/geoview-store.ts
- packages/geoview-core/src/core/stores/stores-managers.ts
This PR implements subscribeWithSelector in the code.
Fixes #1340
- [] Bug fix (non-breaking change which fixes an issue)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)
> 1340 store subscribe with selector

- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
Implement custom filtered and selected row message for data table
Fixes # ([1314](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1314))
1) https://kaminderpal.github.io/geoview/raw-data-table.html
2) Selected any row or filter any row.
- - - …
> feature(DataTable): filtered and selected row message

- packages/geoview-core/public/templates/default-config.html
- packages/geoview-core/public/templates/languages.html
- packages/geoview-core/public/templates/package-layers-panel.html
- packages/geoview-core/public/templates/theme-switching.html
- packages/geoview-core/src/api/eventProcessors/appBar-event-process.ts
- packages/geoview-core/src/api/eventProcessors/map-event-process.ts
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/details/feature-info.tsx
- packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/overview-map/overview-map.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/stores/geoview-store.ts
- packages/geoview-core/src/geo/map/map.ts
Closes #1328
Fixes # (#1328 )
Tested on many pages that map click, mouse position, scale, ... events are still working
https://jolevesq.github.io/geoview/index.html
- - - …
> refactor(store): Moved OL events in the store

- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/crosshair/crosshair.tsx
- packages/geoview-core/src/core/containers/focus-trap.tsx
- packages/geoview-core/src/geo/utils/utilities.ts
Closes #1396
Fixes #1396
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1398)
> fix(WCAG): Crosshair does not appear on host

- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts
- packages/geoview-core/src/core/components/overview-map/overview-map.tsx
- packages/geoview-core/src/core/containers/containers-style.ts
This change fixes the app bar covering the map.
Fixes #1202 
https://cphelefu.github.io/geoview/basemaps.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1395)
> fix appbar and footer bar covering map

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/templates/raw-legend-2.html
- packages/geoview-core/src/core/components/legend-2/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend-2/legend-item-details/legend-item-details.tsx
- packages/geoview-core/src/core/components/legend-2/legend-item.tsx
- packages/geoview-core/src/core/components/legend-2/legend.tsx
- packages/geoview-core/src/core/components/legend/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend/legend-item.tsx
- packages/geoview-core/src/core/stores/geoview-store.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-footer-panel/src/index.tsx
Moves initial visibility handling out of legend to be completely handled at layer creation. Also changes feature visibility handling from legend menus to more expected behaviour.
Fixes #1289 
Tested with old legend in package-footer-panel.html and new version in raw-legend-2.html
https://damonu2.github.io/geoview/raw-legend-2.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414)
> refactor(visibility): layer visibility moved out of legend

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/containers/containers-style.ts
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
Closes #1405
Fixes # 1405
On many pages click on map to see click marker and details/feature higlight are good
Test side effect on add panel and footer package pages
https://jolevesq.github.io/geoview/package-footer-panel.html
- - - …
> fix(click): Offset when click on map made bythe flex style

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts
- packages/geoview-core/src/core/components/legend-2/legend-icon-list.tsx
- packages/geoview-core/src/core/components/legend-2/legend-item-details/legend-item-details.tsx
- packages/geoview-core/src/core/components/legend-2/legend-style.ts
- packages/geoview-core/src/core/components/legend-2/legend.tsx
- packages/geoview-core/src/core/stores/geoview-store.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1429)
> Legend fixes rebased

- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/abstract-geoview-raster.ts
Fixes # This PR is for investigation
__Deploy URL__: https://ychoquet.github.io/GeoView/type-of-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1417)
> Encapsulate promises in async functions

- README.md
- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/src/core/stores/stores-managers.ts
Adding zustand-devtools
- X ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1447)
> adding zustand devtools

- packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-enhanced.tsx
- packages/geoview-core/src/ui/select/select-style.ts
- packages/geoview-core/src/ui/select/select.tsx
- packages/geoview-core/src/ui/slider/slider-base.tsx
This PR list a couple adjustments in GeoView Core for the upcoming GeoView-GeoChart PR.
- New TypeFeatureInfoEntryPartial type
- New Esri-related common functions
- Turned the styling of select-style theme usage as optional values (because there are no themes when importing a cgpv ui component in an external package where there are no maps and no ThemeProvider - discuss)
- Tweaked the checkbox-list-enhanced.tsx to align with a pattern in select.tsx (part of this commit too)
- I couldn't find out how to make the MenuItemProps.content property work when passed via TypeMenuItemProps. The Component was failing to unpack. So, I'm directly injecting the component prop - more explicitly - and this works fine.
- Exposing more props to the slider-base, like : orientation, valueLabelFormat, …
> GeoView-GeoChart prerequisites PR for the GeoView-GeoChart plugin PR

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/templates/layers/vector-tiles.html
- packages/geoview-core/public/templates/package-time-slider.html
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
Some small changes to vector tiling to use provided metadata.
Fixes nothing
Tested with vector tiles in many different ways.
https://damonu2.github.io/geoview/vector-tiles.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1464)
> fix(vectortiles): Some fixes to vector tiles

- packages/geoview-core/src/core/components/layers/layers-style.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/legend-2/legend.tsx
Replace table html with grid.
Fixes #1362 
https://cphelefu.github.io/geoview/raw-legend-2.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1474)
> replace table with grid

- packages/geoview-core/src/ui/slider/slider-base.tsx
Adding 'step' support to Slider Base class. I need it for the GeoChart component.
In GeoChart component
[https://alex-nrcan.github.io/geochart/](https://alex-nrcan.github.io/geochart/)
*I can't host it, because I'd have to host a GeoChart which would be pointing to a whole other GeoView cgpv-main.js.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1477)
> Added 'step' prop support to the slider-base.tsx

- packages/geoview-core/src/core/components/layers/layers.tsx
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/legend-2/legend-layer.tsx
- packages/geoview-core/src/core/components/legend-2/legend-styles.ts
- packages/geoview-core/src/core/components/legend-2/legend.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
Improvements to legend tab styling
Fixes #1465 
Fixes #1410 
Fixes #1363 
https://cphelefu.github.io/geoview/raw-legend-2.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490)
> styling legend tab

- packages/geoview-core/src/core/components/common/layer-title.tsx
- packages/geoview-core/src/core/components/common/responsive-grid.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/data-table/data-table-style.ts
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/details-style.ts
- packages/geoview-core/src/core/components/time-slider/time-slider-panel.tsx
- packages/geoview-core/src/core/components/time-slider/time-slider-style.ts
Reuse layer Title component for heading of datatable, details and time slider component.
Extract breakpoints from individual component and use from responsive grid.
Fixes # ([1507](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1507))
1. https://kaminderpal.github.io/geoview/raw-data-table.html
2. https://kaminderpal.github.io/geoview/raw-feature-info-1.html
3. https://kaminderpal.github.io/geoview/package-time-slider.html
-  ~~New and …
> fix(datatable): fix layer title and responsive design #1507

- packages/geoview-core/public/configs/package-footer1-config.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/common/layer-title.tsx
- packages/geoview-core/src/core/components/common/responsive-grid.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
- packages/geoview-core/src/core/components/details/details-api.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/feature-info-new.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
- packages/geoview-core/src/core/components/layers/left-panel/delete-undo-button.tsx
- packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx
- packages/geoview-core/src/core/components/time-slider/time-slider-panel.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/details-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/geo/index.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/utils/feature-highlight.ts
Closes #1350
Moves highlight functionality out of component and adds store values to track highlights.
Tested with various layers and geolocator searches.
https://damonu2.github.io/geoview/package-footer-panel.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)
> refactor(highlight): highlight functionality utilizes store

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/components/icon-stack/icon-stack-style.ts
- packages/geoview-core/src/core/components/icon-stack/icon-stack.tsx
- packages/geoview-core/src/core/components/layers/layers-panel.tsx
- packages/geoview-core/src/core/components/layers/layers.tsx
- packages/geoview-core/src/core/components/layers/left-panel/layers-actions.tsx
- packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/layers/types.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/ui/icon-button/icon-button-types.ts
This PR fixes tooltips to buttons and removes some unnecessary code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1529)
> Connecting legend to store

- packages/geoview-core/src/ui/button-drop-down/button-drop-down-style.ts
- packages/geoview-core/src/ui/button-drop-down/button-drop-down.tsx
- packages/geoview-core/src/ui/button-group/button-group.tsx
- packages/geoview-core/src/ui/index.ts
Added a new button-drop-down ui component which acts like a button with drop down arrow.
Logic taken from this Split Button example [Split button](https://mui.com/material-ui/react-button-group/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1546)
> Added a new button-drop-down ui component which acts like a button with drop down arrow

- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
Cleanup useEffects to make logics more readable. 
We still need to see if we can move the footer-tab component inside the package folder.
Fixes #1136 
https://amir-azma.github.io/geoview/raw-feature-info-1.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1551)
> feat(footer-tab-cleanup): Refactor useEffects

- packages/geoview-core/src/ui/slider/slider.tsx
- packages/geoview-time-slider/src/time-slider.tsx
Fix animation flickering on time slider's marker labelsslider section
Fixes # (1522)
- https://mayurmarakana89.github.io/geoview/package-time-slider.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1562)
> fix(time-slider): fix marker label flickering #1522

- packages/geoview-core/src/core/utils/utilities.ts
Small delay utility function to be used for code testing purposes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1596)
> Small delay function

- common/config/rush/pnpm-lock.yaml
- packages/geoview-basemap-panel/src/basemap-panel.tsx
- packages/geoview-basemap-panel/src/index.tsx
- packages/geoview-core/public/configs/package-geochart-map1-config-geochart.json
- packages/geoview-core/src/api/plugin/abstract-plugin.ts
- packages/geoview-core/src/api/plugin/appbar-plugin.ts
- packages/geoview-core/src/api/plugin/footer-plugin.ts
- packages/geoview-core/src/api/plugin/map-plugin.ts
- packages/geoview-core/src/api/plugin/plugin.ts
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-footer-panel/src/data-table.tsx
- packages/geoview-footer-panel/src/footer-panel-legend-item.tsx
- packages/geoview-footer-panel/src/index.tsx
- packages/geoview-footer-panel/src/layers.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/geochart.tsx
- packages/geoview-geochart/src/index-appbar.tsx
- packages/geoview-geochart/src/index.tsx
- packages/geoview-layers-panel/src/index.tsx
- packages/geoview-layers-panel/src/layer-stepper.tsx
- packages/geoview-layers-panel/src/layers-list.tsx
- packages/geoview-layers-panel/src/panel-content.tsx
- packages/geoview-layers-panel/src/reorder-layers-list.tsx
- packages/geoview-swiper/src/index.tsx
- packages/geoview-swiper/src/swiper.tsx
- packages/geoview-time-slider/src/index.tsx
- packages/geoview-time-slider/src/time-slider.tsx
This PR puts the GeoChart Plugin in the footer by using a new "FooterPlugin" mechanism.
AbstractPlugin now has FooterPlugin, AppBarPlugin and MapPlugin:
- GeoChartFooterPlugin now a FooterPlugin
- GeoChartAppBarPlugin now a AppBarPlugin
- BasemapPanelPlugin now a AppBarPlugin
- LayersPanelPlugin now a AppBarPlugin
- TimeSliderPlugin now a FooterPlugin
- Swiper plugin now using MapPlugin
- FooterPanelPlugin now a AbstractPlugin
Tabs now using a React.ElementType instead of ReactNode (seems to be working better)
Fixes #1568
Hosted here: [https://alex-nrcan.github.io/geoview/](https://alex-nrcan.github.io/geoview/)
-  ~~New and existing unit tests …
> GeoChart Plugin in footer and general Plugin partial refactor

- packages/geoview-core/public/configs/package-time-slider-config-time-slider.json
- packages/geoview-core/public/configs/package-time-slider2-config-footer-panel.json
- packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json
- packages/geoview-core/public/configs/package-time-slider2-config.json
- packages/geoview-core/public/templates/package-time-slider.html
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/api/plugin/plugin.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- packages/geoview-core/src/ui/slider/slider.tsx
- packages/geoview-time-slider/default-config-time-slider-panel.json
- packages/geoview-time-slider/schema.json
- packages/geoview-time-slider/src/index.tsx
- packages/geoview-time-slider/src/time-slider-panel.tsx
- packages/geoview-time-slider/src/time-slider-types.tsx
- packages/geoview-time-slider/src/time-slider.tsx
Use config values to update time slider layout
Fixes # ([1540](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1540))
https://mayurmarakana89.github.io/geoview/package-time-slider.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591 …
> feat(time-slider): update time-slider layout to use config values #1540

- packages/geoview-core/public/templates/layers/esri-dynamic.html
- packages/geoview-core/public/templates/layers/esri-feature.html
- packages/geoview-core/public/templates/layers/wms.html
- packages/geoview-core/public/templates/ui-components.html
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/components/data-table/map-data-table.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
This PR creates a group at the topmost level of the tree when the users put more than one layer configuration on the first level of the layer tree..
Fixes issue #1634 .
Using Chrome Devtools for tracing and debugging. Use the GeoJson template in Type of layers to test this new functionality.
__URL for the tests:__ https://ychoquet.github.io/GeoView/geojson.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1635)
> Create topmost group

- packages/geoview-core/public/configs/package-swiper3-config.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/layers/xyz.html
- packages/geoview-core/public/templates/package-layers-panel.html
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/feature-info-new.tsx
- packages/geoview-core/src/core/components/layers/left-panel/delete-undo-button.tsx
- packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx
- packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
- packages/geoview-core/src/geo/utils/feature-highlight.ts
Closes #805
Closes #1581
Closes #1582 
Closes #1583
Closes #1552
Fixes some of the items in #1526
- adds layerOrder and visibleLayers (in order) to map state store
- links these to legend, details, data-table, and time-slider
- updates them according to changes to legendLayers - movement, visibility changes, and add/remove
- adds new XYZ tile source, replacing missing source
- fixes issue with XYZ tile layer export
- fixes error when trying to select WMS feature
- adds extent box around highlighted features
- restores layer visibility if layer deletion is cancelled
There are issues anywhere there is a group layer at the base level, as the indexes for the sublayers and root layers get mixed up.
Removed GeoJSON layer from raw-feature-info.html to test layer movement, others …
> refactor(layerOrder): move layerOrder to store

- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
Correction applyed as mentioned in the issue #1640 .
Fixes #1640
Using template geojson.html. This PR should eliminate the stack dump.
__Deploy URL:__ https://ychoquet.github.io/GeoView/geojson.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1643)
> BUG-calculateBounds-error

- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
Fixing the error with collapse layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1653)
> fix collapse in layers

- packages/geoview-core/public/templates/layers/geopackage.html
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
Fixes errors in geopackage handling
Tested with geopackage.html
https://damonu2.github.io/geoview/geopackage.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1652)
> GeoPackage Fix

- packages/geoview-basemap-panel/src/basemap-panel-style.ts
- packages/geoview-basemap-panel/src/basemap-panel.tsx
- packages/geoview-basemap-panel/src/index.tsx
- packages/geoview-core/public/css/style.css
- packages/geoview-core/public/templates/package-basemap-panel.html
- packages/geoview-core/public/templates/package-time-slider.html
- packages/geoview-core/src/core/components/app-bar/app-bar-style.ts
- packages/geoview-core/src/core/components/geolocator/geolocator-style.ts
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
1. Fixed styling issues:
> - updated selected state of basepanel card
> - updated hovering state of basepanel card
> - fixed width of basepanel
> - fixed width of searchbox on basepanel
2. Fixed focus issue while closing the 2nd maps basepanel
Fixes # ([1577](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1577))
https://mayurmarakana89.github.io/geoview/package-basemap-panel.html
-  ~~New and existing unit tests pass locally with my …
> refactor (basemap): update styling and focus issues on basepanel close #1577

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
Fixes #1660 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659)
> adding tooltips to layers icons and deactivating layer items

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/geo/layer/layer.ts
Closes #1638
Fixed issue with sublayer highlighting, and updated to deal with group layer path changes
Tested with geojson group layer.
https://damonu2.github.io/geoview/raw-feature-info.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1661)
> fix(highlight): sublayer highlight fixed

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control-styles.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control.tsx
- packages/geoview-core/src/core/components/layers/types.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/ui/slider/slider-base.tsx
Adds ability to handle max opacity from parent.
Fixes #1658 1658
https://cphelefu.github.io/geoview/raw-feature-info.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1656)
> Inheriting Opacity from Parent Layer

- packages/geoview-core/public/geojson/metadata.json
- packages/geoview-core/public/geojson/points_1.json
- packages/geoview-core/public/geojson/points_2.json
- packages/geoview-core/public/geojson/points_3.json
- packages/geoview-core/public/templates/raw-feature-info.html
- packages/geoview-core/src/core/components/common/layer-list-style.ts
- packages/geoview-core/src/core/components/data-table/data-table-style.ts
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/details-style.ts
- packages/geoview-core/src/core/components/details/feature-info-new.tsx
- packages/geoview-core/src/core/components/details/feature-info-table.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/scale/scale-style.ts
- packages/geoview-core/src/core/components/scale/scale.tsx
Refactor left/right panel to use MUI Grid, fixed some issues related to small screen size and more changes for responsive design.
Fixes #1609 
In mobile view, we removed the action button and unselect all buttons for better user experience. Fix issues for scale button and focus focus button if map is visible or not. We should have scroll bars in left panel in case we have many number of layers.
- - - …
> refactor(responsive-changes): Refactor details left/right panel. Fix some scrolling issue and more.

- packages/geoview-core/src/api/plugin/map-plugin.ts
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts
- packages/geoview-core/src/core/containers/focus-trap.tsx
- packages/geoview-swiper/src/swiper.tsx
Closes #1611
Closes #1668
Fixed issue with swiper offset, as well as using the swiper near the map edges causing an additional offset. Also moved the swiper above the nav bar.
Tested moving the swipers around on the swiper page
https://damonu2.github.io/geoview/package-swiper.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1667)
> fix(swiper): offset fixed and moved above navbar

- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-styles.ts
- packages/geoview-core/src/core/components/legend/legend.tsx
Fixes #1610 
Please open legend tab, the legends should have collapsable buttons. Also, also we will the legends based on the felx direction row, not column.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1676)
> refactor(legend-management): Refactor legend flex box and added collapsable feature

- packages/geoview-core/public/templates/default-config.html
- packages/geoview-core/public/templates/languages.html
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/api/plugin/plugin.ts
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
New getLayerConfigAsync function
Vector, Dynamic and WMS done-ish
Better error handling in Plugin async logic
Core functions
Log error when unable to calculate bounds on layer applyViewFilter
createMapFromConfig fixes
Added async when setting projection and showing circular progress
Removed timeout in default-config.html following earlier fix with createMapFromConfig
Cleanup
Fixes some async stuff all around and #1618 on the side (with Johann's modifications around footer package too)
On my host: https://alex-nrcan.github.io/geoview/
- - - …
> Fixing some async stuff and removed some setTimeout

- common/config/rush/pnpm-lock.yaml
- docs/README.md
- docs/programming/logging.md
- packages/geoview-core/src/api/plugin/abstract-plugin.ts
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/types/global-types.ts
- packages/geoview-core/src/core/utils/localStorage.ts
- packages/geoview-core/src/core/utils/logger.ts
- packages/geoview-core/src/core/utils/useWhatChanged.ts
- packages/geoview-geochart/src/geochart.tsx
2 new logging mechanisms to facilitate logging management.
- `logger` which is a straightforward way to log using a level of detail and a bypass depending on environment (development vs production)
- `useWhatChanged` which is a custom implementation of the https://github.com/simbathesailor/use-what-changed with some enhancements and fixes
Fixes #1495 #1594
Hosting it here: https://alex-nrcan.github.io/geoview/
- - - …
> Logging mechanisms

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
Added No Filter for reseting individual filters of geolocator.
Fixes # (1679)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1730)
> feat(geolocator): fixes  #closes1679

- common/config/rush/pnpm-lock.yaml
- docs/programming/logging.md
- packages/geoview-core/public/configs/package-footer-panel-geochart-map1-config-geochart.json
- packages/geoview-core/public/configs/package-footer-panel-geochart-map2-config-geochart.json
- packages/geoview-core/public/configs/package-footer-panel-geochart-map2-config.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/package-footer-panel-geochart.html
- packages/geoview-core/public/templates/package-time-slider.html
- packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
- packages/geoview-core/src/api/event-processors/index.ts
- packages/geoview-core/src/api/plugin/footer-plugin.ts
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/common/enlarge-button.tsx
- packages/geoview-core/src/core/components/common/layer-list.tsx
- packages/geoview-core/src/core/components/common/layout.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/stores/geoview-store.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- packages/geoview-core/src/ui/autocomplete/autocomplete.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/geochart-style.ts
- packages/geoview-geochart/src/geochart.tsx
- packages/geoview-geochart/src/index-appbar.tsx
- packages/geoview-geochart/src/index.tsx
- packages/geoview-time-slider/src/time-slider-panel.tsx
Removed a GeoChart from template for testing
Store processor stuff first
Simplified back code
Bug fix with layer-state
Typos and cleanup
eslint
Fixes #1501
- - - …
> [FEATURE] GeoChart in the store

- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/common/layer-list.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/data-table/data-table-modal.tsx
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
- packages/geoview-core/src/core/components/resize-footer-panel/resize-footer-panel.tsx
- packages/geoview-core/src/core/utils/logger.ts
- packages/geoview-core/src/core/utils/useWhatChanged.ts
`logger` supports useMemo too
Added more log calls, notably for the useMemo() calls
Simplified layer-list
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1735)
> [FEATURE] Added logTraceUseMemo to the logger

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/layers/esri-image.html
- packages/geoview-core/public/templates/layers/type-of-layers.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/layers/types.ts
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
Closes #1626
Support for ESRI Image layers added.
Tested with several layers, most in depth with the layers currently on https://damonu2.github.io/geoview/esri-image.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734)
> feature(esri-image): ESRI image layer support added

- packages/geoview-core/public/index.html
- packages/geoview-core/public/templates/cgdi-demo.html
- packages/geoview-core/public/templates/layers/all-layers.html
- packages/geoview-core/public/templates/layers/type-of-layers.html
- packages/geoview-core/public/templates/layers/xyz.html
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
Added a demo page with all layer types for testing, also added a page for the CGDI catalogue
https://damonu2.github.io/geoview/all-layers.html
https://damonu2.github.io/geoview/water-resources.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)
> feat(demo): All layers and CGDI catalogue page added

- packages/geoview-core/public/templates/theme-switching.html
- packages/geoview-core/src/core/components/app-bar/app-bar-buttons.ts
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/ui/panel/panel-types.ts
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/index-appbar.tsx
`Tabs` and `Panel` ui components had GeoView store leaking in their implementation. I've removed the store dependencies.
This PR is dependent on [#1739](https://github.com/Canadian-Geospatial-Platform/geoview/pull/1739). I couldn't fix a conflict to have this PR distinct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1757)
> [FIX] Removed store dependency from UI components

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/common/layer-list-style.ts
- packages/geoview-core/src/core/components/common/layer-list.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/core/components/icon-stack/icon-stack.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
This PR is dependent on [#1739](https://github.com/Canadian-Geospatial-Platform/geoview/pull/1739). Because of PR #1757 already not being distinct, I've left this one dependent too.
Partially? fixes #1752 
Couldn't reproduce #1724 , fixed?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1758)
> [FEATURE] layerStatus now handled in Layer-List component too

- packages/geoview-core/src/core/components/data-table/data-table.tsx
Convert hyperlinks as string from response to react links.
Fixes #1693 
1) Click on the link provided below
2) Select Water quality layer on map.
3) Open data table and scroll to the right.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1776)
> fix(datatable): convert string hyperlinks to links  #closes1693

- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
Correction for the load error on raw-feature-info.html template.
Fixes #1772
- x ] Bug fix (non-breaking change which fixes an issue)
Using Chrome Devtools to trace and debug..
__Deploy URL__: [Basic Details](https://ychoquet.github.io/GeoView/raw-feature-info.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)
> BUG=raw-feature-info on load

- packages/geoview-core/public/templates/layers/geocore.html
- packages/geoview-core/src/api/plugin/plugin.ts
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/common/layer-list-style.ts
- packages/geoview-core/src/core/components/common/layout.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/feature-info-new.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/index.tsx
- packages/geoview-time-slider/src/time-slider-panel.tsx
`details-panel` highlight fixing when selecting different layers and browsing features.
`click-marker` not touching the feature highlights logic anymore.
Fix for FooterBar collapsing not working. **NEED HELP TESTING MOBILE MODE.**
Some logging tweaking
Layer opacity in the `layers-list`
Comments integration
Details uncollapse on click on map
Details Feature info : the highlight checkbox is disabled when the feature has no geometry
Click-marker doesn't hide automatically when clicking on a feature anymore
Added logs and cleanup
Fixes: #1764 and #1769
**In draft, because if #1749 gets merged before this one, I can add another small thing in this one. Update: 1749 got merged, this PR has been updated with it.**
Hosted here as of Feb. 8th, 18h30 EST : https://alex-nrcan.github.io/geoview/
- …
> [FIX] Details-panel highlighting and more things

- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
Slight refactor to geopackages to fix some bugs and properly get metadata, and get geopackages to work in add layers.
Fixes #1207 
Fixes #1683 
Tested on geopackages.html and raw-add-layers.html
https://damonu2.github.io/geoview/geopackage.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1785)
> refactor(gpkg): refactor and bug fixes for gpkgs

- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/geochart.tsx
Quick refactor to clean up the working code based on store progress and reusability.
Hosted here as of Feb 13th 16h40 : https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1788)
> [REFACTOR] Geochart refactor to clean logic based on core progress

- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
- packages/geoview-core/src/ui/style/themeOptionsGenerator.ts
Attempt to fix the panel event handling vs rendering.
This Panel is actually only used in `app-bar` and `nav-bar`. Not in `footer-bar`. Test the behavior using those first containers.
Hosted here as of Feb 15th 11h45: https://alex-nrcan.github.io/geoview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1813)
> [FIX] Panel event handling vs rendering

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/attribution/attribution.tsx
- packages/geoview-core/src/core/components/map-info/map-info-expand-button.tsx
- packages/geoview-core/src/core/components/map-info/map-info-rotation-button.tsx
- packages/geoview-core/src/core/components/overview-map/overview-map-toggle.tsx
- packages/geoview-core/src/core/containers/containers-style.ts
- packages/geoview-core/src/core/containers/focus-trap.tsx
- packages/geoview-core/src/core/utils/constant.ts
- packages/geoview-core/src/ui/icon-button/icon-button.tsx
- packages/geoview-core/src/ui/popover/popover.tsx
We need to make sure our accessibility features we have added in our project will work on screen readers and also with keyboard navigation
Fixes #1791
https://amir-azma.github.io/geoview/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)
> feat(map-accessibility): Fix some accessibility issues on the map, and related buttons

- docs/programming/logging.md
- packages/geoview-core/src/core/utils/logger.ts
New log methods to track objects
Not hosted yet...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1871)
> feat(logger) New log methods to track objects

- packages/geoview-core/public/templates/demos/demo-osdp-society.html
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/renderer/esri-renderer.ts
Corrections to the loading process. Layers tested are OSDP demo and type of layers.
Fixes #1884
Using the Chrome Devtools.
__Deploy URL used to test__: https://ychoquet.github.io/GeoView/demo-osdp-society.html
AND
https://ychoquet.github.io/GeoView/all-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)
> 1884-[BUG] OSDP load errors.

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/geolocator/geo-list.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-style.ts
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
Fix font bold for search term in search result, limit the query until 3 chars and add support for lat and long.
Fixes #1826 
1) Open https://kaminderpal.github.io/geoview/raw-feature-info.html
2) Click on Geolocator icon in appbar.
3) do search for place, font will be bold for search item in search result.
4) No api request sent until 3 chars are typed.
5) do search for `-86.7792,51.6607`, it will add one item for lat and long.
-  ~~New and existing …
> fix(geolocator): Geolocator

- packages/geoview-core/src/core/components/export/export-modal.tsx
Make sure navigation buttons work properly using screen readers and keyboard navigation.
Fixes #1793 
- [] Bug fix (non-breaking change which fixes an issue)
Please navigate to navigation button using screen reader and keyboard to make sure they work as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1892)
> feat(nav-bar): Add role and tabindex to export that can be opened from nav bar

- packages/geoview-core/src/ui/style/themeOptionsGenerator.ts
Fixes tooltips not working in fullscreen mode.
Fixes #1685 
https://cphelefu.github.io/geoview/  (not deployed, will deploy on-demand)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1896)
> fixes tooltips not working in fullscreen mode

- packages/geoview-core/public/templates/layers/layerlib.js
- packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts
- packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/layer/other/cluster-placeholder.ts
- packages/geoview-core/src/geo/utils/legends-layer-set.ts
Remove layerPhase property from the entire viewer code.
Fixes #1913-Remove_layerPhase_property
Using Chrome Devtools.
__Deploy URL__: https://ychoquet.github.io/GeoView/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916)
> 1913-Remove_layerPhase_property

- packages/geoview-core/src/core/components/app-bar/buttons/version.tsx
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/components/common/layer-list-style.ts
- packages/geoview-core/src/core/components/common/layout-style.ts
- packages/geoview-core/src/core/components/data-table/data-table-style.ts
- packages/geoview-core/src/core/components/details/details-style.ts
- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-style.ts
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
- packages/geoview-core/src/core/components/guide/guide-style.ts
- packages/geoview-core/src/core/components/layers/layers-toolbar.tsx
- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
- packages/geoview-core/src/core/components/layers/left-panel/delete-undo-button.tsx
- packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/legend/legend-styles.ts
- packages/geoview-core/src/core/components/map-info/map-info-style.ts
- packages/geoview-core/src/core/components/mouse-position/mouse-position-style.ts
- packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx
- packages/geoview-core/src/core/components/notifications/notifications-style.ts
- packages/geoview-core/src/core/components/notifications/notifications.tsx
- packages/geoview-core/src/core/components/scale/scale-style.ts
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/ui/button/button-style.ts
- packages/geoview-core/src/ui/panel/panel-style.ts
- packages/geoview-core/src/ui/select/select-style.ts
- packages/geoview-core/src/ui/style/default.ts
- packages/geoview-core/src/ui/style/themeOptionsGenerator.ts
- packages/geoview-core/src/ui/switch/switch-style.ts
PR for using centralizes font sizes.
Fixes #1925
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1924)
> Use centralized font sizes

- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- packages/geoview-core/src/core/utils/date-mgt.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
- packages/geoview-time-slider/src/time-slider-panel.tsx
- packages/geoview-time-slider/src/time-slider-types.tsx
- packages/geoview-time-slider/src/time-slider.tsx
Closes #1817
Added time dimension to ESRI Image layer when there is time info in service. Added apply filter to ESRI Image layer. Updated time-slider to handle ESRI Image time dimension properly.
Tested playing with time slider on the following pages:
https://damonu2.github.io/geoview/package-time-slider.html
https://damonu2.github.io/geoview/demo-osdp-climate.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)
> fix(esriImage): time dimension added

- packages/geoview-geochart/src/geochart-panel.tsx
Fixes # (1844)
https://mayurmarakana89.github.io/geoview/package-footer-panel-geochart.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geovi …
> fix goechart loading

- packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
- packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts
This PR depends on PR: #1978 
It brings back the hover-tooltip functionality, linked with the store.
Hosted here as of April 3rd 12h15: https://alex-nrcan.github.io/geoview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1979)
> feat(hover tooltip)

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/templates/layers/esri-dynamic.html
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/details/feature-info-new.tsx
- packages/geoview-core/src/core/utils/async-semaphore.ts
- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/geo/layer/geometry/geometry.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/renderer/geoview-renderer.ts
- packages/geoview-core/src/geo/utils/feature-highlight.ts
- packages/geoview-core/src/geo/utils/layer-set.ts
This PR implements the getAllFeatureInfo() for Esri Dynamic layers.
Fixes: #1855 #1921 
Hosted, April 10th, 19h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)
> fix(1855) - Esri Dynamic can now query "all" features

- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-styles.ts
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/ui/icons/index.ts
Implement visibility, highlight, zoom icon for each legend layer and fixes some css issues.
Fixes #2007 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2023)
> feat(Legend): fix legend issues  #closes2007

- packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts
- packages/geoview-core/src/core/components/scale/scale-style.ts
- packages/geoview-core/src/core/components/scale/scale.tsx
Fix attribution scale line
Fixes #2015 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2031)
> adding scale lines to scale text

- packages/geoview-core/src/core/components/map-info/map-info-style.ts
- packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts
- packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx
- packages/geoview-core/src/core/components/scale/scale-style.ts
Fixes to attribution. Make sure attribution slides over map. Hide expanding attribution in smaller screens.
Fixes #2013
Fixes #2014 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2032)
> Attribution animation improvements

- .gitattributes
- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2043)
> Added ,gitattributes to standardize eol

- packages/geoview-core/src/core/components/data-table/data-table.tsx
Remove column pinning from data table
Fixes #1818 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2053)
> fix(datatable): remove column pinning  #closes1818

- packages/geoview-core/public/templates/package-swiper.html
- packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/swiper-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/components/click-marker/click-marker.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts
- packages/geoview-core/src/geo/utils/feature-info-layer-set.ts
- packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts
- packages/geoview-core/src/geo/utils/layer-set.ts
- packages/geoview-core/src/geo/utils/legends-layer-set.ts
- packages/geoview-geochart/src/index-appbar.tsx
- packages/geoview-swiper/src/index.tsx
- packages/geoview-time-slider/src/index.tsx
Removed couple subscriptions to orderedLayerInfo from the event processors
Replaced some store subscribe for hooks in some component tsx files
Hosting, April 24th, 23h15: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)
> refactor(subscriptions-and-layer-sets) - Refactored a couple subscriptions and layer-sets processing

- packages/geoview-core/public/css/style.css
- packages/geoview-core/src/core/components/common/use-footer-panel-height.tsx
- packages/geoview-core/src/core/components/export/export-modal.tsx
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
Fixes the map height when no footerbar is available and geochart guide rendering issue.
Fixes #1995 
Fixes #2057 
https://kaminderpal.github.io/geoview/esri-dynamic.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2061)
> fix(map): fix map height  #closes1995

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx
- packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/ui/icons/index.ts
Make draggable work in sort.. otherwise switch to using arrows.
Fixes #2010 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063)
> Using Arrows to Re-order Layers

- packages/geoview-core/public/templates/raw-add-layers.html
- packages/geoview-core/src/geo/map/map-viewer.ts
Closes #1970
Added setCenter, setZoomLevel, setMinZoomLevel, setMaxZoomLevel, setExtent, setMaxExtent functions to map-viewer.
Tested all functions through console.
https://damonu2.github.io/geoview/demos-navigator.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2071)
> feat(view): functions added to update view

- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
Change gvMap to map.
Using Chrome Devtools.
__Deploy URL:__ https://ychoquet.github.io/GeoView/config-sandbox.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2086)
> Change gvMap property back to map.

- packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx
- packages/geoview-core/src/core/components/common/responsive-grid.tsx
Full screen mode in the Footer Panel: unwanted overlapping of the layer/subject boxes for all the detail windows when set in full screen mode.
Fixes #2085 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2088)
> fixing error in responsive layout

- packages/geoview-core/public/templates/raw-add-layers.html
Closes #1996
Closes #1816
Added url's and issue #s for the layers from issues 1996 and 1816
https://damonu2.github.io/geoview/raw-add-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2092)
> feat(urls): Added outlier url's from issues

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
Revert forgotten properties.
using Chrome Devtools.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2113)
> Implementation of the new schema (revert properties)

- packages/geoview-core/public/css/style.css
- packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx
- packages/geoview-core/src/core/components/data-table/export-button.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/export/export-modal-button.tsx
- packages/geoview-core/src/core/containers/shell.tsx
Fix the map size issue created by previous PR
#2116 
Fixes #2102 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2120)
> fix(map): fix mapsize in sandbox page  #closes2102

- packages/geoview-core/src/core/components/data-table/data-table.tsx
Fix column pinning in data table.
Fixes #2110 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2126)
> fix(datatable): fix datatable column pinning  #closes2110

- common/config/rush/pnpm-lock.yaml
- packages/geoview-swiper/src/swiper.tsx
Closes #2097
Swiper now handles base layer paths or parent layer paths and gets associated layers to use.
https://damonu2.github.io/geoview/demo-osdp-land.html
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/12-a-package-swiper.json
https://damonu2.github.io/geoview/package-swiper.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2131)
> fix(swiper): gets proper layer paths from partial

- packages/geoview-core/src/core/components/common/responsive-grid-layout-style.ts
- packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx
- packages/geoview-core/src/core/components/common/responsive-grid.tsx
- packages/geoview-core/src/core/components/guide/guide-panel.tsx
- packages/geoview-core/src/core/components/guide/guide-style.ts
- packages/geoview-core/src/ui/style/themeOptionsGenerator.ts
Dark theme is having issues in the guide tab and also in time slider.
Fixes #2084 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130)
> fixes to dark theme in timeslider

- packages/geoview-core/src/ui/style/themeOptionsGenerator.ts
Selected deep layers were no longer highlighted. This code fixes that.
Fixes #2036 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2134)
> fix highlight layers regression

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/configs/validator/01-simple.json
- packages/geoview-core/public/configs/validator/02-unique-value.json
- packages/geoview-core/public/configs/validator/03-class-breaks.json
- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/core/types/global-types.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts
Create three synchronous configurations:
- One simple feature with temporal dimension;
- One uniqueValue which has two layers and creates à group on the fly;
- one classBreaks with only one layer.
Fixes #2135 
Using Chrome Devtools to traCE AND DEBUG THE CODE.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136)
> Creation of three synchronous configurations

- packages/geoview-core/src/api/plugin/plugin-types.ts
- packages/geoview-core/src/core/components/common/index.ts
- packages/geoview-core/src/core/components/common/use-lightbox.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/data-table/data-table-modal.tsx
- packages/geoview-core/src/core/components/data-table/data-table-style.ts
- packages/geoview-core/src/core/components/data-table/data-table-type.ts
- packages/geoview-core/src/core/components/data-table/data-table-types.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/data-table/export-button.tsx
- packages/geoview-core/src/core/components/data-table/hooks/index.ts
- packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx
- packages/geoview-core/src/core/components/data-table/hooks/useToolbarActionMessage.tsx
- packages/geoview-core/src/core/components/data-table/json-export-button.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/feature-detail-modal.tsx
- packages/geoview-core/src/core/components/details/feature-info-new.tsx
- packages/geoview-core/src/core/components/details/feature-info-table.tsx
- packages/geoview-core/src/core/components/export/export-modal.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/core/components/geolocator/geo-list.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-style.ts
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
- packages/geoview-core/src/core/components/guide/guide-panel.tsx
- packages/geoview-core/src/core/components/guide/guide-style.ts
- packages/geoview-core/src/core/containers/html-to-react.tsx
- packages/geoview-core/src/core/utils/constant.ts
- packages/geoview-core/src/ui/linear-progress/linear-progress.tsx
Refactor the below UI component for performance..
1. details
2. export
3. footer-bar
4. geolocator
5. guide
6. Data table
Fixes #2144 
- - - …
> fix(UI): refactor UI component for performance   #closes2144

- packages/geoview-core/public/templates/raw-add-layers.html
- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
Closes #1805
- Fix problem with WMS, OGC, Esri and Contiune button state
Fixes #1805, #1814
Hosted, May 22, 2:30PM: https://jolevesq.github.io/geoview/raw-add-layers.html
tested the add layer function with all links
- - - …
> fix(addLayer): Fix the add layer bugs

- packages/geoview-core/public/locales/en/guide.md
- packages/geoview-core/public/locales/fr/guide.md
- packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts
- packages/geoview-core/src/api/plugin/plugin.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/app-state.ts
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/layer/geometry/geometry.ts
Closes #2123
Fixes #2123
Hosted May 22, 1PM: https://jolevesq.github.io/geoview/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2167)
> fix(core): Use cgpv-main path to access assets

- packages/geoview-core/public/configs/validator/01-simple.json
- packages/geoview-core/public/configs/validator/02-unique-value.json
- packages/geoview-core/public/configs/validator/03-class-breaks.json
- packages/geoview-core/public/configs/validator/04-geocore.json
- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/public/templates/raw-add-layers.html
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/types/classes/config-exceptions.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/geo/map/map-schema-types.ts
This PR will process the GeoCore layers at the very beginning to get the GeoView layer definition before doing the internal schema validation.
Fixes #2191
Using Chrome Devtool to trace and debug the code.
__Deploy URL__: https://ychoquet.github.io/GeoView/geocore.html and https://ychoquet.github.io/GeoView/config-sandbox.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)
> 2191-Early processing of geocore layers

- packages/geoview-core/src/core/components/common/layer-icon-style.ts
- packages/geoview-core/src/core/components/common/layer-icon.tsx
- packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
- packages/geoview-core/src/geo/layer/layer-sets/legends-layer-set.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
Closes #2072
Adds an event for style changes and emits it when a default style is created. The legend event processor listens to this, and updates the legend icon
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/20-wfs.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197)
> fix(legend): gets icons for default styles

- packages/geoview-core/public/configs/navigator/07-basic-appbar.json
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/common/use-footer-panel-height.tsx
- packages/geoview-core/src/core/components/index.ts
- packages/geoview-core/src/core/components/layers/layers-panel.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
Integrate layers panel in appbar 
Fixes #1889 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2203)
> feat(Appbar): Integrate layers panel in appbar  #closes1889

- packages/geoview-core/public/configs/navigator/10-package-time-slider.json
- packages/geoview-core/public/configs/navigator/14-wms-layer.json
- packages/geoview-core/public/templates/demos/demo-cgdi.html
- packages/geoview-core/public/templates/layers/wms.html
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/components/layers/hooks/helpers.ts
- packages/geoview-core/src/core/components/layers/types.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
Closes #1789
Fixes image icons for WMS and static image layers.
https://damonu2.github.io/geoview/demo-cgdi.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2211)
> fix(legend): fix WMS legend

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/map-info/map-info-expand-button.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
Closes 2183-zoom
- translation
- zoom to layer not working on legend panel for geoJSON
- default zoom/maxExtent
Fixes #2183
Hosted, June 03, 16:3-: https://jolevesq.github.io/geoview/demos-navigator.html
- - - …
> fix(core): zoom default, translation, zoom layer

- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/layers/layers-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx
- packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
PR fixes the following issues;
Fixes #2207 
Fixes #2107 
Fixes #2209 
https://cphelefu.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2213)
> handle layout enlarged in layers

- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-styles.ts
Fix mobile view of legend stack icons
Fixes #2137 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2226)
> fix(legend): fix stack icons on legend for mobile view  #closes2137

- packages/geoview-core/public/templates/layers/wms.html
- packages/geoview-core/public/templates/outliers.html
- packages/geoview-core/public/templates/raw-add-layers.html
- packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
Closes #2220
- If no default style, apply a valid style
Fixes #2220
Hosted May 6th, 4:30: https://jolevesq.github.io/geoview/outliers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial- …
> fix(wms): default style missing

- packages/geoview-core/src/core/components/layers/left-panel/left-panel-styles.ts
- packages/geoview-geochart/src/geochart-panel.tsx
Fixes #2163 
This PR also fixes alignment in the layers tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2231)
> fix error in geocharts

- packages/geoview-core/src/core/components/common/layer-list.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
- Fix focus trap issue of geoview keyboard navigation 
- Fix subtitle elipsis issue when left panel is enlarge.
- Fix border issue WMS layers
- Fix stack icons for group type layer.
Fixes #2155 
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/14-wms-layer.json
- - - …
> 2155 focus trap appbar

- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/geochart-parsing.ts
- packages/geoview-geochart/src/geochart.tsx
Fixes some type issues in GeoviewGeochart package
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2235)
> fix(geoview-geochart) - Fixes some type issues in GeoviewGeochart package

- packages/geoview-core/public/configs/OSDP/function-event-swiper.json
- packages/geoview-core/public/configs/OSDP/function-event.json
- packages/geoview-core/public/configs/navigator/14-wms-layer.json
- packages/geoview-core/public/templates/demos/demo-function-event.html
- packages/geoview-core/public/templates/layers/wms.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/swiper-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/core/stores/state-api.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/geo/layer/basemap/basemap.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
- packages/geoview-swiper/src/swiper.tsx
Closes #1931
OSDP events and functions to get status added. Still needs swiper added to demo-function-event.html. Also fixes some WMS legends.
https://damonu2.github.io/geoview/demo-function-event.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2221)
> feat(events): OSDP events added

- packages/geoview-core/public/templates/demos-navigator.html
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/map/map.tsx
- packages/geoview-core/src/core/components/notifications/notifications.tsx
This PR fixes the following issues;
Fixes #1810 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2242)
> fixing console log errors and screen size

- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/esri-renderer-parser.ts
- packages/geoview-core/src/api/config/types/classes/config-exceptions.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-esri-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/api/config/types/type-guards.ts
- packages/geoview-core/src/api/config/utils.ts
- packages/geoview-core/src/app.tsx
Fetch the service metadata and all the layer's metadata. Compute the layer tree.
Using Chrome Devtools to trace and debug the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2227)
> Fetch metadata and layer tree

- packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/ui/style/themeOptionsGenerator.ts
- packages/geoview-core/src/ui/tabs/tabs-style.ts
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-time-slider/src/time-slider-panel.tsx
1) Fix the size of tabs in footer bar
2) Add guide feature for time slider plugin
Fixes #2232 
https://kaminderpal.github.io/geoview/add-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)
> feat(footerbar): timeslider  #closes2232

- packages/geoview-core/src/core/components/geolocator/geo-list.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
- packages/geoview-core/src/ui/switch/switch-style.ts
Fix geolocator filters show/hide when keyboard enter is pressed while searching any value in search box.
Fixes #2190 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262)
> feat(geolocator): fix geolocator filters  #closes2190

- packages/geoview-core/public/locales/en/guide.md
- packages/geoview-core/public/locales/fr/guide.md
Closes #2246
Replace guide fr by real translation
Fixes #2246
Hosted June 17th, 2pm: https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/05-zoom-layer.json
- - - …
> doc(i18n): Add French guide

- packages/geoview-core/src/core/components/layers/left-panel/delete-undo-button.tsx
Fix remove btn for layer when layer status is loading and processing.
Fixes #2228 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2270)
> fix(layers): fix remove btn for layer status

- packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts
Fixes a loading issue with Geopackage type layers.
Fixes #1922
Host pending..
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2266)
> fix(geopackage-error) - Quick fix to turn layerStatus to error when a Geopackage fails to load

- packages/geoview-core/public/templates/geometry.html
- packages/geoview-core/src/geo/layer/geometry/geometry.ts
Under the map 4 new buttons and a short description of what the buttons does got added. The buttons add a geometry in a group named static which is not the active group. If the group is not created when the buttons are used it create the group and add the geometry concerned by the button used to it. 
Fixes # (2241)
- I used the new buttons to make sure the geometries were appearing on the map. (Add Polyline to static Group, Add Polygon to static Group, Add Circle to static Group and Add marker to static Group.
- I created a group named static with the button "Create Geometry Group".
- I selected the "static" group and deleted it. Making sure the geometries added were getting deleted at the same time.
__URL for the deploy!__
https://guichoquette.github.io/geoview/geometry.html
-  ~~I have …
> Add Group Param To Geometry #2241

- packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts
- packages/geoview-core/src/core/components/notifications/notifications.tsx
- packages/geoview-core/src/core/utils/useSpringAnimations.ts
Fixes #2261 
PR also moves code for animation to useSpringAnimations.
https://cphelefu.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
- - - …
> adding animated box component

- packages/geoview-core/public/configs/navigator/10-package-time-slider.json
- packages/geoview-core/public/templates/add-layers.html
- packages/geoview-core/public/templates/ui-components.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/schemaESRIDynamic..txt
- packages/geoview-core/src/schemaESRIFeature.txt
- Fix the source problem with date filter from esri dynamic
- Add a flag isTimeAware inside the schema to exclude a layer from time function like time slider. This is a value mainly extracted from geocore
Fixes #1765 
Hosted, June 18th, 3:30: https://jolevesq.github.io/geoview/add-layers.html
Add the latest geocore layer in the list - HFE layer whiteout time slider
Add the HFE esri dynamic from add layer - HFE with time slider
-  ~~I have added tests …
> fix(Time): Fix time slider dynamic source and add flag for geocore not time aware

- packages/geoview-core/public/configs/max-record-count.json
- packages/geoview-core/public/templates/demos/demo-gsc.html
- packages/geoview-core/public/templates/demos/demos.html
- packages/geoview-core/public/templates/outliers.html
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
Closes #2199
Also adds GSC demo page
Uses multiple queries to get all features of ESRI Feature layers with maxRecordCount.
https://damonu2.github.io/geoview/outliers.html#HMap2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2280)
> fix(max records): fetch additional features if there is a max response

- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/utils/useSpringAnimations.ts
Fix the details right panel showing when layers are loading
Fixes #2178 
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283)
> fix(details): fix display of right panel when in details  closes2178

- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
Fix the lagging of the search in geolcator component.
Fixes #2286 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2287)
> fix(geolocator): fix lag of searching the geolcations  closes2286

- packages/geoview-core/src/core/components/export/export-modal.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
Fix the loading of font Embed in Css when we export the png from export template.
Before when we try to export the png, 32 requests were sent to google to get the embed fonts.
Now we will fetch the fonts from our dom.
Fixes #2290 
- - - …
> fix(exportModal): fix embed font css for export template

- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
Fixes a bug when a GeoJSON layer has no metadata associated for it to be loaded in Details/DataTable tabs
Fixes #2281 
Hosted, June 26th, 15h: https://alex-nrcan.github.io/geoview/add-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2315)
> fix(GeoJSON) - Fixes a bug when a GeoJSON layer has no metadata associated for it to be loaded in Details/DataTable tabs

- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/scale/scale-style.ts
- packages/geoview-core/src/core/containers/containers-style.ts
* Fixes the horizontal scroll to be same height as width of vertical scroll.
* Fixes color of scale in static mode.
Fixes #2316
Fixes #2306 
Fixes #2318 
Fixes #2320 
https://cphelefu.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json (make sure scrolls are the same)
https://cphelefu.github.io/geoview/default-config.html?p=3857&z=4&c=-100,40&l=en&t=dark&b=basemapId:transport,shaded:false,labeled:true&i=dynamic&cc=overview-map&keys=12acd145-626a-49eb-b850-0a59c9bc7506,ccc75c12-5acc-4a6a-959f-ef6f621147b9#HLCONF6
(Make sure scale lines have same color)
-  ~~I have added tests that prove my …
> fix static map scale

- common/config/rush/pnpm-lock.yaml
- packages/geoview-basemap-panel/package.json
- packages/geoview-core/package.json
- packages/geoview-geochart/package.json
- packages/geoview-swiper/package.json
- packages/geoview-time-slider/package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2328)
> core(release): Update release tag

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/src/geo/layer/geometry/geometry.ts
- packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector-tile.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/gv-esri-feature.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/gv-vector-tiles.ts
- packages/geoview-core/src/geo/map/feature-highlight.ts
- packages/geoview-swiper/package.json
This PR is dependent on PR #2245
This PR migrates Open Layers from 9.1.0 to 9.2.4.
This fixes some issues some people have been getting with, for example, VectorSource in the GeometryApi class.
Hosted, June 28th, 12h: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2250)
> migration(open-layers) - Migration of Open Layers from 9.1.0 to 9.2.4

- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/data-table/data-skeleton.tsx
- packages/geoview-core/src/core/components/data-table/data-table-modal.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/details-skeleton.tsx
- packages/geoview-core/src/ui/button-drop-down/button-drop-down.tsx
- packages/geoview-core/src/ui/index.ts
- packages/geoview-core/src/ui/list/checkbox-list/checkbox-list.tsx
- packages/geoview-core/src/ui/table/table.tsx
1) Fix the skeleton of data table and details component.
2) Remove default props of Button dropdown and checkbox,
Fixes #2307 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2332)
> fix(dataTable): fix the skeleton of datatable

- packages/geoview-core/public/templates/demos/demo-function-event.html
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/layer.ts
Closes #1890
Added event for layer being loaded onto the map
Event notification added to demo-function-event.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)
> feat(event): layer loaded event added

- packages/geoview-core/public/configs/important-layers.json
- packages/geoview-core/public/templates/demos/demo-important-layers.html
- packages/geoview-core/public/templates/demos/demos.html
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/uuid-config-reader.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
Created a demo page that allow to classify layers using three drop-down: group, sub group and service selectors
Fixes: The code allow us to test the services. It doesn't fix error detected. A new issue is created if a service fail and the issue is too complex to resole.
Using Chrome Devtool to trace and debug the code.
__Deploy URL__: https://ychoquet.github.io/GeoView/demo-important-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/234 …
> Important layers to test

- packages/geoview-core/src/api/config/uuid-config-reader.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/core/utils/utilities.ts
Correction of the geocore converter for esriImage layers.
Fixes #2342
Using Chrome Devtool to trace and debbug demo-important-layers.html template.
__Deploy url__: https://ychoquet.github.io/GeoView/demo-important-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2347)
> 2342-BUG GeoCore converter generates esriImage errors

- packages/geoview-aoi-panel/src/index.tsx
- packages/geoview-basemap-panel/src/basemap-panel.tsx
- packages/geoview-basemap-panel/src/index.tsx
- packages/geoview-core/public/configs/loading-packages-config.json
- packages/geoview-core/public/configs/navigator/07-basic-appbar.json
- packages/geoview-core/public/configs/navigator/09-package-basemap-custom-basemap-panel.json
- packages/geoview-core/public/templates/default-config.html
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/plugin/abstract-plugin.ts
- packages/geoview-core/src/api/plugin/appbar-plugin.ts
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/app-start.tsx
- packages/geoview-core/src/core/components/app-bar/app-bar-api.ts
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
Fixes #2334 
Hosted July 4th, 4pm: https://jolevesq.github.io/geoview/loading-packages.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2345)
> fix(plugins): button that does not disieapear

- .github/workflows/type-build.yml
- packages/geoview-core/public/configs/max-record-count.json
- packages/geoview-core/public/templates/outliers/outlier-ESRI-maxRecordCount.html
- packages/geoview-core/public/templates/outliers/outliers.html
- packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
Closes #2199
Closes #2349
Updates esri dynamic getAllFeatureInfo to handle layers with maxRecordCount.
Also fixes type build action.
https://damonu2.github.io/geoview/outlier-ESRI-maxRecordCount.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2353)
> fix(data-table): fixes max record count for table

- packages/geoview-aoi-panel/default-config-aoi-panel.json
- packages/geoview-aoi-panel/default-config-area-of-interest.json
- packages/geoview-aoi-panel/schema.json
- packages/geoview-aoi-panel/src/aoi-panel.tsx
- packages/geoview-aoi-panel/src/index.tsx
- packages/geoview-core/public/configs/navigator/26-package-area-of-interest-aoi-panel.json
I created a Schema for the package area of interest.
Fixes # (2351)
I made sure that the web site was still loading.
the URL for the deploy : https://guichoquette.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)
> 2321-draft version aoi

- packages/geoview-core/public/configs/important-layers.json
- packages/geoview-core/public/templates/demos/demo-important-layers.html
Closes #2358
Fixes #2358 
- Select OSDP in first selector and see all the temporal and cross-departmental group were id layer name is updated in third drop down
- 
Hosted July 10th, 3:30pm: https://jolevesq.github.io/geoview/demo-important-layers.html
- - - …
> demos(OSDP): Add missing layers to OSDP/team imporant layers demo page

- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
- packages/geoview-time-slider/src/time-slider-panel.tsx
Closes #2327
Changed the location where the overview map and map were unmounted in map viewer remove method to fix error with time slider being rendered after removal.
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
Select a layer in time slider and then load another config, no error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2361)
> fix(time-slider): fixes error when removing map

- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts
Closes #2343
Populates the id field of all features
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json - Data table zoom to uses getFeatureById
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2388)
> feat(features): ID added for all features

- docs/app/packages.md
- packages/geoview-aoi-panel/README.md
I Updated the AOI Readme file and doc. 
Fixes # (2374)
I looked at what was the output of the Readme file using ctrl+shift+V will in the Readme file.
[__Add the URL for your deploy!__](https://canadian-geospatial-platform.github.io/geoview/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)
> Readme Doc for AOI

- packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-base-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/gv-group-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/abstract-gv-raster.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
- packages/geoview-core/src/geo/layer/gv-layers/utils.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/gv-ogc-feature.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/gv-wfs.ts
- packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/hover-feature-info-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/legends-layer-set.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
- packages/geoview-time-slider/src/index.tsx
Adds the management of Group Layers in the new GV Layers classes and the Layer-sets.
Hosted July 22nd, 10h30: https://alex-nrcan.github.io/geoview/
**To test thoroughly, because the rebase was over 1 month old**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2393)
> feat(gv-layer-groups) - Group Layers in the new GV Layers classes and the Layer-sets

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/map-info/map-info-rotation-button.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/esri-feature.ts
Closes #2396
Updates ESRI feature loader to do multiple concurrent fetches. Number of fetches and features fetched can be modified.
https://damonu2.github.io/geoview/outlier-ESRI-maxRecordCount.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)
> feat(ESRI Feature): query optimization

- packages/geoview-core/public/templates/demos/demo-function-event.html
- packages/geoview-core/public/templates/demos/demo-world-of-maps.html
- packages/geoview-core/public/templates/demos/demos.html
- packages/geoview-core/src/geo/utils/utilities.ts
- Calculate distance function
- Demo for World of Maps
Fixes #2378 
Hosted, July 24th: 9:30:
https://jolevesq.github.io/geoview/demo-function-event.html
https://jolevesq.github.io/geoview/demo-world-of-maps.html
- - - …
> feat(Utils): Calculate distance utilities function

- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
Small optimization for the icon/canvas thing.
Hosted July 24, 13h45: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)
> feat(data-table-icon) Optimization for the icon/canvas thing

- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-esri-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/uuid-config-reader.ts
- createMetadataLayerTree must not accept GeoCore layers;
- createMetadataLayerTree called with ids must return a tree only for the lids specified;
- Get Config From URL must not fetch service metadata, but only the GeoCore information;
- CreatMapConfig must not fetch service metadata.
Fixes #1881, 2391
Using Chrome Devtool to trace and debug code using https://ychoquet.github.io/GeoView/config-sandbox.html template
- - - …
> First version of the new code

- docs/programming/best-practices.md
- docs/programming/object-oriented.md
- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/types/classes/config-exceptions.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-esri-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/abstract-base-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/type-guards.ts
- packages/geoview-core/src/app.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
Converting JS getter/setter to functions according to best practices.
Fixes #2408
Using Chrome Devtool and https://ychoquet.github.io/GeoView/config-sandbox.html template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2409)
> 2408 convert js getter/setter to functions

- packages/geoview-core/src/core/containers/shell.tsx
PR 2429 caused an issue with map heights in some situations, this fixes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2430)
> fix(shell): fixes map height issue

- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/common/focus-trap-container.tsx
- packages/geoview-core/src/core/components/common/layer-list.tsx
- packages/geoview-core/src/core/components/common/layout.tsx
- packages/geoview-core/src/core/components/common/responsive-grid-layout-style.ts
- packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/data-table/data-table-modal.tsx
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/data-table/export-button.tsx
- packages/geoview-core/src/core/components/details/details-panel.tsx
- packages/geoview-core/src/core/components/details/feature-detail-modal.tsx
- packages/geoview-core/src/core/components/export/export-modal-button.tsx
- packages/geoview-core/src/core/components/export/export-modal.tsx
- packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx
- packages/geoview-core/src/core/components/guide/guide-panel.tsx
- packages/geoview-core/src/core/components/guide/guide-style.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts
- packages/geoview-core/src/ui/tabs/tab-panel.tsx
- packages/geoview-core/src/ui/tabs/tabs.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-time-slider/src/time-slider-panel.tsx
Fix focus issues of details, datatable guide
Fixes #2420 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2426)
> 2420 wcag layerpanel

- packages/geoview-core/public/templates/demos/demo-function-event.html
- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/containers/shell.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- packages/geoview-core/src/core/utils/config/validation-classes/group-layer-entry-config.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
Coordinates filters between initial config, data table and time slider. Also removes some timeouts from map reload/remove/createMapFromConfig. The filters are not reflected in the data table, this will be dealt with in another PR.
Fixes #2234 
Fixes #2108 
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2433)
> 2234 layer filter management

- packages/geoview-core/src/core/components/layers/layers-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
- packages/geoview-core/src/core/components/layers/left-panel/delete-undo-button.tsx
- packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx
- packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/ui/autocomplete/autocomplete.tsx
- packages/geoview-core/src/ui/button/button.tsx
- packages/geoview-core/src/ui/select/select.tsx
- packages/geoview-core/src/ui/text-field/text-field.tsx
Fix the wcag issues of layers tab in footerbar.
Fixes #2428 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2443)
> fix(layers): fix layers tab wcag

- packages/geoview-core/public/configs/navigator/12-package-geochart-geochart.json
- packages/geoview-core/public/configs/navigator/12-package-geochart.json
- packages/geoview-core/src/core/components/lightbox/lightbox.tsx
- packages/geoview-core/src/core/containers/shell.tsx
Fixes # none
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2449)
> demos(geochart): Add AGOL layer for geochart to test

- docs/app/accessibility.md
- packages/geoview-core/public/datasets/geojson/blank.json
- packages/geoview-core/public/datasets/geojson/metadata-blank.json
- packages/geoview-core/public/templates/demos/demo-geojson-inject.html
- packages/geoview-core/public/templates/demos/demos.html
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts
Closes #2411
Added a function to inject new geojson into a layer, overriding existing features.
https://damonu2.github.io/geoview/demo-geojson-inject.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454)
> feat(geojson): Added ability to inject features overriding geojson

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/map-info/map-info.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
Fixes #2481 
Hosted September 17th 11am: https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/12-package-geochart.json
- - - …
> fix(mapInfo): Scale not updated when expend

- packages/geoview-core/public/configs/validator/07-ogc-wfs.json
- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-dynamic-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/esri-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/vector-config/wfs-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/esri-group-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/group-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wfs-group-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wms-group-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/esri-dynamic-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/wms-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/esri-feature-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/wfs.ts
- packages/geoview-core/src/geo/utils/utilities.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486)
> 2472-Config_API_for_WFS

- packages/geoview-core/src/core/utils/date-mgt.ts
Bug correction as mention in issue.
Fixes #2495 
using [wms.html](https://ychoquet.github.io/GeoView/wms.html) template.
__Deploy URL__: https://ychoquet.github.io/GeoView/wms.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2496)
> 2495-Temporal dimension creation bug

- packages/geoview-core/src/api/config/uuid-config-reader.ts
- packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
Closes #2485
Closes #2484
Changes reponse to response in uuid readers to fix bug.
https://damonu2.github.io/geoview/geocore.html
2485 - Add 0a309f2c-4f11-4ddb-bce1-e7ba6f8c20cf - check class visibility functionality
2484 -  Add db177a8c-5d7d-49eb-8290-31e6a45d786c - name should be DFO Species at Risk Critical Habitat 2024
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2499)
> fix(geocore): reponse > response

- packages/geoview-core/src/core/components/geolocator/geo-list.tsx
Fix the geolocator list width
Fixes #2493 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2501)
> fix(geolocator): fix geolocator container width closes2493

- packages/geoview-core/public/configs/validator/09-esri-image.json
- packages/geoview-core/public/templates/config-sandbox.html
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/esri-image-config.ts
- packages/geoview-core/src/api/config/types/classes/map-feature-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/abstract-base-esri-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/esri-image-layer-entry-config.ts
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
Implement the classes needed to process the ESRI-Image GeoView layer configurations.
Fixes #2489
Using the config-sandbox.html template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2502)
> 2489-Config API for ESRI-Image

- packages/geoview-core/public/datasets/geojson/metadata-new.meta
- packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts
- packages/geoview-core/src/api/config/types/classes/sub-layer-config/entry-config-base-class.ts
Important bug corrections to the config api for the add layer functionality.
Fixes #2520
Using the add-layer template ond the code of the PR 2422-Layer tree selection created from a fork of Chris PR.
__Deploy URL__: https://ychoquet.github.io/GeoView/add-layers.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2521)
> 2520-Important corrections for add layer

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/package.json
- packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts
- packages/geoview-core/webpack.common.js
- Fix build error with vector-tiles.ts
- Fix build warning with sass which we aren't using anyways, so removed the package completely
Hosted here, Oct 2nd @ 20h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2534)
> fix(open-layer) - Migrate OpenLayers to 10.2.1. Remove sass package

- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts
- packages/geoview-core/src/core/components/app-bar/buttons/version.tsx
- packages/geoview-core/src/core/components/common/layer-list-style.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- packages/geoview-core/src/core/utils/date-mgt.ts
- packages/geoview-core/src/ui/slider/slider.tsx
- packages/geoview-time-slider/src/time-slider-panel.tsx
- packages/geoview-time-slider/src/time-slider.tsx
- WCAG - focus goes to body and need to tab again. Now works for single handle and dual handle (with time slider, focus goes to first handle)
- Time format standard to ISO on time slider
- Repair label overlap on slider. Still issue in small screen (issue created)
Fixes #1974, #2505
Hosted, October 24th
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
- test time slider panel and layer panel (opacity) …
> fix(slider): Focus isue and standardize time function for time slider

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/common/layer-icon-style.ts
- packages/geoview-core/src/core/components/common/layer-icon.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control-styles.ts
- packages/geoview-core/src/core/components/layers/right-panel/layer-opacity-control/layer-opacity-control.tsx
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-styles.ts
- packages/geoview-core/src/core/components/nav-bar/buttons/basemap-select.tsx
- packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx
Closes #2550, #2564 , #2556
- Fix the border for class visibility in legend panel. Remove the one on layer and reverse color on class items
- Fix the confusing label name for the toggle all class visibility in layers panel
- Fix the inconsistency between WMS legend stack item
- 
Fixes #2550, #2564, #2556
Hosted October 25th, 4pm
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/19-geojson.json
- 2556
- Open layers panel, click on Polygons
- See the new label and divider
- 2564
- …
> fix(ui): Toggle class visibility, legend class border and wms stack icon

- packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/components/data-table/json-export-button.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/geo/layer/geometry/geometry.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/gv-layers/utils.ts
- packages/geoview-core/src/geo/map/feature-highlight.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
DataTable now attempts to export the geometries for the EsriDynamic layers
Fixes #2545
Hosted Nov 4th 16h30: https://alex-nrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)
> fix(data-table) DataTable now attempts to export the geometries for the EsriDynamic layers

- packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx
- packages/geoview-core/src/ui/panel/panel.tsx
Manual testing of the side panels and their interaction with the map info panel was done.
https://pvautour.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2609)
> Finish cleanup of #2581

- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/core/components/export/export-modal.tsx
- packages/geoview-core/src/core/components/scale/scale.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
Closes #2544
Fixes #2544
Hosted nov 21 1pm
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/03-projection-WM.json
See we now have support for imperial scale on map info bar
- - - …
> feat(scale): Add Imperial to map info bar

- .github/workflows/codeql-analysis.yml
Updates CodeQL action
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2679)
> update(codeql): replace deprecated CodeQL version

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/public/templates/demos/demo-osdp-integration.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/api/config/config-api.ts
- packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/layer/other/geocore.ts
- packages/geoview-core/src/geo/map/map-schema-types.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
Closes #2711
Adds a variable to createMapConfigFromMapState to drop geocore layer names to pick them up from the source in a different language. Also adds a translation to image loading error and fixes an issue with names of group layers.
5a65ad7c-561a-466a-8375-8d876624df9d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2717)
> feat(geocore): better language switching for geocore

- packages/geoview-core/public/configs/geojson-inject.json
- packages/geoview-core/public/datasets/geojson/metadata_genericBlank_featureInfo5_20250217.meta
- packages/geoview-core/public/templates/demos/demo-geojson-inject.html
- packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
Also fixes missing outfields failing layer load.
Closes #2777
Update to geojson injection demo, using files from client. Also some very small fixes to missing metadata causing errors.
Hosted 2PM March 4
https://damonu2.github.io/geoview/demo-geojson-inject.html
https://damonu2.github.io/geoview/demo-osdp-integration.html with 981a18a3-6f0d-4109-b3d2-019589fad7c6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2778)
> feat(demo): updates geojson demo page

- packages/geoview-core/src/core/workers/fetch-esri-worker-script.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
Closes #2740
Adds web worker for ESRI Dynamic getAllFeatureInfo queries, and caching for image sources for features with no style attached. Prevents UI freezing on query, and reduces it to under two seconds for formatting.
Hosted March 5, 4:05
For web worker (slow query on highways layer): https://damonu2.github.io/geoview/outlier-performance.html
For slow formatting (buildings - used to take ~5 minutes): https://damonu2.github.io/geoview/outlier-GeoAI.html
- - - …
> fix(data table): fixes data table freezing ui

- packages/geoview-core/public/configs/navigator/05-layer-zoom-levels.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/core/components/common/layer-list-style.ts
- packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details-style.ts
- packages/geoview-core/src/core/components/legend/legend-layer-ctrl.tsx
- packages/geoview-core/src/core/components/legend/legend-layer.tsx
- packages/geoview-core/src/core/components/legend/legend-styles.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/utils/utilities.ts
- packages/geoview-core/src/ui/icons/index.ts
* Add a new button to legend and layer to zoom to visible layer scale
* Add a new param to vcs call to get domain
Fixes #2762
Hosted March 18, 3pm
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/05-layer-zoom-levels.json
- Zoom in and out and see new icon for zoom to visible scale and visibility icon at the same time
- Click on button to zoom to visible scale
- Same mechanism in layers and legend
-  ~~I have added …
> feat(ui): Add zoom to visible scale button

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/public/configs/loading-packages-config.json
- packages/geoview-core/public/configs/navigator/30-package-custom-legend.json
- packages/geoview-core/public/templates/demos-navigator.html
- packages/geoview-core/public/templates/loading-packages.html
- packages/geoview-core/src/api/config/types/config-constants.ts
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/webpack.common.js
- packages/geoview-custom-legend/default-config-custom-legend.json
- packages/geoview-custom-legend/package.json
- packages/geoview-custom-legend/schema.json
- packages/geoview-custom-legend/src/custom-legend-style.ts
- packages/geoview-custom-legend/src/custom-legend.tsx
- packages/geoview-custom-legend/src/index.tsx
- packages/geoview-custom-legend/tsconfig.json
- rush.json
Fixes # 2364
https://ahmedyacinfarah.github.io/geoview/demos-navigator.html?config=./configs/navigator/30-package-custom-legend.json
Here is the link got my host latest test.  3:05 pm 2025-03-21.
- - - …
> Feature/custom legend panel #2364

- packages/geoview-core/public/templates/demos/demo-osdp-integration.html
- packages/geoview-core/public/templates/outliers/outlier-GeoAI.html
- packages/geoview-core/schema.json
- packages/geoview-core/src/api/config/types/config-validation-schema.json
- packages/geoview-core/src/api/config/types/map-schema-types.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
Closes #2805
Closes #2662
Fixes some of #2665 (maybe all?)
Added a "homeView" setting to viewSettings to make the home button view able to change without altering initialView. API call added to change it. If layer IDs are used for the home view, they now dynamically change with the layer. Also fixes missing icons in data table due to apostrophes.
Zoom to layer IDs, API call:
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/05-zoom-layer.json
Delete polygons and try home button - should zoom to lines
Delete lines and should zoom to default max extent
Try: cgpv.api.maps.sandboxMap.setHomeButtonView({'extent': [-120,50,-40,70]})
Home button goes somewhere else.
Different initial view and homeView:
https://damonu2.github.io/geoview/outlier-GeoAI.html
homeView …
> feat(homeView): added settings for home nav button

- packages/geoview-core/src/api/api.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2852)
> fix(core): PAth the deletemap to log a warning instead of error

- packages/geoview-core/src/core/components/data-table/export-button.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-geochart/src/geochart-panel.tsx
Fixes an unnecessary state in the Legend component
Fixes #2803 
Added some minor comments and functions moving in this PR, last minute, no impact.
Hosted April 30 @ 10h50 : https://alex-nrcan.github.io/geoview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2868)
> fix(legendLayers) Fixing an unnecessary state in the legend component

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/core/components/north-arrow/hooks/useManageArrow.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2880)
> fix(merged): Fix a bad merge commited

- packages/geoview-core/public/configs/navigator/17-esri-feature-errors.json
- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/components/data-table/data-table.tsx
- packages/geoview-core/src/core/exceptions/geoview-exceptions.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-base-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-wms.ts
- packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts
- packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/hover-feature-info-layer-set.ts
- packages/geoview-core/src/geo/layer/layer-sets/legends-layer-set.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
Refactoring the code to remove MapViewer attribute from the GV Layers. Phase 2 of removing the mapId references.
Also simplified the getFeatureAtPixel() functions in the GV Layers.
Hosted May 14th 16h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2891)
> refactor(map-viewer) Decoupling map viewer from GV Layers classes

- packages/geoview-core/public/templates/demos/demo-function-event.html
- packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts
- packages/geoview-core/src/core/exceptions/core-exceptions.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts
- packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts
- packages/geoview-core/src/core/utils/fetch-helper.ts
- packages/geoview-core/src/core/utils/utilities.ts
- packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts
- packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts
- packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-image.ts
- packages/geoview-core/src/geo/layer/gv-layers/utils.ts
- packages/geoview-core/src/geo/layer/layer.ts
- packages/geoview-core/src/geo/map/map-viewer.ts
- packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts
Work in progress to improve the layer queries when working with coded value domains.
Host May 23 10h30: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2900)
> fix(layer-highlight) Improves the layer query when working with coded value domains

- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
Fixes the saving of the map state when it comes to multiple geocore layers, including those that get a suffix in their geoviewLayerId.
Hosted May 23 12h10: https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2903)
> fix(geocore-map-state) Fixes the geocore state update

- packages/geoview-core/public/locales/en/translation.json
- packages/geoview-core/public/locales/fr/translation.json
- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-layer-utils.ts
- packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx
- packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx
Hosted June 4th, 9am: https://jolevesq.github.io/geoview/
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x My changes generate no new warnings
- - - …
> fix(translattion): Layer type not translated in more info section

- common/config/rush/pnpm-lock.yaml
- packages/geoview-core/src/api/event-processors/event-processor-children/geochart-event-processor.ts
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts
- packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts
- packages/geoview-drawer/package.json
- packages/geoview-geochart/src/geochart-panel.tsx
- packages/geoview-geochart/src/geochart-parsing.ts
- packages/geoview-geochart/src/geochart-types.ts
- packages/geoview-geochart/src/geochart.tsx
- packages/geoview-geochart/src/index.tsx
Better implementation of the types issues between geochart component, geoview-geochart and geoview-core.
Hosted July 2 @ 13h15 : https://alex-nrcan.github.io/geoview/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2971)
> Better implementation of the types issues between packages

- packages/geoview-core/public/templates/demos/demo-function-event.html
- packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts
- packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts
- packages/geoview-core/src/api/plugin/appbar-plugin.ts
- packages/geoview-core/src/core/components/app-bar/app-bar-api.ts
- packages/geoview-core/src/core/components/app-bar/app-bar-helper.ts
- packages/geoview-core/src/core/components/app-bar/app-bar.tsx
- packages/geoview-core/src/core/components/data-table/data-panel.tsx
- packages/geoview-core/src/core/components/export/export-modal.tsx
- packages/geoview-core/src/core/components/geolocator/geolocator.tsx
- packages/geoview-core/src/core/components/legend/legend.tsx
- packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts
- packages/geoview-core/src/geo/layer/layer.ts
Removed button groups from the app bar
Fixes #2958 
https://damonu2.github.io/geoview/demo-function-event.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2987)
> 2958 app bar groups

- packages/geoview-core/src/core/utils/config/config-validation.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-base-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts
- packages/geoview-core/src/geo/layer/gv-layers/gv-group-layer.ts
- packages/geoview-core/src/geo/layer/layer.ts
Fixes issue with group layer visibility set to false in config.
Fixes #3005
Add CESI layer with custom config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/3006)
> fix(visibility): fixes issue with group layer config visibility

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/main.yml
- .github/workflows/type-build.yml
Build and deploy only occurs on push to develop or manual run, actions updated to latest versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/3011)
> fix(github-actions): updated github actions

- .github/workflows/build-check.yml
Hopeful fix for build-check action
Not tested yet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/3021)
> fix(build-check): update to build-check github action
